const sharedContact = {
  en: {
    kicker: "TWO WAYS TO START",
    title: "Fund a campaign or join the clipper pool.",
    text: "Choose the path that matches your role. The form prepares an email to info@reklamatic.ai; it does not create an account or upload files.",
    modeLabel: "Choose inquiry type",
    modes: { brand: "Advertise as a brand", clipper: "Apply as a clipper" },
    labels: { name: "Name", email: "Email", phone: "Phone / WhatsApp", company: "Brand / company", market: "Target market", platforms: "Target platforms", platformsHint: "TikTok, Instagram Reels, YouTube Shorts", budget: "Indicative campaign budget", source: "Product or source URL", service: "Campaign type", portfolio: "Public account / portfolio", specialty: "Content category", message: "Describe the brand and campaign objective", clipperMessage: "Describe your platforms, category and short-form experience", consent: "I agree to be contacted about this inquiry and have read the", privacy: "Privacy Policy", submit: "Prepare email", required: "Complete the required fields and enter a valid email." },
    safetyNote: "Do not send passwords, access codes, private client material or files you are not authorized to share.",
    services: ["App campaign", "Music release", "Publisher / streamer campaign", "Product campaign"],
    specialties: ["Apps / technology", "Music / entertainment", "Streaming / gaming", "Product / UGC", "Podcast / education", "Other"],
    markets: ["Global", "Türkiye", "Europe", "United States", "Other"],
    budgets: ["Not decided", "Under €2,500", "€2,500–€5,000", "€5,000–€15,000", "€15,000+"],
    direct: "Prefer a direct conversation?",
  },
  tr: {
    kicker: "BAŞLAMANIN İKİ YOLU",
    title: "Kampanyayı fonla veya clipper havuzuna katıl.",
    text: "Rolüne uygun yolu seç. Form info@reklamatic.ai adresine gönderilecek e-postayı hazırlar; hesap açmaz veya dosya yüklemez.",
    modeLabel: "Başvuru türünü seç",
    modes: { brand: "Marka olarak reklam ver", clipper: "Clipper olarak başvur" },
    labels: { name: "Adınız", email: "E-posta", phone: "Telefon / WhatsApp", company: "Marka / şirket", market: "Hedef pazar", platforms: "Hedef platformlar", platformsHint: "TikTok, Instagram Reels, YouTube Shorts", budget: "Tahmini kampanya bütçesi", source: "Ürün veya kaynak bağlantısı", service: "Kampanya türü", portfolio: "Herkese açık hesap / portfolyo", specialty: "İçerik kategorisi", message: "Markanızı ve kampanya hedefini anlatın", clipperMessage: "Platformlarını, kategorini ve kısa video deneyimini anlat", consent: "Bu başvuru hakkında iletişim kurulmasını kabul ediyor ve", privacy: "Gizlilik Politikasını", submit: "E-postayı hazırla", required: "Zorunlu alanları doldurun ve geçerli bir e-posta yazın." },
    safetyNote: "Parola, erişim kodu, gizli müşteri materyali veya paylaşma yetkin olmayan dosya gönderme.",
    services: ["Uygulama kampanyası", "Müzik yayını", "Yayıncı / streamer kampanyası", "Ürün kampanyası"],
    specialties: ["Uygulama / teknoloji", "Müzik / eğlence", "Yayın / oyun", "Ürün / UGC", "Podcast / eğitim", "Diğer"],
    markets: ["Küresel", "Türkiye", "Avrupa", "Amerika Birleşik Devletleri", "Diğer"],
    budgets: ["Henüz belirlenmedi", "₺25.000 altı", "₺25.000–₺75.000", "₺75.000–₺250.000", "₺250.000+"],
    direct: "Doğrudan görüşmek ister misiniz?",
  },
};

export const content = {
  en: {
    lang: "English", skip: "Skip to clipping story", cta: "Advertise", menu: "Open menu",
    nav: [["For brands", "/for-brands"], ["For clippers", "/for-clippers"], ["How it works", "/clipping-campaigns"], ["Operations tool", "#operations"], ["FAQ", "#faq"]],
    hero: {
      kicker: "MANAGED CLIPPING CAMPAIGNS FOR BRANDS",
      titleA: "One brief. Multiple creator accounts.", titleB: "One managed campaign.",
      text: "Reklamatic turns approved brand material into platform-native short videos and manages clipper matching, pre-publish review, distribution tracking and campaign reporting. When a campaign includes an eligible-view guarantee, the agreement defines the target, counting method, reporting window, exclusions and remedy.",
      primary: "Plan a campaign", secondary: "Apply as a clipper", primaryHref: "#brand-contact", secondaryHref: "#clipper-contact",
      status: "TikTok · Instagram Reels · YouTube Shorts", visualAlt: "A managed clipping campaign moving from approved source to creator accounts and measured distribution",
    },
    pathways: {
      kicker: "CHOOSE YOUR PATH", title: "Two roles. One written operating scope.",
      brand: { label: "FOR BRANDS", title: "Start a managed campaign.", text: "Share your objective, budget and approved material. Reklamatic scopes production, matching, approval, distribution tracking and reporting in writing.", cta: "Explore brand campaigns", href: "/for-brands" },
      clipper: { label: "FOR CLIPPERS", title: "Apply with your public portfolio.", text: "Share your platforms and specialties. If a suitable campaign becomes available, the assignment, eligibility and payment terms are written before work starts.", cta: "See the clipper path", href: "/for-clippers" },
    },
    experience: {
      story: { kicker: "CLIPPING IN 20 SECONDS", title: "From approved source to eligible views.", intro: "Scroll through the campaign loop. On mobile, the same four steps stay native and swipe-free.", steps: [
        ["00—04", "Clipping", "One approved source becomes a platform-native short video with its own hook, context, captions and pace.", "SOURCE → CLIP"],
        ["05—09", "Clipping campaign", "A funded campaign adds a brief, selected clippers, eligible accounts, publishing rules and measurement terms.", "BRIEF → ASSIGN"],
        ["10—14", "Create, review, publish", "The clipper produces the post. Reklamatic runs QA; the brand approves; the eligible account publishes.", "QA → APPROVAL"],
        ["15—20", "Report and settle", "Eligible views are counted by the written rules. Campaign reporting and clipper payment follow the agreed model.", "VIEWS → REPORT"],
      ]},
      reel: { kicker: "CAMPAIGN SHOWREEL", title: "Different feeds need different native cuts.", text: "A production-style reel, not a client-results montage.", label: "Reklamatic campaign showreel", play: "Play showreel", pause: "Pause showreel" },
      operations: { kicker: "OPERATIONS TOOL", badge: "REKLAMATIC OPERATIONS", title: "The distribution work has an operating layer.", text: "The Reklamatic extension helps approved clippers manage multiple channels, campaign queues, publishing and submission tracking from one operational view. Retry and recovery states keep interrupted work visible to the operator.", note: "Used inside Reklamatic-managed operations. It is not offered as public self-serve software and the website does not expose account or workflow data.", cta: "Discuss an operated campaign", href: "/contact", slots: [["01", "Channel group", "Ready"], ["02", "Campaign queue", "In review"], ["03", "Publishing", "Tracking"], ["04", "Recovery", "Available"]] },
      film: { kicker: "CAMPAIGN CATEGORIES", title: "One operating model, four creative worlds.", text: "See how the same managed workflow changes for apps, music, publishers and consumer products.", items: [
        ["APP LAUNCH", "Apps", "/media/generated/reklamatic-app-lumen.webp", "Short-form app campaign workflow"],
        ["RELEASE WEEK", "Music releases", "/media/generated/reklamatic-music-noctra.webp", "Music release campaign workflow"],
        ["STREAM MOMENTS", "Publishers & streamers", "/media/generated/reklamatic-streamer-raidline.webp", "Publisher and streamer campaign workflow"],
        ["PRODUCT STORIES", "Products", "/media/editorial/view-guarantee.webp", "Product campaign review workflow"],
      ]},
      economics: { kicker: "TERMS BEFORE WORK", title: "The campaign agreement controls both sides.", brandTitle: "For the campaign buyer", brandText: "A contract-defined view target states eligible accounts, platforms, measurement source, period, exclusions and the shortfall remedy. It does not guarantee sales, profit or virality.", clipperTitle: "For the clipper", clipperText: "The fixed fee, per-1K eligible-view rate, performance terms and eligibility rules are shown before work. An assignment or earnings are never guaranteed.", formula: "written fixed fee (if any) + eligible verified views ÷ 1,000 × campaign rate (if any)" },
    },
    faq: { kicker: "QUICK ANSWERS", title: "Know the model before joining it.", items: [
      ["What is clipping?", "Clipping turns approved source material into a platform-native short video with its own hook, context, captions and pace."],
      ["What is a clipping campaign?", "It adds funding, a written brief, managed clipper assignment, eligible accounts, approvals, publishing and measurement to the individual clips."],
      ["What does a clipper do?", "A clipper accepts campaign terms, creates from approved sources, follows the brief and publishes through an eligible account after QA and brand approval."],
      ["How can a clipper earn?", "The campaign may use a fixed fee, eligible views ÷ 1,000 × campaign rate, a performance model or a written combination. Rates and eligibility appear before work; earnings are not guaranteed."],
      ["Is the view target a virality promise?", "No. When sold, the target covers only contract-defined eligible views and includes exclusions and a shortfall remedy. Sales, profit and virality are outside that term."],
      ["Can I use the operations extension?", "It is an internal operations tool for approved clippers working on Reklamatic-managed campaigns, not public self-serve software."],
    ]},
    contact: sharedContact.en,
    footer: { line: "Managed clipping campaigns for apps, music, publishers, streamers and products.", explore: "Explore", contact: "Contact", legal: "Legal", privacy: "Privacy", terms: "Terms", rights: "All rights reserved." },
  },
  tr: {
    lang: "Türkçe", skip: "Clipping anlatısına geç", cta: "Reklam ver", menu: "Menüyü aç",
    nav: [["Markalar için", "/tr/markalar-icin"], ["Clipper ol", "/tr/clipper-ol"], ["Nasıl çalışır?", "/tr/clipping-kampanyalari"], ["Operasyon aracı", "#operations"], ["SSS", "#faq"]],
    hero: {
      kicker: "MARKALAR İÇİN YÖNETİLEN CLIPPING KAMPANYALARI",
      titleA: "Bir brief. Birden fazla üretici hesabı.", titleB: "Tek kampanya operasyonu.",
      text: "Reklamatic, onaylı marka materyalini platforma uygun kısa videolara dönüştürür; clipper eşleşmesini, yayın öncesi kontrolü, dağıtım takibini ve kampanya raporlamasını yönetir. Uygun görüntülenme garantisi sunulan kampanyalarda hedef, sayım yöntemi, rapor dönemi, hariçler ve telafi maddesi sözleşmede tanımlanır.",
      primary: "Kampanya planla", secondary: "Clipper olarak başvur", primaryHref: "#brand-contact", secondaryHref: "#clipper-contact",
      status: "TikTok · Instagram Reels · YouTube Shorts", visualAlt: "Onaylı kaynaktan üretici hesaplarına ve ölçülen dağıtıma ilerleyen yönetilen clipping kampanyası",
    },
    pathways: {
      kicker: "ÇALIŞMA YOLUNU SEÇ", title: "İki rol. Tek yazılı operasyon kapsamı.",
      brand: { label: "MARKALAR İÇİN", title: "Yönetilen kampanyayı başlat.", text: "Hedefini, bütçeni ve onaylı materyalini paylaş. Reklamatic üretim, eşleşme, onay, dağıtım takibi ve raporlamayı yazılı kapsamda yönetir.", cta: "Marka kampanyalarını incele", href: "/tr/markalar-icin" },
      clipper: { label: "CLIPPER'LAR İÇİN", title: "Herkese açık portfolyonla başvur.", text: "Platformlarını ve uzmanlığını paylaş. Uygun kampanya olduğunda görev, uygunluk ve ödeme koşulları işe başlamadan önce yazılır.", cta: "Clipper yolunu incele", href: "/tr/clipper-ol" },
    },
    experience: {
      story: { kicker: "20 SANİYEDE CLIPPING", title: "Onaylı kaynaktan uygun view'a.", intro: "Kampanya döngüsünü kaydırarak izle. Mobilde aynı dört adım doğal sayfa akışında kalır.", steps: [
        ["00—04", "Clipping", "Tek onaylı kaynak; kendine ait açılışı, bağlamı, altyazısı ve temposu olan platforma doğal kısa videoya dönüşür.", "KAYNAK → KLİP"],
        ["05—09", "Clipping kampanyası", "Fonlanan kampanya; brief, seçili clipper'lar, uygun hesaplar, yayın kuralları ve ölçüm koşulları ekler.", "BRIEF → ATAMA"],
        ["10—14", "Üret, kontrol et, yayınla", "Clipper gönderiyi üretir. Reklamatic kalite kontrolü yapar; marka onaylar; uygun hesap yayınlar.", "KONTROL → ONAY"],
        ["15—20", "Raporla ve hesaplaş", "Uygun view'lar yazılı kurallarla sayılır. Kampanya raporu ve clipper ödemesi mutabık modele göre ilerler.", "VIEW → RAPOR"],
      ]},
      reel: { kicker: "KAMPANYA SHOWREEL'İ", title: "Farklı akışlar, farklı doğal kurgular ister.", text: "Üretim stilini gösteren reel; müşteri sonucu montajı değildir.", label: "Reklamatic kampanya showreel'i", play: "Showreel'i oynat", pause: "Showreel'i duraklat" },
      operations: { kicker: "OPERASYON ARACI", badge: "REKLAMATIC OPERASYONLARI", title: "Dağıtım işinin bir operasyon katmanı var.", text: "Reklamatic eklentisi, onaylı clipper'ların birden fazla kanalı, kampanya kuyruklarını, yayın ve gönderim takibini tek operasyon görünümünden yönetmesine yardımcı olur. Yeniden deneme ve kurtarma durumları kesintiye uğrayan işi operatör için görünür tutar.", note: "Reklamatic'in yönettiği operasyonlarda kullanılır. Herkese açık self-servis yazılım değildir; web sitesi hesap veya iş akışı verisi göstermez.", cta: "Yönetilen kampanyayı görüş", href: "/tr/iletisim", slots: [["01", "Kanal grubu", "Hazır"], ["02", "Kampanya kuyruğu", "Kontrolde"], ["03", "Yayın", "Takipte"], ["04", "Kurtarma", "Kullanılabilir"]] },
      film: { kicker: "KAMPANYA KATEGORİLERİ", title: "Tek operasyon modeli, dört kreatif dünya.", text: "Aynı yönetilen iş akışının uygulama, müzik, yayıncı ve tüketici ürünlerinde nasıl değiştiğini görün.", items: [
        ["UYGULAMA LANSMANI", "Uygulamalar", "/media/generated/reklamatic-app-lumen.webp", "Kısa video uygulama kampanyası iş akışı"],
        ["YAYIN HAFTASI", "Müzik yayınları", "/media/generated/reklamatic-music-noctra.webp", "Müzik yayını kampanyası iş akışı"],
        ["YAYIN KESİTLERİ", "Yayıncı ve streamer'lar", "/media/generated/reklamatic-streamer-raidline.webp", "Yayıncı ve streamer kampanyası iş akışı"],
        ["ÜRÜN HİKÂYELERİ", "Ürünler", "/media/editorial/view-guarantee.webp", "Ürün kampanyası inceleme iş akışı"],
      ]},
      economics: { kicker: "İŞTEN ÖNCE KOŞULLAR", title: "Kampanya sözleşmesi iki tarafı da yönetir.", brandTitle: "Kampanya alıcısı için", brandText: "Sözleşmede tanımlı görüntülenme hedefi; uygun hesapları, platformları, ölçüm kaynağını, dönemi, hariçleri ve eksik kalma telafisini yazar. Satış, kâr veya viral olma garantisi değildir.", clipperTitle: "Clipper için", clipperText: "Sabit ücret, 1.000 uygun doğrulanmış görüntülenme başına oran, performans koşulu ve uygunluk kuralları işe başlamadan gösterilir. Görev veya kazanç garanti edilmez.", formula: "yazılı sabit ücret (varsa) + uygun doğrulanmış görüntülenme ÷ 1.000 × kampanya oranı (varsa)" },
    },
    faq: { kicker: "KISA YANITLAR", title: "Modele katılmadan önce nasıl çalıştığını bil.", items: [
      ["Clipping nedir?", "Onaylı kaynak materyalini kendine ait açılışı, bağlamı, altyazısı ve temposu olan platforma doğal kısa videoya dönüştürmektir."],
      ["Clipping kampanyası nedir?", "Tek tek kliplere fon, yazılı brief, yönetilen clipper ataması, uygun hesap, onay, yayın ve ölçüm katmanı ekler."],
      ["Clipper ne yapar?", "Kampanya koşulunu kabul eder, onaylı kaynaktan üretir, brief'e uyar ve kalite kontrol ile marka onayından sonra uygun hesabında yayınlar."],
      ["Clipper nasıl kazanabilir?", "Kampanya sabit ücret, uygun view ÷ 1.000 × kampanya oranı, performans modeli veya yazılı bir kombinasyon kullanabilir. Oran ve uygunluk işten önce gösterilir; kazanç garanti edilmez."],
      ["View hedefi viral olma sözü mü?", "Hayır. Satılıyorsa yalnız sözleşmede tanımlı uygun view'ları kapsar; hariçler ve eksik kalma telafisi vardır. Satış, kâr ve viral sonuç kapsam dışıdır."],
      ["Operasyon eklentisini kullanabilir miyim?", "Reklamatic'in yönettiği kampanyalarda çalışan onaylı clipper'lar için iç operasyon aracıdır; herkese açık self-servis yazılım değildir."],
    ]},
    contact: sharedContact.tr,
    footer: { line: "Uygulama, müzik, yayıncı, streamer ve ürünler için yönetilen clipping kampanyaları.", explore: "Keşfet", contact: "İletişim", legal: "Yasal", privacy: "Gizlilik", terms: "Koşullar", rights: "Tüm hakları saklıdır." },
  },
};
