const sharedContact = {
  en: {
    kicker: "TWO WAYS TO START",
    title: "Fund a campaign or join the clipper pool.",
    text: "Choose the path that matches your role. The form prepares an email to info@reklamatic.ai; it does not create an account or upload files.",
    modeLabel: "Choose inquiry type",
    modes: { brand: "Advertise as a brand", clipper: "Apply as a clipper" },
    labels: { name: "Name", email: "Email", phone: "Phone / WhatsApp", company: "Brand / company", market: "Target market", platforms: "Target platforms", platformsHint: "TikTok, Instagram Reels, YouTube Shorts", budget: "Indicative campaign budget", source: "Product or source URL", service: "Campaign type", portfolio: "Public account / portfolio", specialty: "Content category", message: "Describe the brand and campaign objective", clipperMessage: "Describe your platforms, category and short-form experience", consent: "I agree to be contacted about this inquiry and have read the", privacy: "Privacy Policy", submit: "Prepare email", required: "Complete the required fields and enter a valid email." },
    safetyNote: "Do not send passwords, access codes, private client material or files you are not authorized to share.",
    services: ["App campaign", "Music release", "Publisher / streamer campaign", "Product campaign"],
    specialties: ["Apps / technology", "Music / entertainment", "Streaming / gaming", "Product / UGC", "Podcast / education", "Other"],
    markets: ["Global", "Türkiye", "Europe", "United States", "Other"],
    budgets: ["Not decided", "Under €2,500", "€2,500–€5,000", "€5,000–€15,000", "€15,000+"],
    direct: "Prefer a direct conversation?",
  },
  tr: {
    kicker: "BAŞLAMANIN İKİ YOLU",
    title: "Kampanyayı fonla veya clipper havuzuna katıl.",
    text: "Rolüne uygun yolu seç. Form info@reklamatic.ai adresine gönderilecek e-postayı hazırlar; hesap açmaz veya dosya yüklemez.",
    modeLabel: "Başvuru türünü seç",
    modes: { brand: "Marka olarak reklam ver", clipper: "Clipper olarak başvur" },
    labels: { name: "Adınız", email: "E-posta", phone: "Telefon / WhatsApp", company: "Marka / şirket", market: "Hedef pazar", platforms: "Hedef platformlar", platformsHint: "TikTok, Instagram Reels, YouTube Shorts", budget: "Tahmini kampanya bütçesi", source: "Ürün veya kaynak bağlantısı", service: "Kampanya türü", portfolio: "Herkese açık hesap / portfolyo", specialty: "İçerik kategorisi", message: "Markanızı ve kampanya hedefini anlatın", clipperMessage: "Platformlarını, kategorini ve kısa video deneyimini anlat", consent: "Bu başvuru hakkında iletişim kurulmasını kabul ediyor ve", privacy: "Gizlilik Politikasını", submit: "E-postayı hazırla", required: "Zorunlu alanları doldurun ve geçerli bir e-posta yazın." },
    safetyNote: "Parola, erişim kodu, gizli müşteri materyali veya paylaşma yetkin olmayan dosya gönderme.",
    services: ["Uygulama kampanyası", "Müzik yayını", "Yayıncı / streamer kampanyası", "Ürün kampanyası"],
    specialties: ["Uygulama / teknoloji", "Müzik / eğlence", "Yayın / oyun", "Ürün / UGC", "Podcast / eğitim", "Diğer"],
    markets: ["Küresel", "Türkiye", "Avrupa", "Amerika Birleşik Devletleri", "Diğer"],
    budgets: ["Henüz belirlenmedi", "₺25.000 altı", "₺25.000–₺75.000", "₺75.000–₺250.000", "₺250.000+"],
    direct: "Doğrudan görüşmek ister misiniz?",
  },
};

export const content = {
  en: {
    lang: "English", skip: "Skip to clipping story", cta: "Advertise", menu: "Open menu",
    nav: [["For brands", "/for-brands"], ["For clippers", "/for-clippers"], ["How it works", "/clipping-campaigns"], ["Operations tool", "#operations"], ["FAQ", "#faq"]],
    hero: {
      kicker: "MANAGED CLIPPING MARKETPLACE",
      titleA: "Campaigns fund the clips.", titleB: "Clippers carry them into the feed.",
      text: "Reklamatic connects apps, artists, publishers, streamers and brands with managed clippers. We run the brief, assignment, QA, brand approval, publishing and eligible-view reporting under one campaign agreement.",
      primary: "Advertise", secondary: "Become a clipper", primaryHref: "#brand-contact", secondaryHref: "#clipper-contact",
      status: "Apps · music · publishers · streamers · products", visualAlt: "A brand campaign moving through Reklamatic to approved clips, eligible accounts and view reporting",
    },
    pathways: {
      kicker: "CHOOSE YOUR SIDE", title: "One marketplace. Two clear roles.",
      brand: { label: "FOR BRANDS", title: "Fund managed distribution.", text: "Set the objective, approved source, platforms, budget and view rules. Reklamatic manages the clipper operation.", cta: "Explore brand campaigns", href: "/for-brands" },
      clipper: { label: "FOR CLIPPERS", title: "Create, publish and earn by the campaign terms.", text: "Review the rate and eligibility rules before accepting work. Produce from approved sources and publish through an eligible account after approval.", cta: "See the clipper path", href: "/for-clippers" },
    },
    experience: {
      story: { kicker: "CLIPPING IN 20 SECONDS", title: "From approved source to eligible views.", intro: "Scroll through the campaign loop. On mobile, the same four steps stay native and swipe-free.", steps: [
        ["00—04", "Clipping", "One approved source becomes a platform-native short video with its own hook, context, captions and pace.", "SOURCE → CLIP"],
        ["05—09", "Clipping campaign", "A funded campaign adds a brief, selected clippers, eligible accounts, publishing rules and measurement terms.", "BRIEF → ASSIGN"],
        ["10—14", "Create, review, publish", "The clipper produces the post. Reklamatic runs QA; the brand approves; the eligible account publishes.", "QA → APPROVAL"],
        ["15—20", "Report and settle", "Eligible views are counted by the written rules. Campaign reporting and clipper payment follow the agreed model.", "VIEWS → REPORT"],
      ]},
      reel: { kicker: "CAMPAIGN SHOWREEL", title: "Different feeds need different native cuts.", text: "A production-style reel, not a client-results montage.", label: "Reklamatic campaign showreel", play: "Play showreel", pause: "Pause showreel" },
      operations: { kicker: "OPERATIONS TOOL", badge: "REKLAMATIC OPERATIONS", title: "The distribution work has an operating layer.", text: "The Reklamatic extension helps approved clippers manage multiple channels, campaign queues, publishing and submission tracking from one operational view. Retry and recovery states keep interrupted work visible to the operator.", note: "Used inside Reklamatic-managed operations. It is not offered as public self-serve software and the website does not expose account or workflow data.", cta: "Discuss an operated campaign", href: "/contact", slots: [["01", "Channel group", "Ready"], ["02", "Campaign queue", "In review"], ["03", "Publishing", "Tracking"], ["04", "Recovery", "Available"]] },
      film: { kicker: "CAMPAIGN CATEGORIES", title: "One operating model, four creative worlds.", text: "Original Reklamatic demo concepts show category direction, not customer work or achieved results.", items: [
        ["LUMEN", "Apps", "/media/generated/reklamatic-app-lumen.webp", "Lumen app campaign concept"],
        ["NOCTRA", "Music releases", "/media/generated/reklamatic-music-noctra.webp", "Noctra music release campaign concept"],
        ["RAIDLINE", "Publishers & streamers", "/media/generated/reklamatic-streamer-raidline.webp", "Raidline streamer campaign concept"],
        ["VELOCITY", "Products", "/media/generated/reklamatic-network-velocity.webp", "Velocity product distribution concept"],
      ]},
      economics: { kicker: "TERMS BEFORE WORK", title: "The campaign agreement controls both sides.", brandTitle: "For the campaign buyer", brandText: "A contract-defined view target states eligible accounts, platforms, measurement source, period, exclusions and the shortfall remedy. It does not guarantee sales, profit or virality.", clipperTitle: "For the clipper", clipperText: "The fixed fee, per-1K eligible-view rate, performance terms and eligibility rules are shown before work. An assignment or earnings are never guaranteed.", formula: "eligible views ÷ 1,000 × campaign rate + fixed bonus" },
    },
    faq: { kicker: "QUICK ANSWERS", title: "Know the model before joining it.", items: [
      ["What is clipping?", "Clipping turns approved source material into a platform-native short video with its own hook, context, captions and pace."],
      ["What is a clipping campaign?", "It adds funding, a written brief, managed clipper assignment, eligible accounts, approvals, publishing and measurement to the individual clips."],
      ["What does a clipper do?", "A clipper accepts campaign terms, creates from approved sources, follows the brief and publishes through an eligible account after QA and brand approval."],
      ["How can a clipper earn?", "The campaign may use a fixed fee, eligible views ÷ 1,000 × campaign rate, a performance model or a written combination. Rates and eligibility appear before work; earnings are not guaranteed."],
      ["Is the view target a virality promise?", "No. When sold, the target covers only contract-defined eligible views and includes exclusions and a shortfall remedy. Sales, profit and virality are outside that term."],
      ["Can I use the operations extension?", "It is an internal operations tool for approved clippers working on Reklamatic-managed campaigns, not public self-serve software."],
    ]},
    contact: sharedContact.en,
    footer: { line: "Managed clipping campaigns for apps, music, publishers, streamers and products.", explore: "Explore", contact: "Contact", legal: "Legal", privacy: "Privacy", terms: "Terms", rights: "All rights reserved." },
  },
  tr: {
    lang: "Türkçe", skip: "Clipping anlatısına geç", cta: "Reklam ver", menu: "Menüyü aç",
    nav: [["Markalar için", "/tr/markalar-icin"], ["Clipper ol", "/tr/clipper-ol"], ["Nasıl çalışır?", "/tr/clipping-kampanyalari"], ["Operasyon aracı", "#operations"], ["SSS", "#faq"]],
    hero: {
      kicker: "YÖNETİLEN CLIPPING PAZARYERİ",
      titleA: "Kampanya klipleri fonlar.", titleB: "Clipper'lar akışa taşır.",
      text: "Reklamatic; uygulama, sanatçı, yayıncı, streamer ve markaları yönetilen clipper ağıyla buluşturur. Brief, atama, kalite kontrol, marka onayı, yayın ve uygun view raporunu tek kampanya sözleşmesiyle yönetir.",
      primary: "Reklam ver", secondary: "Clipper ol", primaryHref: "#brand-contact", secondaryHref: "#clipper-contact",
      status: "Uygulama · müzik · yayıncı · streamer · ürün", visualAlt: "Marka kampanyasının Reklamatic üzerinden onaylı kliplere, uygun hesaplara ve view raporuna ilerlemesi",
    },
    pathways: {
      kicker: "TARAFINI SEÇ", title: "Tek pazaryeri. İki net rol.",
      brand: { label: "MARKALAR İÇİN", title: "Yönetilen dağıtımı fonla.", text: "Hedefi, onaylı kaynağı, platformları, bütçeyi ve view kurallarını belirle. Clipper operasyonunu Reklamatic yönetsin.", cta: "Marka kampanyalarını incele", href: "/tr/markalar-icin" },
      clipper: { label: "CLIPPER'LAR İÇİN", title: "Üret, yayınla, kampanya koşuluna göre kazan.", text: "İşi kabul etmeden oranı ve uygunluk kurallarını gör. Onaylı kaynaktan üret ve marka onayından sonra uygun hesabında yayınla.", cta: "Clipper yolunu incele", href: "/tr/clipper-ol" },
    },
    experience: {
      story: { kicker: "20 SANİYEDE CLIPPING", title: "Onaylı kaynaktan uygun view'a.", intro: "Kampanya döngüsünü kaydırarak izle. Mobilde aynı dört adım doğal sayfa akışında kalır.", steps: [
        ["00—04", "Clipping", "Tek onaylı kaynak; kendine ait açılışı, bağlamı, altyazısı ve temposu olan platforma doğal kısa videoya dönüşür.", "KAYNAK → KLİP"],
        ["05—09", "Clipping kampanyası", "Fonlanan kampanya; brief, seçili clipper'lar, uygun hesaplar, yayın kuralları ve ölçüm koşulları ekler.", "BRIEF → ATAMA"],
        ["10—14", "Üret, kontrol et, yayınla", "Clipper gönderiyi üretir. Reklamatic kalite kontrolü yapar; marka onaylar; uygun hesap yayınlar.", "KONTROL → ONAY"],
        ["15—20", "Raporla ve hesaplaş", "Uygun view'lar yazılı kurallarla sayılır. Kampanya raporu ve clipper ödemesi mutabık modele göre ilerler.", "VIEW → RAPOR"],
      ]},
      reel: { kicker: "KAMPANYA SHOWREEL'İ", title: "Farklı akışlar, farklı doğal kurgular ister.", text: "Üretim stilini gösteren reel; müşteri sonucu montajı değildir.", label: "Reklamatic kampanya showreel'i", play: "Showreel'i oynat", pause: "Showreel'i duraklat" },
      operations: { kicker: "OPERASYON ARACI", badge: "REKLAMATIC OPERASYONLARI", title: "Dağıtım işinin bir operasyon katmanı var.", text: "Reklamatic eklentisi, onaylı clipper'ların birden fazla kanalı, kampanya kuyruklarını, yayın ve gönderim takibini tek operasyon görünümünden yönetmesine yardımcı olur. Yeniden deneme ve kurtarma durumları kesintiye uğrayan işi operatör için görünür tutar.", note: "Reklamatic'in yönettiği operasyonlarda kullanılır. Herkese açık self-servis yazılım değildir; web sitesi hesap veya iş akışı verisi göstermez.", cta: "Yönetilen kampanyayı görüş", href: "/tr/iletisim", slots: [["01", "Kanal grubu", "Hazır"], ["02", "Kampanya kuyruğu", "Kontrolde"], ["03", "Yayın", "Takipte"], ["04", "Kurtarma", "Kullanılabilir"]] },
      film: { kicker: "KAMPANYA KATEGORİLERİ", title: "Tek operasyon modeli, dört kreatif dünya.", text: "Özgün Reklamatic demo konseptleri kategori yönünü gösterir; müşteri işi veya elde edilmiş sonuç değildir.", items: [
        ["LUMEN", "Uygulamalar", "/media/generated/reklamatic-app-lumen.webp", "Lumen uygulama kampanyası konsepti"],
        ["NOCTRA", "Müzik yayınları", "/media/generated/reklamatic-music-noctra.webp", "Noctra müzik yayını kampanya konsepti"],
        ["RAIDLINE", "Yayıncı ve streamer'lar", "/media/generated/reklamatic-streamer-raidline.webp", "Raidline streamer kampanya konsepti"],
        ["VELOCITY", "Ürünler", "/media/generated/reklamatic-network-velocity.webp", "Velocity ürün dağıtım konsepti"],
      ]},
      economics: { kicker: "İŞTEN ÖNCE KOŞULLAR", title: "Kampanya sözleşmesi iki tarafı da yönetir.", brandTitle: "Kampanya alıcısı için", brandText: "Sözleşmede tanımlı view hedefi; uygun hesapları, platformları, ölçüm kaynağını, dönemi, hariçleri ve eksik kalma telafisini yazar. Satış, kâr veya viral olma garantisi değildir.", clipperTitle: "Clipper için", clipperText: "Sabit ücret, 1.000 uygun view başına oran, performans koşulu ve uygunluk kuralları işe başlamadan gösterilir. Görev veya kazanç garanti edilmez.", formula: "uygun view ÷ 1.000 × kampanya oranı + sabit bonus" },
    },
    faq: { kicker: "KISA YANITLAR", title: "Modele katılmadan önce nasıl çalıştığını bil.", items: [
      ["Clipping nedir?", "Onaylı kaynak materyalini kendine ait açılışı, bağlamı, altyazısı ve temposu olan platforma doğal kısa videoya dönüştürmektir."],
      ["Clipping kampanyası nedir?", "Tek tek kliplere fon, yazılı brief, yönetilen clipper ataması, uygun hesap, onay, yayın ve ölçüm katmanı ekler."],
      ["Clipper ne yapar?", "Kampanya koşulunu kabul eder, onaylı kaynaktan üretir, brief'e uyar ve kalite kontrol ile marka onayından sonra uygun hesabında yayınlar."],
      ["Clipper nasıl kazanabilir?", "Kampanya sabit ücret, uygun view ÷ 1.000 × kampanya oranı, performans modeli veya yazılı bir kombinasyon kullanabilir. Oran ve uygunluk işten önce gösterilir; kazanç garanti edilmez."],
      ["View hedefi viral olma sözü mü?", "Hayır. Satılıyorsa yalnız sözleşmede tanımlı uygun view'ları kapsar; hariçler ve eksik kalma telafisi vardır. Satış, kâr ve viral sonuç kapsam dışıdır."],
      ["Operasyon eklentisini kullanabilir miyim?", "Reklamatic'in yönettiği kampanyalarda çalışan onaylı clipper'lar için iç operasyon aracıdır; herkese açık self-servis yazılım değildir."],
    ]},
    contact: sharedContact.tr,
    footer: { line: "Uygulama, müzik, yayıncı, streamer ve ürünler için yönetilen clipping kampanyaları.", explore: "Keşfet", contact: "İletişim", legal: "Yasal", privacy: "Gizlilik", terms: "Koşullar", rights: "Tüm hakları saklıdır." },
  },
};
