export const content = {
  en: {
    lang: "English", skip: "Skip to content", cta: "Start a project", menu: "Open menu",
    nav: [["About", "/about"], ["Services", "/clipping-agency"], ["Campaigns", "/case-studies"], ["Process", "#process"], ["Resources", "/blog"], ["FAQ", "#faq"]],
    hero: { kicker: "Your clipping agent for short-form distribution", titleA: "One source.", titleB: "Many chances to be seen.", text: "Reklamatic turns podcasts, interviews, founder content and campaign footage into platform-native clips—with clear approvals, rights checks and a learning loop.", primary: "Build my clipping plan", secondary: "See the workflow", pills: ["Human creative judgment", "Brand-safe approvals", "TR + EN delivery"], visualLabel: "Source → moment → platform", visualTitle: "A repeatable clipping workflow", visualAlt: "Conceptual Reklamatic clipping workflow from long-form content to vertical clips", floating: ["MOMENT MAP", "00:01.2", "LEARNING LOOP"] },
    ticker: ["PODCASTS", "FOUNDER CONTENT", "EDUCATION", "PRODUCT STORIES", "INTERVIEWS", "LIVE STREAMS"],
    clipperRole: { kicker: "What a clipper does", title: "The clipper carries meaning from the source into the feed.", text: "A clipper is more than an operator. The role combines editorial judgment, short-form craft and reliable quality control while staying inside the approved brief.", items: [
      ["01", "Understand & select", "Review the brief, rights, source and audience; shortlist moments that can stand alone without misleading context."], ["02", "Hook & adapt", "Build the opening, captions, pacing, reframing and platform variants while preserving the speaker's meaning and brand rules."], ["03", "QA & deliver", "Check language, claims, audio, visual safety and specifications; organize delivery. Publishing happens only with written scope, access and approval."],
    ], note: "Reklamatic does not currently present an open creator network, automated job marketplace or performance-pay program." },
    what: { kicker: "Clipping, explained", title: "Clipping is editorial strategy—not an auto-crop button.", text: "The work starts by understanding why a moment matters, then rebuilding it for a viewer with no context. A strong clip combines selection, a clean opening, pacing, captions, visual proof and a platform-specific ending.", cards: [
      ["01", "Select for meaning", "We look for useful claims, tension, demonstrations, emotion and self-contained story arcs—not random short excerpts."],
      ["02", "Rebuild for the feed", "Hooks, context, captions, reframing, pacing and graphics turn the selected moment into a complete short video."],
      ["03", "Iterate responsibly", "Approved publishing data can guide later themes and formats. A signal informs the next test; it never guarantees reach."],
    ]},
    process: { kicker: "How it works", title: "From source file to learning loop in four controlled steps.", steps: [
      ["01", "Brief & rights", "Define audience, goal, platforms, source ownership, brand rules, prohibited claims and approval owners."],
      ["02", "Moment map", "Review the source and propose moments, angles and hook directions before production volume is locked."],
      ["03", "Edit & approve", "Build platform-native versions with captions and context. Nothing branded is published without the agreed approval."],
      ["04", "Deliver & learn", "Deliver organized files or publish only when scoped. Review available signals and document the next creative hypothesis."],
    ]},
    useCases: { kicker: "Useful source material", title: "Start with content that already contains expertise, proof or a story.", items: [
      ["Podcasts & interviews", "Mine clear opinions, practical lessons, stories and guest moments across each episode."],
      ["Founder & expert content", "Build a recognizable point of view from talks, webinars, AMAs and direct-to-camera recordings."],
      ["Product & brand footage", "Reframe demonstrations, customer questions, behind-the-scenes material and campaign shoots."],
      ["Education & communities", "Turn lessons, livestreams and member conversations into discoverable, context-rich clips."],
    ]},
    services: { kicker: "Brand campaigns", title: "Choose the operating layer your team is missing.", intro: "For brands, creators, podcast teams, educators and product companies with approved source material. Inputs, outputs, approvals, publishing responsibility and measurement are defined before production.", overview: [
      ["You provide", "Source access, rights, audience, goals, brand rules and one approval owner"], ["We scope", "Selection, creative direction, platform versions, review rounds and delivery"], ["Publishing", "Client-owned unless written access and responsibility are agreed"], ["Success signals", "Available reach, watch behavior, engagement and attributable actions—not guarantees"],
    ], tabs: [
      { label: "Clip strategy", title: "Know what to cut—and why", desc: "A source audit, audience framing, content pillars, hook directions and a practical clipping roadmap before recurring production.", facts: [["Best for", "New clipping programs"], ["Output", "Moment and format plan"], ["Decision", "Proceed with a clear scope"]] },
      { label: "Always-on clipping", title: "A recurring external clipping desk", desc: "Source review, selection, editing, captions, platform adaptation and a consistent review rhythm for active teams.", facts: [["Best for", "Ongoing long-form pipelines"], ["Cadence", "Agreed production batches"], ["Control", "Client approval before release"]] },
      { label: "Campaign sprint", title: "Focused creative around one moment", desc: "A bounded project for a launch, event, season, product story or high-value recording—with defined start and finish.", facts: [["Best for", "Time-sensitive campaigns"], ["Input", "Approved campaign sources"], ["Output", "Written deliverable schedule"]] },
      { label: "Distribution support", title: "Add planning and publishing support", desc: "Channel planning, scheduling and review can be added where access, responsibilities and approvals are explicitly agreed.", facts: [["Best for", "Teams needing operations"], ["Access", "Minimum necessary permissions"], ["Reporting", "Platform data in context"]] },
    ], ask: "Request a tailored scope", note: "We do not sell guaranteed virality, guaranteed views or an undisclosed automated posting system." },
    becomeClipper: { kicker: "Become a clipper", title: "Share your craft for possible future collaboration.", text: "We are collecting interest and portfolios from editors—not running an instant membership portal or live job board.", items: [["Public portfolio", "Link work we can review without a login, password or private file request."], ["Specialties", "Tell us your strongest formats, platforms, languages, captions and motion skills."], ["Working style", "Share availability, communication approach, turnaround preferences and QA habits."], ["Honest status", "Submission adds you to an interest pool; it does not guarantee onboarding, assignments, rates or earnings."]], cta: "Open clipper-interest form", note: "Do not send confidential client files or unlisted material you are not authorized to share." },
    measurement: { kicker: "Measurement", title: "Turn accessible platform signals into the next creative decision.", text: "Reporting uses analytics available on the agreed accounts and platforms. Metric definitions, access, reporting period and campaign scope are written before launch; organic reach and conversions are never guaranteed.", pillars: [
      ["Views / reach", "Exposure indicators; a view is not necessarily a unique person."], ["Watch behavior", "Watch time, opening retention and completion where the platform provides them."], ["Engagement", "Likes, comments, saves and shares interpreted alongside format and audience."], ["Action", "Clicks and conversions only when a trackable link or CTA setup exists; attribution remains limited."],
    ], headers: ["Signal", "What it can tell us", "What it cannot prove"], rows: [
      ["Opening retention", "Whether the first seconds held attention", "Why every viewer stayed or left"], ["Completion", "How often the full clip was watched", "Future performance on a new post"], ["Saves & shares", "Possible utility or resonance", "Revenue or brand lift by itself"], ["Clicks / conversions", "Attributed action under the chosen setup", "All influence across devices and channels"],
    ], note: "Historical operated-account screenshots, if ever shown, are not client campaign reports. Cross-platform counts are not unique people, attribution is limited and performance varies." },
    brandSafety: { kicker: "Brand safety", title: "Every clip passes through explicit boundaries and human review.", text: "No workflow can promise absolute safety. We reduce avoidable risk by defining rights, claims, access and escalation before production.", items: [
      ["Rights & source approval", "Use only client-owned, licensed or explicitly authorized footage, music, logos and other materials."], ["Brand rules & disclosures", "Document allowed and prohibited topics, language, visuals, claims, ad or collaboration disclosures and platform policy requirements."], ["Human QA & client approval", "Check context, captions, claims, audio, specifications and brand fit; obtain the agreed client approval before delivery or publishing."], ["Escalation & integrity", "Reject unsuitable material, define correction or takedown contacts, and review suspicious or invalid traffic rather than presenting it as performance."],
    ], note: "The client remains responsible for confirming legal claims and source rights unless a written agreement explicitly assigns a different responsibility." },
    scenarios: { kicker: "Illustrative campaign examples", title: "See the shape of a plan without mistaking it for a case study.", text: "These are fictional planning examples—not Reklamatic client results. They contain no real brand, testimonial, schedule, budget, reach claim or outcome metric.", label: "ILLUSTRATIVE CAMPAIGN EXAMPLE", source: "Source", goal: "Goal", outputs: "Possible outputs", signals: "Signals to review", items: [
      { alt: "Abstract illustration for the fictional Nova Audio podcast clipping plan", title: "NOVA AUDIO — weekly expert podcast", source: "An approved long-form episode and transcript", goal: "Make useful ideas understandable without episode context", outputs: "Moment map, hook options, captioned vertical cuts and approval sheet", signals: "Opening retention, completion, saves and qualitative comments" },
      { alt: "Abstract illustration for the fictional Vela App launch clipping plan", title: "VELA APP — product launch sprint", source: "Founder explanation, product demo and approved claims", goal: "Explain the product from several audience questions", outputs: "Demo, objection and founder-story variants for selected platforms", signals: "Watch behavior, clicks when tracked and conversion attribution limits" },
      { alt: "Abstract illustration for the fictional Northstar Academy campaign", title: "NORTHSTAR ACADEMY — founder-led education", source: "Webinar, Q&A and direct-to-camera lessons", goal: "Build a consistent expert point of view", outputs: "Topic clusters, self-contained lessons, platform versions and learning notes", signals: "Completion, saves, shares and recurring topic response" },
    ], note: "Illustrative only. Final volume, timeline, channels, permissions, measurement and commercial terms depend on the actual written scope." },
    compare: { kicker: "Make-or-buy decision", title: "Choose a clipping partner when you need the system around the edit.", headers: ["Capability", "Reklamatic", "Basic editing", "In-house"], rows: [["Moment selection", "Strategic source review", "Often supplied timestamps", "Depends on team"], ["Platform versions", "Scoped per channel", "Often one master", "Manual"], ["Approval design", "Defined in workflow", "Usually separate", "Owned internally"], ["Learning notes", "Can be built into cadence", "Usually separate", "Must be maintained"]], disclaimer: "A freelance editor or internal workflow may be the better choice for low-volume, tightly directed work. Reklamatic fits teams that need a repeatable external operating layer." },
    resources: { kicker: "Clipping resources", title: "Three practical tools before the first cut.", text: "Open each inline checklist—there is no missing download or blog page.", open: "Open checklist", items: [
      ["SOURCE", "Source-readiness checklist", "Confirm the material is safe and usable before review.", ["Ownership or license confirmed", "Audio and image quality checked", "Private sections and sensitive data removed", "Approval owner named"]],
      ["CAMPAIGN", "Campaign-brief checklist", "Give editors a decision-ready brief instead of a vague request.", ["Audience and business goal", "Platforms and brand voice", "Allowed and prohibited claims", "Publishing owner and review timing"]],
      ["MEASUREMENT", "Measurement terms glossary", "Agree on what each signal means before reporting.", ["Views are not always unique people", "Retention and completion are different", "Engagement needs context", "Clicks and conversions require tracking and limited attribution"]],
    ]},
    faq: { kicker: "Questions, answered", title: "Know the workflow before you send a source file.", items: [
      ["What is clipping?", "Clipping is the editorial and production process of turning selected moments from longer material into self-contained short videos designed for specific platforms."],
      ["Is this just AI auto-clipping?", "No. Tools may assist transcription or production, but editorial choice, context, brand fit and approval require human judgment."],
      ["What source material works?", "Podcasts, interviews, webinars, lessons, livestreams, founder recordings, product footage and campaign shoots can work when rights and quality are suitable."],
      ["How many clips will I receive?", "The count depends on source quality, duration, platforms and creative depth. Your written proposal states exact deliverables before work begins."],
      ["Can you publish for us?", "Publishing support can be scoped. Account access, approval, scheduling responsibility and reporting boundaries are agreed in writing."],
      ["Do you guarantee views or virality?", "No. Organic reach is controlled by platforms and audiences. We guarantee only the work and process described in the signed scope."],
      ["Who owns the final clips?", "Usage and ownership terms are confirmed in the proposal or agreement, including any limits created by third-party footage, fonts, music or licenses."],
      ["How do revisions work?", "Revision rounds, feedback format and approval owners are defined before production so both sides know what is included."],
      ["Can I apply as a clipper?", "Yes, you may send a public portfolio and specialties through the clipper-interest form. It is not automated enrollment and does not guarantee paid work."],
    ]},
    contact: { kicker: "Two briefs, one clear next step", title: "Start a brand plan or share your clipper craft.", text: "Select your route. The form prepares a structured email in your own mail app; it does not upload or store files, create an account or promise a placement.", modeLabel: "Choose contact path", modes: { brand: "Brand / creator brief", clipper: "Clipper interest" }, labels: { name: "Your name", email: "Email", phone: "Phone / WhatsApp", company: "Company / channel", market: "Primary market", platforms: "Target platforms", platformsHint: "TikTok, Reels, Shorts", budget: "Indicative monthly budget", source: "Source content URL", service: "Service interest", portfolio: "Public portfolio URL", specialty: "Primary specialty", message: "What should this program achieve?", clipperMessage: "Tell us about your editing style, languages and availability", consent: "I agree to be contacted about this request and have read the", privacy: "Privacy Policy", submit: "Prepare my email", required: "Please complete the required fields and use a valid email address." }, safetyNote: "Do not paste private links, passwords, access tokens, personal data or confidential client material. Use a public, authorized URL only.", services: ["Clip strategy", "Always-on clipping", "Campaign sprint", "Distribution support"], specialties: ["Podcast / talking-head", "Product / UGC", "Music / culture", "Motion graphics", "Multilingual editing", "Other"], markets: ["Global", "Türkiye", "United States", "Europe", "Other"], budgets: ["Not decided", "Under €2,500", "€2,500–€5,000", "€5,000–€15,000", "€15,000+"], direct: "Prefer a direct conversation?" },
    footer: { line: "Clipping strategy, short-form production and distribution support from Türkiye to global teams.", explore: "Explore", contact: "Contact", legal: "Legal", privacy: "Privacy", terms: "Terms", rights: "All rights reserved." },
  },
  tr: {
    lang: "Türkçe", skip: "İçeriğe geç", cta: "Proje başlat", menu: "Menüyü aç",
    nav: [["Hakkımızda", "/tr/hakkimizda"], ["Hizmetler", "/tr/clipping-ajansi"], ["Kampanyalar", "/tr/ornek-kampanyalar"], ["Süreç", "#process"], ["Kaynaklar", "/tr/blog"], ["SSS", "#faq"]],
    hero: { kicker: "Kısa video dağıtımı için clipping partneriniz", titleA: "Tek kaynak.", titleB: "Görünmek için birçok fırsat.", text: "Reklamatic; podcast, röportaj, kurucu içeriği ve kampanya çekimlerini net onaylar, hak kontrolleri ve öğrenme döngüsüyle platforma doğal kliplere dönüştürür.", primary: "Clipping planımı oluştur", secondary: "Süreci gör", pills: ["İnsan odaklı kreatif karar", "Marka güvenli onay", "TR + EN teslimat"], visualLabel: "Kaynak → an → platform", visualTitle: "Tekrarlanabilir clipping akışı", visualAlt: "Uzun içerikten dikey kliplere uzanan temsili Reklamatic clipping akışı", floating: ["AN HARİTASI", "00:01.2", "ÖĞRENME DÖNGÜSÜ"] },
    ticker: ["PODCAST", "KURUCU İÇERİĞİ", "EĞİTİM", "ÜRÜN HİKÂYESİ", "RÖPORTAJ", "CANLI YAYIN"],
    clipperRole: { kicker: "Clipper ne yapar?", title: "Clipper, kaynaktaki anlamı kısa video akışına taşır.", text: "Clipper yalnızca teknik operatör değildir. Onaylı brief sınırlarında editoryal karar, kısa video kurgusu ve güvenilir kalite kontrolünü birleştirir.", items: [
      ["01", "Anla ve seç", "Brief'i, hakları, kaynağı ve kitleyi inceler; yanıltıcı bağlama yol açmadan tek başına anlaşılabilen anları seçer."], ["02", "Açılışı kur ve uyarla", "Konuşmacının anlamını ve marka kurallarını koruyarak açılış, altyazı, tempo, kadraj ve platform varyantlarını hazırlar."], ["03", "Kalite kontrol ve teslim", "Dil, iddia, ses, görsel güvenlik ve teknik özellikleri kontrol eder; teslimi düzenler. Yayın yalnızca yazılı kapsam, erişim ve onay varsa yapılır."],
    ], note: "Reklamatic şu anda açık bir üretici ağı, otomatik iş pazaryeri veya performansa dayalı ödeme programı sunduğunu iddia etmez." },
    what: { kicker: "Clipping nedir?", title: "Clipping, otomatik kırpma düğmesi değil; editoryal stratejidir.", text: "Süreç bir anın neden önemli olduğunu anlamakla başlar, sonra o anı bağlamı olmayan bir izleyici için yeniden kurar. Güçlü klip; seçim, net açılış, tempo, altyazı, görsel kanıt ve platforma uygun kapanışı birleştirir.", cards: [
      ["01", "Anlam için seç", "Rastgele kısa parçalar yerine faydalı fikirleri, gerilimi, demoları, duyguyu ve tek başına çalışan hikâye akışlarını buluruz."],
      ["02", "Akış için yeniden kur", "Açılış, bağlam, altyazı, yeniden kadraj, tempo ve grafiklerle seçilen anı tamamlanmış kısa videoya dönüştürürüz."],
      ["03", "Sorumlu biçimde yinele", "Onaylı yayın verileri sonraki tema ve formatları yönlendirebilir. Sinyal yeni testi besler; erişimi garanti etmez."],
    ]},
    process: { kicker: "Nasıl çalışır?", title: "Kaynak dosyadan öğrenme döngüsüne dört kontrollü adım.", steps: [
      ["01", "Brief ve haklar", "Kitle, amaç, platformlar, kaynak sahipliği, marka kuralları, yasaklı iddialar ve onay sahiplerini netleştiririz."],
      ["02", "An haritası", "Kaynağı inceler; üretim hacmi kesinleşmeden önce anları, açıları ve açılış yönlerini öneririz."],
      ["03", "Kurgu ve onay", "Altyazı ve bağlamla platforma doğal versiyonlar hazırlarız. Mutabık kalınan onay olmadan markalı içerik yayınlanmaz."],
      ["04", "Teslim ve öğrenme", "Dosyaları düzenli teslim eder veya sadece kapsama dahilse yayınlarız. Sinyalleri inceleyip sonraki kreatif hipotezi yazarız."],
    ]},
    useCases: { kicker: "Uygun kaynak içerikler", title: "İçinde uzmanlık, kanıt veya hikâye olan içerikle başlayın.", items: [
      ["Podcast ve röportaj", "Her bölümdeki görüş, pratik ders, hikâye ve konuk anlarını çıkarın."], ["Kurucu ve uzman içeriği", "Konuşma, webinar, soru-cevap ve kamera önü kayıtlardan tanınabilir bir bakış açısı kurun."], ["Ürün ve marka çekimleri", "Demo, müşteri sorusu, kamera arkası ve kampanya görüntülerini yeniden çerçeveleyin."], ["Eğitim ve topluluk", "Ders, canlı yayın ve üye konuşmalarını keşfedilebilir, bağlamlı kliplere dönüştürün."],
    ]},
    services: { kicker: "Marka kampanyaları", title: "Ekibinizde eksik olan operasyon katmanını seçin.", intro: "Onaylı kaynak içeriği olan markalar, üreticiler, podcast ekipleri, eğitim şirketleri ve ürün ekipleri için. Girdiler, çıktılar, onaylar, yayın sorumluluğu ve ölçüm üretimden önce netleştirilir.", overview: [
      ["Sizden gereken", "Kaynak erişimi, haklar, kitle, hedef, marka kuralları ve bir onay sahibi"], ["Bizim kapsamımız", "Seçim, kreatif yön, platform versiyonları, revizyon ve teslim"], ["Yayın", "Yazılı erişim ve sorumluluk kabul edilmedikçe müşteriye aittir"], ["Başarı sinyalleri", "Erişilebilen izlenme, izleme davranışı, etkileşim ve atfedilebilir aksiyonlar; garanti değildir"],
    ], tabs: [
      { label: "Klip stratejisi", title: "Neyi neden keseceğinizi bilin", desc: "Düzenli üretimden önce kaynak denetimi, kitle çerçevesi, içerik sütunları, açılış yönleri ve uygulanabilir clipping yol haritası.", facts: [["Kimler için", "Yeni clipping programları"], ["Çıktı", "An ve format planı"], ["Karar", "Net kapsamla devam"]] },
      { label: "Sürekli clipping", title: "Düzenli çalışan dış clipping masası", desc: "Aktif ekipler için kaynak inceleme, seçim, kurgu, altyazı, platform uyarlaması ve düzenli değerlendirme ritmi.", facts: [["Kimler için", "Sürekli uzun içerik akışı"], ["Düzen", "Mutabık kalınan partiler"], ["Kontrol", "Yayın öncesi müşteri onayı"]] },
      { label: "Kampanya sprinti", title: "Tek bir ana odaklı üretim", desc: "Lansman, etkinlik, sezon, ürün hikâyesi veya yüksek değerli kayıt için başlangıcı ve bitişi tanımlı proje.", facts: [["Kimler için", "Zaman duyarlı kampanyalar"], ["Girdi", "Onaylı kampanya kaynakları"], ["Çıktı", "Yazılı teslim takvimi"]] },
      { label: "Dağıtım desteği", title: "Planlama ve yayın desteği ekleyin", desc: "Erişim, sorumluluk ve onaylar açıkça kabul edildiğinde kanal planı, takvim ve değerlendirme eklenebilir.", facts: [["Kimler için", "Operasyon arayan ekipler"], ["Erişim", "Gereken en düşük yetki"], ["Raporlama", "Bağlam içindeki platform verisi"]] },
    ], ask: "Özel kapsam iste", note: "Garantili viral olma, garantili görüntülenme veya açıklanmamış otomatik yayın sistemi satmıyoruz." },
    becomeClipper: { kicker: "Clipper ol", title: "Gelecekteki olası iş birlikleri için yeteneğinizi paylaşın.", text: "Editörlerden ilgi ve portfolyo topluyoruz; anında üyelik portalı veya canlı iş panosu işletmiyoruz.", items: [["Herkese açık portfolyo", "Giriş, parola veya özel dosya talebi olmadan inceleyebileceğimiz işleri paylaşın."], ["Uzmanlıklar", "En güçlü format, platform, dil, altyazı ve hareketli grafik becerilerinizi yazın."], ["Çalışma biçimi", "Uygunluk, iletişim yaklaşımı, teslim tercihleri ve kalite kontrol alışkanlıklarınızı belirtin."], ["Dürüst durum", "Gönderim sizi ilgi havuzuna ekler; onboarding, görev, ücret oranı veya kazanç garantisi vermez."]], cta: "Clipper ilgi formunu aç", note: "Gizli müşteri dosyaları veya paylaşma yetkiniz olmayan listelenmemiş materyaller göndermeyin." },
    measurement: { kicker: "Ölçüm", title: "Erişilebilen platform sinyallerini sonraki kreatif karara dönüştürün.", text: "Raporlama, mutabık kalınan hesap ve platformlarda erişilebilen analitikleri kullanır. Metrik tanımları, erişim, rapor dönemi ve kampanya kapsamı lansmandan önce yazılır; organik erişim ve dönüşüm garanti edilmez.", pillars: [
      ["Görüntülenme / erişim", "Maruz kalma göstergeleridir; görüntülenme her zaman tekil kişi değildir."], ["İzleme davranışı", "Platform sağlıyorsa izlenme süresi, açılışta izleyici tutma ve tamamlama."], ["Etkileşim", "Beğeni, yorum, kaydetme ve paylaşım; format ve kitle bağlamında yorumlanır."], ["Aksiyon", "Sadece izlenebilir bağlantı veya harekete geçirici mesaj kurulumu varsa tıklama ve dönüşüm; atıf sınırlıdır."],
    ], headers: ["Sinyal", "Ne anlatabilir?", "Neyi kanıtlamaz?"], rows: [
      ["Açılışta izleyici tutma", "İlk saniyelerin dikkati tutup tutmadığını", "Her izleyicinin neden kaldığını veya çıktığını"], ["Tamamlama", "Klibin ne sıklıkta sonuna kadar izlendiğini", "Yeni bir gönderinin gelecekteki performansını"], ["Kaydetme ve paylaşma", "Olası fayda veya yankıyı", "Tek başına ciroyu veya marka etkisini"], ["Tıklama / dönüşüm", "Seçilen kurulumdaki atfedilen aksiyonu", "Cihazlar ve kanallar arasındaki tüm etkiyi"],
    ], note: "Geçmişte yönetilen hesap ekranları gösterilse bile müşteri kampanya raporu değildir. Platformlar arası sayılar tekil kişi değildir, atıf sınırlıdır ve performans değişir." },
    brandSafety: { kicker: "Marka güvenliği", title: "Her klip açık sınırlar ve insan kalite kontrolünden geçer.", text: "Hiçbir iş akışı mutlak güvenlik vaat edemez. Üretimden önce hakları, iddiaları, erişimi ve müdahale yolunu tanımlayarak kaçınılabilir riski azaltırız.", items: [
      ["Haklar ve kaynak onayı", "Yalnızca müşteriye ait, lisanslı veya açıkça yetkilendirilmiş görüntü, müzik, logo ve materyal kullanılır."], ["Marka kuralları ve açıklamalar", "İzinli-yasaklı konu, dil, görsel, iddia; reklam/iş birliği açıklamaları ve platform kuralları yazılır."], ["İnsan kontrolü ve müşteri onayı", "Bağlam, altyazı, iddia, ses, teknik özellik ve marka uyumu kontrol edilir; teslim veya yayın öncesi mutabık müşteri onayı alınır."], ["Müdahale ve dürüstlük", "Uygunsuz içerik reddedilir, düzeltme/kaldırma iletişimi tanımlanır; şüpheli veya geçersiz trafik performans gibi sunulmaz, incelenir."],
    ], note: "Yazılı sözleşme farklı sorumluluk atamadıkça yasal iddiaları ve kaynak haklarını doğrulama sorumluluğu müşteridedir." },
    scenarios: { kicker: "Temsilî kampanya örnekleri", title: "Vaka çalışması sanmadan bir planın biçimini görün.", text: "Bunlar kurgusal planlama örnekleridir; Reklamatic müşteri sonucu değildir. Gerçek marka, yorum, takvim, bütçe, erişim iddiası veya sonuç metriği içermez.", label: "TEMSİLÎ KAMPANYA ÖRNEĞİ", source: "Kaynak", goal: "Hedef", outputs: "Olası çıktılar", signals: "İncelenecek sinyaller", items: [
      { alt: "Kurgusal Nova Audio podcast clipping planı için soyut illüstrasyon", title: "NOVA AUDIO — haftalık uzman podcasti", source: "Onaylı uzun bölüm ve transkript", goal: "Faydalı fikirleri bölüm bağlamı olmadan anlaşılır kılmak", outputs: "An haritası, açılış seçenekleri, altyazılı dikey kurgular ve onay formu", signals: "Açılışta izleyici tutma, tamamlama, kaydetme ve nitel yorumlar" },
      { alt: "Kurgusal Vela App lansman clipping planı için soyut illüstrasyon", title: "VELA APP — ürün lansman sprinti", source: "Kurucu anlatımı, ürün demosu ve onaylı iddialar", goal: "Ürünü farklı kitle soruları üzerinden anlatmak", outputs: "Seçili platformlar için demo, itiraz ve kurucu hikâyesi varyantları", signals: "İzleme davranışı, izlenebiliyorsa tıklama ve dönüşüm atfının sınırları" },
      { alt: "Kurgusal Northstar Academy kampanyası için soyut illüstrasyon", title: "NORTHSTAR ACADEMY — kurucu odaklı eğitim", source: "Webinar, soru-cevap ve kamera önü dersler", goal: "Tutarlı bir uzman bakış açısı kurmak", outputs: "Konu kümeleri, tek başına anlaşılır dersler, platform versiyonları ve öğrenme notları", signals: "Tamamlama, kaydetme, paylaşma ve tekrar eden konu tepkisi" },
    ], note: "Yalnızca temsilidir. Net hacim, süre, kanallar, izinler, ölçüm ve ticari koşullar gerçek yazılı kapsama göre belirlenir." },
    compare: { kicker: "Üret veya satın al kararı", title: "Kurgu çevresindeki sisteme ihtiyaç duyduğunuzda clipping partneri seçin.", headers: ["Yetkinlik", "Reklamatic", "Temel kurgu", "Ekip içi"], rows: [["An seçimi", "Stratejik kaynak inceleme", "Genellikle verilen zaman kodları", "Ekibe bağlı"], ["Platform versiyonları", "Kanal bazında kapsam", "Genellikle tek ana video", "Manuel"], ["Onay tasarımı", "İş akışında tanımlı", "Genellikle ayrı", "Ekip sahiplenir"], ["Öğrenme notları", "Üretim düzenine eklenebilir", "Genellikle ayrı", "Sürdürülmesi gerekir"]], disclaimer: "Düşük hacimli ve net yönlendirilmiş işlerde freelance editör veya iç süreç daha doğru olabilir. Reklamatic, tekrarlanabilir bir dış operasyon katmanı isteyen ekiplere uygundur." },
    resources: { kicker: "Clipping kaynakları", title: "İlk kurgudan önce üç pratik araç.", text: "Her kontrol listesini sayfa içinde açın; eksik indirme veya blog bağlantısı yoktur.", open: "Kontrol listesini aç", items: [
      ["KAYNAK", "Kaynak hazırlık listesi", "İnceleme öncesi materyalin güvenli ve kullanılabilir olduğunu doğrulayın.", ["Sahiplik veya lisans doğrulandı", "Ses ve görüntü kalitesi kontrol edildi", "Özel bölümler ve kişisel veri kaldırıldı", "Onay sahibi belirlendi"]],
      ["KAMPANYA", "Kampanya brief kontrol listesi", "Editöre belirsiz istek değil, karar almaya hazır brief verin.", ["Hedef kitle ve iş amacı", "Platformlar ve marka dili", "İzinli-yasaklı iddialar", "Yayın sahibi ve değerlendirme zamanı"]],
      ["ÖLÇÜM", "Ölçüm terimleri sözlüğü", "Raporlamadan önce her sinyalin ne anlama geldiğinde anlaşın.", ["Görüntülenme her zaman tekil kişi değildir", "İzleyici tutma ve tamamlama farklıdır", "Etkileşim bağlam gerektirir", "Tıklama/dönüşüm izleme ve sınırlı atıf gerektirir"]],
    ]},
    faq: { kicker: "Sık sorulanlar", title: "Kaynak dosyayı göndermeden önce iş akışını bilin.", items: [
      ["Clipping nedir?", "Uzun materyaldeki seçili anları belirli platformlar için tasarlanmış, tek başına anlamlı kısa videolara dönüştüren editoryal ve prodüksiyon sürecidir."], ["Bu yalnızca yapay zekâ ile otomatik klip çıkarma mı?", "Hayır. Araçlar transkripsiyon veya prodüksiyona yardımcı olabilir; editoryal seçim, bağlam, marka uyumu ve onay insan kararı gerektirir."], ["Hangi kaynaklar uygundur?", "Hak ve kalite uygun olduğunda podcast, röportaj, webinar, ders, canlı yayın, kurucu kaydı, ürün videosu ve kampanya çekimi kullanılabilir."], ["Kaç klip alırım?", "Adet; kaynak kalitesi, süre, platform ve kreatif derinliğe bağlıdır. Teklifiniz net teslimatları işe başlamadan belirtir."], ["Bizim için yayın yapar mısınız?", "Yayın desteği kapsama eklenebilir. Hesap erişimi, onay, takvim sorumluluğu ve raporlama sınırları yazılı kabul edilir."], ["Görüntülenme veya viral olma garantisi var mı?", "Hayır. Organik erişimi platformlar ve izleyiciler belirler. Yalnızca imzalı kapsamdaki iş ve süreci garanti ederiz."], ["Son kliplerin sahibi kim olur?", "Kullanım ve sahiplik koşulları; üçüncü taraf görüntü, font, müzik veya lisans sınırları dahil teklif ya da sözleşmede netleşir."], ["Revizyonlar nasıl işler?", "Revizyon turu, geri bildirim biçimi ve onay sahipleri üretimden önce tanımlanır."], ["Clipper olarak başvurabilir miyim?", "Evet, clipper ilgi formundan herkese açık portfolyo ve uzmanlığınızı paylaşabilirsiniz. Bu otomatik kayıt değildir ve ücretli iş garantisi vermez."],
    ]},
    contact: { kicker: "İki brief, tek net sonraki adım", title: "Marka planı başlatın veya clipper yeteneğinizi paylaşın.", text: "Yolunuzu seçin. Form kendi e-posta uygulamanızda düzenli bir e-posta hazırlar; dosya yüklemez, hesap açmaz veya yerleşim sözü vermez.", modeLabel: "İletişim yolunu seç", modes: { brand: "Marka / üretici brief'i", clipper: "Clipper ilgisi" }, labels: { name: "Adınız", email: "E-posta", phone: "Telefon / WhatsApp", company: "Şirket / kanal", market: "Ana pazar", platforms: "Hedef platformlar", platformsHint: "TikTok, Reels, Shorts", budget: "Tahmini aylık bütçe", source: "Kaynak içerik bağlantısı", service: "Hizmet ilgisi", portfolio: "Herkese açık portfolyo bağlantısı", specialty: "Ana uzmanlık", message: "Bu program ne başarmalı?", clipperMessage: "Kurgu stilinizi, dillerinizi ve uygunluğunuzu anlatın", consent: "Bu talep hakkında benimle iletişime geçilmesini kabul ediyor ve", privacy: "Gizlilik Politikasını", submit: "E-postamı hazırla", required: "Lütfen zorunlu alanları doldurun ve geçerli bir e-posta adresi yazın." }, safetyNote: "Özel link, parola, erişim token'ı, kişisel veri veya gizli müşteri materyali yapıştırmayın. Yalnızca herkese açık ve paylaşmaya yetkili olduğunuz URL kullanın.", services: ["Klip stratejisi", "Sürekli clipping", "Kampanya sprinti", "Dağıtım desteği"], specialties: ["Podcast / konuşan kişi", "Ürün / UGC", "Müzik / kültür", "Motion grafik", "Çok dilli kurgu", "Diğer"], markets: ["Türkiye", "Küresel", "Amerika Birleşik Devletleri", "Avrupa", "Diğer"], budgets: ["Henüz belirlenmedi", "€2.500 altı", "€2.500–€5.000", "€5.000–€15.000", "€15.000+"], direct: "Doğrudan görüşmeyi mi tercih edersiniz?" },
    footer: { line: "Türkiye'den global ekiplere clipping stratejisi, kısa video üretimi ve dağıtım desteği.", explore: "Keşfet", contact: "İletişim", legal: "Yasal", privacy: "Gizlilik", terms: "Koşullar", rights: "Tüm hakları saklıdır." },
  },
};
