const make = (key, type, enPath, trPath, en, tr, related = [], meta = {}) => ({ key, type, paths: { en: enPath, tr: trPath }, en, tr, related, ...meta });

export const seoPages = [
  make("about", "AboutPage", "about", "hakkimizda", {
    title: "About Reklamatic | Clipping Agency and Distribution Network", description: "See how Reklamatic turns a campaign form into short videos, active clipper distribution and eligible-view reporting.", kicker: "About Reklamatic", headline: "One clipping agency from campaign form to multi-account distribution.", lead: "Reklamatic turns content from brands, apps, artists, publishers, streamers and creators into platform-native short videos, then coordinates clipper matching, approval, publishing and reporting. Our publishing history includes millions of platform views.",
    highlights: [["Active network", "Clippers and suitable publishing accounts"], ["Proven distribution", "Millions of historical platform views"], ["Brand control", "Written conditions, content approval and measurement rules"]],
    sections: [["Why we exist", "Brands should not need to manage account outreach, campaign forms, production, approvals and publishing one by one. Reklamatic brings those responsibilities into one campaign operation."], ["How we work", "We define the audience, approved source, platform rules and measurement terms; prepare the short-video directions; coordinate brand approval; publish through suitable accounts in the active clipper network and report the agreed platform data."], ["What the contract controls", "Content, accounts, platforms, target geography, approval, measurement and commercial terms are written first. If the campaign includes an eligible-view target, its counting rules, exclusions and shortfall remedy are explicit; sales and virality are not guaranteed."]], cta: "Discuss a clipping campaign"
  }, {
    title: "Reklamatic Hakkında | İnsan Odaklı Clipping Operasyonu", description: "Reklamatic'in kısa video clipping sürecini insan kararı, açık onaylar ve dürüst ölçümle nasıl yürüttüğünü öğrenin.", kicker: "Reklamatic hakkında", headline: "Karar, açıklık ve kontrol etrafında kurulan clipping operasyonu.", lead: "Reklamatic, Türkçe ve İngilizce çalışan marka, içerik üreticisi ve medya ekipleri için Türkiye merkezli clipping partneridir. Onaylı uzun kaynakları kısa video sistemlerine dönüştürürken yazılımın, görüntülenmenin veya viral olmanın insan kararının yerini tuttuğunu iddia etmeyiz.",
    highlights: [["İnsan odaklı", "Editoryal karar ve kalite kontrol hesap verebilir kalır"], ["İki dilli", "Türkçe ve İngilizce üretim akışları"], ["Önce kapsam", "Haklar, çıktılar, onay ve erişim baştan yazılır"]],
    sections: [["Neden varız?", "Uzun içerik çoğu zaman değerli anlar barındırır; ancak ekiplerin bunları seçmek, yeniden kurmak ve dağıtmak için zamanı veya sistemi yoktur. Reklamatic, özgün anlamı koruyarak bu operasyon katmanını sağlar."], ["Nasıl çalışırız?", "Hedef kitle, kaynak hakları, marka kuralları ve içeriğin destekleyeceği kararla başlarız. Editörler tek başına anlaşılır klipler hazırlar, müşteri onaylar ve erişilebilen platform sinyalleri sonraki hipotezi yönlendirir."], ["Ne vaat etmeyiz?", "Garantili görüntülenme, viral sonuç, otomatik üretici dağıtımı veya her clipper adayına iş sözü vermeyiz. Teslimatlar, yayın sorumluluğu, raporlama ve ticari koşullar yazılı kapsamda belirlenir."]], cta: "Kampanya formunu görüş"
  }, ["agency", "brands", "contact"]),
  make("agency", "Service", "clipping-agency", "clipping-ajansi", {
    title: "Clipping Agency for Apps, Music and Publishers | Reklamatic", description: "Plan, produce, approve and distribute short-form campaigns through Reklamatic's managed clipper network.", kicker: "Clipping agency", headline: "More than editing: managed production and distribution around every clip.", lead: "Reklamatic turns an approved campaign form and source material into platform-ready clip directions, assigns suitable clippers from a managed network, coordinates brand approval and consolidates campaign reporting.",
    highlights: [["Inputs", "Approved source, audience, goals and brand rules"], ["Outputs", "Scoped clips, versions and organized delivery"], ["Control", "Client approval before publishing where agreed"]],
    sections: [["What the agency does", "We review approved material, create clip angles, prepare vertical variants, allocate suitable clippers and coordinate publishing after brand approval. Account, platform and reporting responsibilities are written into scope."], ["Who it fits", "The managed campaign model is designed for apps, music releases and publishers that need creative variation across suitable short-form accounts without managing each contributor separately."], ["How quality is governed", "Rights, prohibited topics, claims, visual rules, music, disclosures and approval owners are documented. Human quality control checks context, language, specifications and brand fit before a post is approved."]], cta: "Request an agency scope"
  }, {
    title: "Markalar ve Üreticiler için Clipping Ajansı | Reklamatic", description: "Podcast, röportaj ve marka çekimlerini platforma doğal kısa videolara dönüştüren insan odaklı clipping ajansı.", kicker: "Clipping ajansı", headline: "Kurgudan fazlası: her kısa klibin çevresindeki operasyon sistemi.", lead: "Reklamatic onaylı kampanya materyalini kısa videolara dönüştürür, yönetilen ağdan uygun clipper'ları atar, marka onayını ve yayın raporlamasını koordine eder.",
    highlights: [["Girdiler", "Onaylı kaynak, kitle, hedef ve marka kuralları"], ["Çıktılar", "Kapsamlı klipler, versiyonlar ve düzenli teslim"], ["Kontrol", "Mutabık yayın öncesi müşteri onayı"]],
    sections: [["Ajans ne yapar?", "Kaynağı inceler, an haritası çıkarır, açılışlar önerir, dikey izleme için kurgu yapar, erişilebilir altyazı ve platform varyantları hazırlarız. Yayın, yalnızca yetki ve sorumluluklar kapsamda yazılıysa dahildir."], ["Kimler için uygundur?", "Düzenli kaynağı fakat sınırlı iç kısa video kapasitesi olan podcast ekipleri, kurucular, eğitim şirketleri, ürün markaları ve ajanslar için uygundur. Düşük hacimli net işler için freelance editör daha doğru olabilir."], ["Kalite nasıl yönetilir?", "Haklar, yasaklı konular, iddialar, görsel kurallar, müzik, açıklamalar ve onay sahipleri belgelenir. İnsan kalite kontrolü teslimden önce bağlamı, dili, teknik özellikleri ve marka uyumunu inceler."]], cta: "Ajans kapsamı iste"
  }, ["campaigns", "pricing", "choose-agency"]),
  make("campaigns", "Service", "clipping-campaigns", "clipping-kampanyalari", {
    title: "How Clipping Campaigns Work | Reklamatic", description: "See how Reklamatic turns a brand form into approved short videos, active clipper distribution and eligible-view reporting.", kicker: "How it works", headline: "Submit the form. Let the clipper network produce and distribute. Report eligible views.", lead: "Reklamatic runs one agency process for brands, apps, artists, publishers and creators: define the audience and campaign terms, prepare platform-native short videos, approve them, distribute through suitable clipper accounts and report the agreed results.",
    highlights: [["1 · Form", "Objective, audience, budget, source and view rules"], ["2 · Distribution", "Production, approval and suitable clipper accounts"], ["3 · Report", "Verified posts and contract-defined eligible views"]],
    sections: [["1. Set the campaign", "The brand shares what it wants to promote, the Türkiye audience it wants to reach, its budget, approved material, platform priorities and prohibited claims. Reklamatic turns this into a written campaign scope."], ["2. Produce and publish", "Short-video directions and platform versions are prepared, reviewed and approved. Publishing is coordinated through suitable accounts in Reklamatic's active clipper network."], ["3. Measure the result", "The agreement states the eligible accounts, platforms, geography, counting window, exclusions and any shortfall remedy. The report shows verified posts and eligible views; it does not promise sales or virality."]], cta: "Start a campaign"
  }, {
    title: "Clipping Kampanyaları | Planlama, Üretim ve Onay", description: "Kaynak, çıktı, onay, yayın sorumluluğu ve ölçüm sınırları net bir kısa video clipping kampanyası planlayın.", kicker: "Clipping kampanyaları", headline: "Kampanya, viral olma sözü değil; kontrollü öğrenme planıdır.", lead: "Reklamatic clipping kampanyalarını onaylı kaynak içerik, tanımlı kitle ve iş sorusu etrafında kurar. Hacim, süre, platform, izin ve raporlama üretimden önce kabul edilir.",
    highlights: [["Kaynak", "Podcast, kurucu, ürün, eğitim veya etkinlik çekimi"], ["Plan", "Açılar, formatlar, onay ve teslim düzeni"], ["Sinyaller", "Erişilebilen izleme, etkileşim ve aksiyon verisi"]],
    sections: [["Kampanya girdileri", "Marka; kaynak hakları, kitle, amaç, platform öncelikleri, iddialar, görsel rehber, hariç tutulan konular ve onay sahibi sağlar. Özel link, token ve yetkisiz dosyalar site üzerinden paylaşılmamalıdır."], ["Olası kampanya kapsamı", "Yazılı kapsam; kaynak denetimi, an haritası, açılış yönleri, kurgulanmış klipler, platform versiyonları, altyazı dosyaları, revizyon ve düzenli teslim içerebilir. Varsayılan adet veya süre iddiası yoktur."], ["Yayın ve ölçüm", "Hesap erişimi ve sorumluluğu açıkça atanmadıkça yayın müşteridedir. Raporlama erişilebilen platform analitiğini kullanır; görüntülenme her zaman tekil kişi değildir ve atıf sınırlıdır."]], cta: "Kampanya planla"
  }, ["brands", "cases", "strategy"]),
  make("pricing", "WebPage", "pricing", "fiyatlandirma", {
    title: "Clipping Agency Pricing | How Reklamatic Scopes Work", description: "Understand the variables behind clipping agency pricing, deliverables and written commercial scope without invented package promises.", kicker: "Pricing", headline: "Price follows the real production load—not a vague clip count.", lead: "Reklamatic does not publish a universal price because source complexity, editorial depth, platform variants, approvals and publishing responsibility change the work. A written proposal shows the exact scope and commercial terms.",
    highlights: [["Source load", "Length, quality, languages and review complexity"], ["Creative depth", "Selection, hooks, graphics and platform versions"], ["Operations", "Revisions, access, publishing and reporting"]],
    sections: [["What affects price", "Key variables include source load, creative depth, clip volume, assigned clipper and account scope, platforms, review rounds, campaign window and reporting requirements."], ["What a proposal should state", "A useful proposal names deliverables, account criteria, included revisions, approval timing, publishing responsibility, reporting period, usage terms and exclusions. Ask questions when any item is unclear."], ["How view targets are priced", "A campaign may include a contract-defined eligible-view target. The proposal must state the measurement source, eligible accounts, reporting window, exclusions and shortfall remedy; conversion, sales and virality remain outside that guarantee."]], cta: "Request a written estimate"
  }, {
    title: "Clipping Ajansı Fiyatlandırması | Reklamatic Kapsamı", description: "Clipping kampanyası fiyatını, teslimatları, clipper dağıtımını ve sözleşmede tanımlanan görüntülenme hedefini belirleyen unsurları öğrenin.", kicker: "Fiyatlandırma", headline: "Bütçe; üretim, dağıtım ve görüntülenme hedefinin kapsamına göre belirlenir.", lead: "Kaynağın durumu, üretilecek formatlar, atanacak clipper ve hesap yapısı, kampanya süresi, onay süreci ve uygun görüntülenme hedefi fiyatı birlikte belirler. Teklif bütün koşulları yazılı olarak gösterir.",
    highlights: [["Kaynak yükü", "Süre, kalite, diller ve inceleme karmaşıklığı"], ["Kreatif derinlik", "Seçim, açılış, grafik ve platform versiyonları"], ["Operasyon", "Revizyon, erişim, yayın ve raporlama"]],
    sections: [["Fiyatı ne etkiler?", "Kaynak yükü, kreatif derinlik, klip adedi, atanacak clipper ve hesap kapsamı, platformlar, revizyon turu, kampanya dönemi ve raporlama ihtiyacı temel değişkenlerdir."], ["Teklif ne söylemeli?", "Teklif teslimatları, hesap kriterlerini, dahil revizyonları, onay zamanını, yayın sorumluluğunu, rapor dönemini, kullanım koşullarını ve hariçleri açıkça yazar."], ["Görüntülenme hedefi nasıl fiyatlanır?", "Kampanya sözleşmede tanımlanan uygun görüntülenme hedefini içerebilir. Ölçüm kaynağı, uygun hesaplar, rapor dönemi, hariç trafik ve eksik kalma telafisi teklifte yer alır; dönüşüm, satış ve viral sonuç bu garantinin dışındadır."]], cta: "Yazılı teklif iste"
  }, ["agency", "campaigns", "contact"]),
  make("cases", "CollectionPage", "case-studies", "ornek-kampanyalar", {
    title: "Clipping Campaign Examples | Reklamatic", description: "Explore app, music and publisher campaign plans with source, clipper direction, distribution and reporting details.", kicker: "Campaign examples", headline: "Campaign plans for apps, music releases and publishers.", lead: "Compare three practical campaign blueprints: what the brand supplies, what clippers produce, where publishing happens and what the final report contains.",
    highlights: [["App launch", "Demos, objections and use-case clips"], ["Music release", "Performance moments and artist stories"], ["Publisher", "Stream and episode moments with preserved context"]],
    sections: [["App campaign", "Source: approved product footage, screen recordings and claims. Clipper direction: demonstrations, comparisons and problem-solution formats. Reporting: eligible views, watch signals and tracked clicks when included in scope."], ["Music release campaign", "Source: cleared music, performance, rehearsal and artist-approved archive. Clipper direction: performance, release-moment and story formats. Reporting: eligible views and platform engagement in the agreed campaign period."], ["Publisher campaign", "Source: approved episodes, stream moments, transcripts and editorial limits. Clipper direction: reaction, argument and story formats. Reporting: eligible views, watch behavior and link actions when available."]], cta: "Build a campaign scope"
  }, {
    title: "Clipping Kampanya Örnekleri | Reklamatic", description: "Uygulama, müzik ve yayıncı kampanyalarını kaynak, clipper yönü, dağıtım ve raporlama ayrıntılarıyla inceleyin.", kicker: "Kampanya örnekleri", headline: "Uygulama, müzik ve yayıncılar için kampanya planları.", lead: "Üç uygulanabilir kampanya planını karşılaştırın: markanın sağlayacağı kaynak, clipper üretimi, yayın modeli ve sonuç raporunun içeriği.",
    highlights: [["Uygulama lansmanı", "Demo, itiraz ve kullanım klipleri"], ["Müzik yayını", "Performans anları ve sanatçı hikâyeleri"], ["Yayıncı", "Bağlamı korunan yayın ve bölüm kesitleri"]],
    sections: [["Uygulama kampanyası", "Kaynak: onaylı ürün görüntüsü, ekran kaydı ve iddialar. Clipper yönü: demo, karşılaştırma ve sorun-çözüm formatları. Rapor: kapsama göre uygun görüntülenme, izleme sinyali ve takipli tıklama."], ["Müzik yayını kampanyası", "Kaynak: hakları temizlenmiş müzik, performans, prova ve sanatçı onaylı arşiv. Clipper yönü: performans, yayın anı ve hikâye formatları. Rapor: mutabık kampanya dönemindeki uygun görüntülenme ve platform etkileşimi."], ["Yayıncı kampanyası", "Kaynak: onaylı bölümler, yayın anları, transkript ve editoryal sınırlar. Clipper yönü: tepki, argüman ve hikâye formatları. Rapor: uygun görüntülenme, izleme davranışı ve varsa bağlantı aksiyonu."]], cta: "Kampanya kapsamı oluştur"
  }, ["campaigns", "brands", "contact"]),
  make("faq", "FAQPage", "faq", "sss", {
    title: "Clipping FAQ | Brands, Campaigns, Rights and Clippers", description: "Answers about clipping, campaign scope, brand safety, measurement, publishing, rights and clipper interest.", kicker: "Frequently asked questions", headline: "Clear answers before a source file changes hands.", lead: "These answers describe Reklamatic's current service boundaries. Your written proposal and agreement control the final deliverables, ownership, access and commercial terms.",
    faq: [["What is clipping?", "Clipping turns approved source material and written campaign conditions into a self-contained short video and distributes it through a suitable social account."], ["Who is a clipper?", "A clipper prepares or adapts the short video, follows the campaign rules and publishes it through an eligible account."], ["How can a clipper earn?", "A campaign can state a rate for each 1,000 eligible and verified views. The rate and counting rules are shown before work; applying does not guarantee assignments or earnings."], ["What does the clipper extension do?", "It supports content variants, campaign queues, authorized multi-account management and publishing workflows. Platform permissions and limits still apply."], ["Do I need a monetized channel?", "Not for campaign-based payments. Each Reklamatic campaign defines its own valid-view and payment conditions; platform monetization is a separate matter."], ["Do you help with company setup?", "Yes. Optional sole proprietorship setup support is a separate one-time paid service. It does not require campaign participation or the automation package; a licensed accountant confirms the suitable tax route."], ["What does a brand buy?", "The written scope can include content production, account allocation, approval, publishing coordination, post verification, reporting and a contract-defined eligible-view target."], ["Do you guarantee views?", "Some campaigns include a written eligible-view guarantee. The contract defines the target, accounts, platforms, geography, measurement source, window, exclusions and shortfall remedy; it never guarantees sales or virality."], ["Does Reklamatic have a distribution network?", "Yes. Reklamatic coordinates production, publishing and reporting through an active clipper network supported by an AI-assisted internal operations system."]],
    sections: [["Campaign scope", "Volume, timing, platforms, revisions and reporting depend on source and requirements. They are written before work begins."], ["Safety and privacy", "Do not send passwords, access tokens, private links or unauthorized material. Brand rules and prohibited topics are documented during scoping."], ["Measurement", "Available views, watch behavior, engagement, clicks and conversions may be reviewed. Views are not always unique people and attribution is limited."]], cta: "Ask a specific question"
  }, {
    title: "Clipping SSS | Marka, Kampanya, Haklar ve Clipper", description: "Clipping, kampanya kapsamı, marka güvenliği, ölçüm, yayın, haklar ve clipper ilgisi hakkında yanıtlar.", kicker: "Sık sorulan sorular", headline: "Kaynak dosya el değiştirmeden önce net yanıtlar.", lead: "Yanıtlar Reklamatic'in mevcut hizmet sınırlarını açıklar. Net teslimat, sahiplik, erişim ve ticari koşullarda yazılı teklif ve sözleşme geçerlidir.",
    faq: [["Clipping nedir?", "Clipping, onaylı kampanya materyalini uygun hesaplarda yayımlanacak kısa videolara dönüştürür."], ["Otomatik yapay zekâ clipping mi?", "Araçlar üretime yardımcı olabilir; seçim, bağlam, clipper eşleşmesi, marka uyumu ve kalite onayı insan sorumluluğunda kalır."], ["Görüntülenme garantisi var mı?", "Bazı kampanyalarda sözleşme uygun view hedefini, ölçüm kaynağını, hesapları, dönemi, hariçleri ve eksik kalma telafisini tanımlar. Satış, kâr ve viral sonuç garanti edilmez."], ["Reklamatic bizim için yayın yapabilir mi?", "Atanmış clipper hesaplarında yayın; sorumluluklar, izinler ve marka onayı yazılı olarak kabul edildiğinde koordine edilir."], ["Kaynak haklarını kim doğrular?", "Yazılı sözleşme başka sorumluluk atamadıkça müşteri doğrular."], ["Clipper olarak başvurabilir miyim?", "Herkese açık portfolyo ve uzmanlık paylaşabilirsiniz. İlgi formu onboarding, görev veya kazanç garantisi değildir."]],
    sections: [["Kampanya kapsamı", "Hacim, süre, platform, revizyon ve raporlama kaynak ve gereksinime bağlıdır. İş başlamadan yazılır."], ["Güvenlik ve gizlilik", "Parola, erişim token'ı, özel link veya yetkisiz materyal göndermeyin. Marka kuralları ve yasaklı konular kapsam sırasında belgelenir."], ["Ölçüm", "Erişilebilen görüntülenme, izleme davranışı, etkileşim, tıklama ve dönüşüm incelenebilir. Görüntülenme her zaman tekil kişi değildir, atıf sınırlıdır."]], cta: "Belirli bir soru sor"
  }, ["agency", "pricing", "contact"]),
  make("blog", "CollectionPage", "blog", "blog", {
    title: "Clipping Resources and Guides | Reklamatic Blog", description: "Practical guides to clipping strategy, UGC, content repurposing, agency selection and short-form planning.", kicker: "Resource library", headline: "Define better campaign conditions before you buy production.", lead: "The Reklamatic guide library explains the decisions behind useful short-form systems. Every guide is educational, contains no guaranteed outcome and links to the next relevant planning step.",
    highlights: [["Basics", "What clipping is and what it is not"], ["Strategy", "How sources, formats and signals connect"], ["Selection", "How to evaluate an agency and scope"]],
    sections: [["Start with the fundamentals", "Read What is Clipping and Content Repurposing to understand source readiness, self-contained meaning and the difference between copying and adapting."], ["Understand campaign economics", "The earnings and eligible-view guides show how written rates, measurement sources, exclusions and remedies should be defined before work begins."], ["Track platform change", "The platform update log connects official YouTube, Instagram and Facebook changes to practical clipping decisions instead of repeating generic trend claims."]], cta: "Browse the eight guides"
  }, {
    title: "Clipping Kaynakları ve Rehberleri | Reklamatic Blog", description: "Clipping stratejisi, UGC, içerik yeniden kullanımı, ajans seçimi ve kısa video planlaması için pratik rehberler.", kicker: "Kaynak kütüphanesi", headline: "Prodüksiyon satın almadan önce kampanya koşullarını netleştirin.", lead: "Reklamatic rehber kütüphanesi faydalı kısa video sistemlerinin arkasındaki kararları açıklar. Her rehber eğiticidir, sonuç garantisi içermez ve ilgili sonraki planlama adımına bağlanır.",
    highlights: [["Temeller", "Clipping nedir ve ne değildir?"], ["Strateji", "Kaynak, format ve sinyaller nasıl bağlanır?"], ["Seçim", "Ajans ve kapsam nasıl değerlendirilir?"]],
    sections: [["Temellerle başlayın", "Kaynak hazırlığı, tek başına anlam ve kopyalamayla uyarlama farkı için Clipping Nedir ve İçerik Yeniden Kullanımı rehberlerini okuyun."], ["Kampanya ekonomisini anlayın", "Kazanç ve uygun görüntülenme rehberleri; yazılı oran, ölçüm kaynağı, hariçler ve telafinin işe başlamadan nasıl tanımlanacağını gösterir."], ["Platform değişimini izleyin", "Platform günlüğü, resmi YouTube, Instagram ve Facebook değişikliklerini genel trend cümleleri yerine uygulanabilir clipping kararlarına bağlar."]], cta: "Sekiz rehberi incele"
  }, ["what-is-clipping", "platform-updates", "clipper-earnings", "view-guarantee", "strategy", "choose-agency"]),
  make("what-is-clipping", "Article", "blog/what-is-clipping", "blog/clipping-nedir", {
    title: "What Is Clipping? Brands, Clippers and Per-View Campaigns", description: "Learn what a clip and clipper are, how per-1,000 eligible-view campaigns work and why Türkiye-focused distribution matters.", kicker: "Clipping guide 01", headline: "Clipping combines short-video production with distribution.", lead: "A clip is a short, self-contained video made from approved source material and written campaign conditions. A clipper prepares it, follows the campaign rules and publishes it through an eligible social account.",
    highlights: [["Brand", "Funds clear conditions and a distribution target"], ["Clipper", "Creates or adapts and publishes"], ["Reklamatic", "Coordinates approval, accounts and reporting"]],
    sections: [["How it differs from editing", "Editing ends when the file is delivered. In a clipping campaign, the content is also distributed through agreed social accounts and the published result is measured under written rules."], ["How a clipper can earn", "A campaign may state a rate for each 1,000 eligible and verified views. The rate, eligible platforms and accounts, target geography, counting window, exclusions and payment terms are shown before work."], ["Why Türkiye-focused campaigns matter", "Some overseas campaigns require traffic from specific countries. Türkiye-based views may not qualify. Reklamatic builds local campaigns around the Türkiye audience, suitable accounts and the written measurement terms."]], cta: "Use the clipping model"
  }, {
    title: "Clipping Nedir? Pratik Kısa Video Rehberi", description: "Clipping'in onaylı uzun kaynakları nasıl tek başına anlaşılır, platforma doğal kısa videolara dönüştürdüğünü öğrenin.", kicker: "Clipping rehberi 01", headline: "Clipping nedir ve neden altyazı eklemekten fazlasıdır?", lead: "Clipping, uzun içeriğin içindeki anlamlı anı bulup belirli bir kitle ve platform için tamamlanmış kısa video olarak yeniden kuran editoryal ve prodüksiyon sürecidir.",
    highlights: [["Seç", "Tek başına değeri olan anı belirle"], ["Yeniden kur", "Açılış, bağlam, tempo ve altyazı ekle"], ["Uyarla", "Platform davranışı ve teknik özelliklere uy"]],
    sections: [["Clipping ve kırpma farkı", "Kırpma kadrajı değiştirir. Clipping iletişimi değiştirir. Klip, kaynağı hiç görmemiş kişi için yeterli bağlama sahip olmalı; konuşmacının anlamını korumalı ve yanıltıcı kurgudan kaçınmalıdır."], ["Uygun olabilecek kaynaklar", "Haklar, ses, görüntü kalitesi ve marka kuralları uygunsa podcast, röportaj, webinar, kurucu kaydı, ders, canlı yayın, ürün demosu ve kampanya çekimi kullanılabilir."], ["Faydalı klip ne içerir?", "Net açılış, tek ana fikir, kanıt veya hikâye hareketi, okunur altyazı, bilinçli tempo, platforma güvenli görseller ve düşünceyi tamamlayan ya da kabul edilen aksiyonu destekleyen kapanış arayın."]], cta: "Kaynağımı plana dönüştür"
  }, ["repurposing", "strategy", "podcast"]),
  make("clipping-vs-ugc", "Article", "blog/clipping-vs-ugc", "blog/clipping-ve-ugc", {
    title: "Clipping vs UGC | Which Short-Form Model Fits?", description: "Compare source-led clipping and UGC-style content by inputs, control, use cases and measurement.", kicker: "Clipping guide 02", headline: "Clipping and UGC solve different creative problems.", lead: "Clipping rebuilds approved existing source material. UGC-style content is usually created as a new, native-feeling asset around a product, experience or message. Neither format guarantees performance.",
    highlights: [["Clipping", "Starts with long-form or campaign source"], ["UGC", "Starts with a creator-style concept or demonstration"], ["Hybrid", "Uses both when rights and scope support it"]],
    sections: [["Choose clipping when", "Use clipping when valuable expertise, stories, interviews, demos or talks already exist and you want to distribute the strongest moments without producing every asset from scratch."], ["Choose UGC-style production when", "Use UGC-style creative when the concept needs a fresh product demonstration, testimonial-style structure, problem-solution narrative or creator perspective. Claims and disclosures still require approval."], ["Build a hybrid carefully", "A campaign might clip a founder interview while separately producing native demonstrations. Keep source rights, usage terms, disclosures, creator permissions and measurement distinct in the written scope."]], cta: "Choose my creative model"
  }, {
    title: "Clipping ve UGC | Hangi Kısa Video Modeli Uygun?", description: "Kaynak odaklı clipping ile UGC tarzı içeriği girdi, kontrol, kullanım alanı ve ölçüm açısından karşılaştırın.", kicker: "Clipping rehberi 02", headline: "Clipping ve UGC farklı kreatif sorunları çözer.", lead: "Clipping onaylı mevcut kaynağı yeniden kurar. UGC tarzı içerik genellikle ürün, deneyim veya mesaj çevresinde yeni ve platforma doğal hisseden materyal olarak üretilir. Hiçbiri performans garantisi vermez.",
    highlights: [["Clipping", "Uzun veya kampanya kaynağıyla başlar"], ["UGC", "Üretici tarzı konsept veya demoyla başlar"], ["Hibrit", "Hak ve kapsam destekliyorsa ikisini kullanır"]],
    sections: [["Clipping ne zaman seçilir?", "Değerli uzmanlık, hikâye, röportaj, demo veya konuşma zaten varsa ve her materyali sıfırdan üretmeden güçlü anları dağıtmak istiyorsanız clipping kullanın."], ["UGC tarzı üretim ne zaman seçilir?", "Yeni ürün demosu, yorum benzeri yapı, sorun-çözüm anlatısı veya üretici bakışı gerekiyorsa UGC tarzı kreatif kullanın. İddia ve açıklamalar yine onay gerektirir."], ["Hibrit modeli dikkatle kurun", "Kampanya kurucu röportajını kliplerken ayrı doğal demolar üretebilir. Kaynak hakkı, kullanım koşulu, açıklama, üretici izni ve ölçümü yazılı kapsamda ayırın."]], cta: "Kreatif modelimi seç"
  }, ["what-is-clipping", "campaigns", "brands"]),
  make("strategy", "Article", "blog/clipping-strategy", "blog/clipping-stratejisi", {
    title: "Clipping Strategy | From Source to Learning Loop", description: "Build a clipping strategy around audience, source rights, moment selection, platform variants, approval and measurement.", kicker: "Clipping guide 03", headline: "A clipping strategy connects every cut to a decision.", lead: "Strategy prevents a short-form program from becoming a pile of disconnected edits. It defines who the clip is for, what source is safe, which idea is being tested and what happens after delivery.",
    highlights: [["Audience", "One defined viewer and need"], ["Creative", "Moment, hook, proof and format"], ["Learning", "A signal tied to a future decision"]],
    sections: [["Map source to audience", "Inventory source quality, rights, recurring themes and usable moments. Match each content pillar to a specific audience question rather than publishing every excerpt."], ["Design controlled variation", "Test one meaningful difference at a time—opening, duration, framing, proof, caption structure or CTA—while keeping approvals and platform specifications visible."], ["Close the loop", "Document which available signal would change the next decision. Watch behavior may change an opening; saves may support a useful topic; clicks require tracking. No single metric proves total business impact."]], cta: "Build a clipping strategy"
  }, {
    title: "Clipping Stratejisi | Kaynaktan Öğrenme Döngüsüne", description: "Kitle, kaynak hakkı, an seçimi, platform varyantı, onay ve ölçüm etrafında clipping stratejisi kurun.", kicker: "Clipping rehberi 03", headline: "Clipping stratejisi her kurguyu bir karara bağlar.", lead: "Strateji, kısa video programının bağlantısız kurgu yığınına dönüşmesini önler. Klibin kimin için olduğunu, hangi kaynağın güvenli olduğunu, hangi fikrin test edildiğini ve teslim sonrası ne olacağını tanımlar.",
    highlights: [["Kitle", "Tanımlı tek izleyici ve ihtiyaç"], ["Kreatif", "An, açılış, kanıt ve format"], ["Öğrenme", "Gelecek karara bağlı sinyal"]],
    sections: [["Kaynağı kitleyle eşleştirin", "Kaynak kalitesi, haklar, tekrar eden temalar ve kullanılabilir anları envanterleyin. Her parçayı yayınlamak yerine içerik sütunlarını belirli kitle sorularıyla eşleştirin."], ["Kontrollü varyasyon tasarlayın", "Onayları ve platform özelliklerini görünür tutarak açılış, süre, kadraj, kanıt, altyazı yapısı veya harekete geçirici mesajdan birini anlamlı biçimde test edin."], ["Döngüyü kapatın", "Hangi erişilebilir sinyalin sonraki kararı değiştireceğini yazın. İzleme davranışı açılışı, kaydetme faydalı konuyu değiştirebilir; tıklama izleme gerektirir. Tek metrik tüm iş etkisini kanıtlamaz."]], cta: "Clipping stratejisi kur"
  }, ["campaigns", "measurement", "choose-agency"]),
  make("choose-agency", "Article", "blog/how-to-choose-a-clipping-agency", "blog/clipping-ajansi-secimi", {
    title: "How to Choose a Clipping Agency | Evaluation Checklist", description: "Evaluate a clipping agency by editorial process, rights, approvals, platform adaptation, measurement and honest claims.", kicker: "Clipping guide 04", headline: "Choose the process you can audit—not the loudest view claim.", lead: "A strong clipping partner should explain how moments are selected, who approves claims, what is included, who publishes and how reporting limitations are communicated.",
    highlights: [["Ask", "How are moments selected and checked?"], ["Verify", "What rights, access and approvals are required?"], ["Write", "What exactly is delivered, when and by whom?"]],
    sections: [["Evaluate editorial quality", "Ask for the selection logic, context checks, caption process, language review, platform variants and quality-control owner. A polished transition cannot repair a misleading edit."], ["Evaluate operating clarity", "The proposal should identify source responsibility, exclusions, revision rounds, approval timing, publishing access, file delivery, usage terms, reporting period and escalation contacts."], ["Challenge performance claims", "Avoid guaranteed virality, unexplained network reach, borrowed case studies and metrics without date, platform or account scope. Historical screenshots do not equal future client results."]], cta: "Evaluate Reklamatic against this list"
  }, {
    title: "Clipping Ajansı Nasıl Seçilir? | Değerlendirme Listesi", description: "Clipping ajansını editoryal süreç, haklar, onay, platform uyarlaması, ölçüm ve dürüst iddialarla değerlendirin.", kicker: "Clipping rehberi 04", headline: "En yüksek görüntülenme iddiasını değil, denetleyebileceğiniz süreci seçin.", lead: "Güçlü clipping partneri anların nasıl seçildiğini, iddiaları kimin onayladığını, neyin dahil olduğunu, kimin yayın yaptığını ve raporlama sınırlarının nasıl açıklandığını anlatmalıdır.",
    highlights: [["Sor", "Anlar nasıl seçiliyor ve kontrol ediliyor?"], ["Doğrula", "Hangi hak, erişim ve onay gerekiyor?"], ["Yaz", "Tam olarak ne, ne zaman, kim tarafından teslim ediliyor?"]],
    sections: [["Editoryal kaliteyi değerlendirin", "Seçim mantığı, bağlam kontrolü, altyazı süreci, dil incelemesi, platform varyantları ve kalite kontrol sahibini sorun. Parlak geçiş yanıltıcı kurguyu düzeltemez."], ["Operasyon açıklığını değerlendirin", "Teklif kaynak sorumluluğu, hariçler, revizyon, onay zamanı, yayın erişimi, dosya teslimi, kullanım koşulları, rapor dönemi ve müdahale iletişimini belirtmelidir."], ["Performans iddialarını sorgulayın", "Garantili viral sonuç, açıklanmayan ağ erişimi, ödünç vaka çalışmaları ve tarih-platform-hesap kapsamı olmayan metriklerden kaçının. Geçmiş ekranlar gelecek müşteri sonucuna eşit değildir."]], cta: "Reklamatic'i bu listeyle değerlendir"
  }, ["agency", "pricing", "faq"]),
  make("repurposing", "Article", "blog/content-repurposing", "blog/icerik-yeniden-kullanim", {
    title: "Content Repurposing for Short-Form | A Responsible System", description: "Repurpose long-form content into short clips without losing context, rights control or brand consistency.", kicker: "Clipping guide 05", headline: "Repurposing should create new usefulness—not duplicate noise.", lead: "Responsible repurposing selects the parts of a source that deserve a new format, then adds the context, pacing and presentation needed for a different audience environment.",
    highlights: [["Inventory", "Know what source exists and who owns it"], ["Transform", "Adapt meaning, format and presentation"], ["Govern", "Track approvals, versions and usage terms"]],
    sections: [["Prepare the source library", "Record ownership, license limits, speakers, languages, sensitive sections, audio quality, visual quality and approval status. Remove private data before sharing."], ["Create a transformation map", "Connect each useful moment to an audience question, platform, format and intended action. Avoid forcing every source into every channel."], ["Maintain the system", "Use naming, version control, caption files, approval records and learning notes so teams know what was published, what changed and what may be reused again."]], cta: "Audit my source library"
  }, {
    title: "Kısa Video için İçerik Yeniden Kullanımı | Sorumlu Sistem", description: "Bağlamı, hak kontrolünü veya marka tutarlılığını kaybetmeden uzun içeriği kısa kliplere dönüştürün.", kicker: "Clipping rehberi 05", headline: "Yeniden kullanım kopya gürültü değil, yeni fayda üretmelidir.", lead: "Sorumlu yeniden kullanım, kaynağın yeni formatı hak eden bölümlerini seçer; sonra farklı izleyici ortamı için gereken bağlam, tempo ve sunumu ekler.",
    highlights: [["Envanter", "Hangi kaynak var, sahibi kim?"], ["Dönüştür", "Anlamı, formatı ve sunumu uyarla"], ["Yönet", "Onay, versiyon ve kullanım koşullarını izle"]],
    sections: [["Kaynak kütüphanesini hazırlayın", "Sahiplik, lisans sınırı, konuşmacı, dil, hassas bölüm, ses-görüntü kalitesi ve onay durumunu kaydedin. Paylaşmadan önce özel veriyi kaldırın."], ["Dönüşüm haritası oluşturun", "Her faydalı anı kitle sorusu, platform, format ve hedeflenen aksiyonla bağlayın. Her kaynağı her kanala zorlamayın."], ["Sistemi sürdürün", "İsimlendirme, versiyon kontrolü, altyazı dosyası, onay kaydı ve öğrenme notu kullanın; ekip neyin yayınlandığını, değiştiğini ve tekrar kullanılabileceğini bilsin."]], cta: "Kaynak kütüphanemi denetle"
  }, ["what-is-clipping", "podcast", "strategy"]),
  make("platform-updates", "Article", "blog/short-form-platform-updates-2026", "blog/kisa-video-platform-guncellemeleri-2026", {
    title: "Short-Form Platform Updates 2026 | Clipping Operations", description: "A sourced update on YouTube Shorts, Instagram Reels and Facebook video changes that affect campaign conditions, measurement and delivery.", kicker: "Platform update 06", headline: "Platform changes alter what a clipping campaign must measure and deliver.", lead: "Short-form specifications are only one part of the job. Counting rules, discovery surfaces, disclosure controls and publishing formats also change, so 2026 campaign conditions should name the platform rule they depend on and the date it was checked.",
    highlights: [["YouTube", "Separate raw Shorts views from engaged views"], ["Instagram", "Use trial distribution as a test, not proof"], ["Facebook", "Plan for a Reels-first video publishing flow"]],
    sections: [["YouTube changed the meaning of a Shorts view", "Since 31 March 2025, a Shorts view counts when a Short starts or replays, with no minimum watch-time requirement. The former measure is called engaged views. A campaign should therefore state whether eligible delivery uses public views, engaged views, a platform export or another agreed source. Raw counts across YouTube, Instagram and TikTok are not interchangeable."], ["Longer Shorts add a rights check", "YouTube allows square or vertical Shorts up to three minutes, but a one-to-three-minute Short with an active third-party Content ID claim may be blocked globally. Music and publisher campaigns need a length-specific rights check before production, not after upload."], ["Instagram trial distribution is an experiment", "Trial Reels can show a Reel to non-followers first. That makes them useful for testing an angle before wider distribution, but the test is not a guaranteed reach product. Record which account, creative version, date and platform signal informed the next decision."], ["Facebook is simplifying video publishing", "Meta announced that new Facebook videos will be shared as Reels as the rollout reaches profiles and Pages. Campaign delivery should not rely on an old distinction between feed video and Reel without checking the current publishing interface and page eligibility."], ["Turn platform news into acceptance criteria", "For every deliverable write the aspect ratio, caption and safe-zone rule, disclosure requirement, account, publishing owner, measurement source and reporting window. Log the source URL and review date so a later platform change can be traced instead of silently changing campaign terms."]], cta: "Plan a current-platform campaign",
    sources: [["YouTube Help — Shorts view counting and creation", "https://support.google.com/youtube/answer/10059070"], ["YouTube Help — three-minute Shorts and Content ID", "https://support.google.com/youtube/answer/15424877"], ["Instagram — Trial Reels", "https://about.fb.com/news/2024/12/trial-reels-try-content-non-followers-first-see-what-perfoms-best/"], ["Meta — all Facebook videos moving to Reels", "https://about.fb.com/news/2025/06/making-it-easier-create-videos-facebook/"]]
  }, {
    title: "2026 Kısa Video Platform Güncellemeleri | Clipping Operasyonu", description: "YouTube Shorts, Instagram Reels ve Facebook video değişikliklerinin kampanya koşulları, ölçüm ve teslim üzerindeki etkilerini kaynaklarla inceleyin.", kicker: "Platform günlüğü 06", headline: "Platform değişiklikleri, clipping kampanyasının neyi ölçüp teslim edeceğini değiştirir.", lead: "Kısa video işi yalnız teknik ölçü değildir. Sayım kuralı, keşif alanı, reklam açıklaması ve yayın formatı da değişir. Bu nedenle 2026 kampanya koşulları dayandığı platform kuralını ve kontrol tarihini yazmalıdır.",
    highlights: [["YouTube", "Ham Shorts view ile engaged view'u ayır"], ["Instagram", "Trial dağıtımı test olarak kullan, kanıt sayma"], ["Facebook", "Reels öncelikli video akışına hazırlan"]],
    sections: [["YouTube, Shorts view tanımını değiştirdi", "31 Mart 2025'ten beri bir Short başladığında veya tekrar oynadığında, minimum izleme süresi aranmadan view sayılır. Eski ölçü engaged views adını aldı. Kampanya; uygun teslimde herkese açık view'u mu, engaged views'u mu, platform dışa aktarımını mı yoksa başka mutabık kaynağı mı kullandığını yazmalıdır. YouTube, Instagram ve TikTok ham sayıları eşdeğer değildir."], ["Daha uzun Shorts için hak kontrolü gerekir", "YouTube kare veya dikey Shorts videolarını üç dakikaya kadar destekler. Ancak aktif üçüncü taraf Content ID talebi bulunan bir ila üç dakikalık Short dünya genelinde engellenebilir. Müzik ve yayıncı kampanyalarında hak kontrolü yüklemeden sonra değil, prodüksiyondan önce süreye göre yapılmalıdır."], ["Instagram trial dağıtımı bir deneydir", "Trial Reels, içeriği önce takipçi olmayan kişilere gösterebilir. Bu özellik daha geniş dağıtımdan önce açıyı sınamak için kullanışlıdır; garanti edilen erişim ürünü değildir. Sonraki kararı etkileyen hesap, kreatif versiyon, tarih ve platform sinyali kayıt altına alınmalıdır."], ["Facebook video yayınını sadeleştiriyor", "Meta, dağıtım profillere ve sayfalara ulaştıkça yeni Facebook videolarının Reels olarak paylaşılacağını duyurdu. Kampanya teslimi, güncel yayın ekranı ve sayfa uygunluğu kontrol edilmeden eski feed video–Reel ayrımına dayanmamalıdır."], ["Platform haberini kabul kriterine dönüştürün", "Her teslim için oranı, altyazı ve güvenli alan kuralını, reklam açıklamasını, hesabı, yayın sahibini, ölçüm kaynağını ve rapor dönemini yazın. Kaynak bağlantısı ile kontrol tarihini kaydedin; sonraki platform değişikliği kampanya koşulunu sessizce değiştirmesin."]], cta: "Güncel platform kampanyası planla",
    sources: [["YouTube Yardım — Shorts görüntüleme sayımı", "https://support.google.com/youtube/answer/10059070"], ["YouTube Yardım — üç dakikalık Shorts ve Content ID", "https://support.google.com/youtube/answer/15424877"], ["Instagram — Trial Reels", "https://about.fb.com/news/2024/12/trial-reels-try-content-non-followers-first-see-what-perfoms-best/"], ["Meta — Facebook videolarının Reels'e geçişi", "https://about.fb.com/news/2025/06/making-it-easier-create-videos-facebook/"]]
  }, ["strategy", "tiktok", "reels", "view-guarantee"], { published: "2026-07-28", updated: "2026-07-28", readTime: { en: "7 min read", tr: "7 dk okuma" }, image: "/media/editorial/platform-updates.webp" }),
  make("clipper-earnings", "Article", "blog/how-clippers-earn", "blog/clipper-nasil-kazanir", {
    title: "How Clippers Earn | Rates, Eligible Views and Payment", description: "Understand fixed fees, per-1,000 eligible-view rates, eligibility rules and payment evidence in a managed clipping campaign.", kicker: "Clipper guide 07", headline: "A clipper earns by written campaign terms—not by a universal average.", lead: "There is no honest single answer to how much a clipper earns. Campaign category, fixed work, eligible account rules, verified views, rate, region, approval and payment schedule all change the result. The useful answer is a written formula with examples and exclusions.",
    highlights: [["Before work", "See the task, rate, eligibility and deadline"], ["During work", "Keep approvals and publishing evidence"], ["After work", "Settle from the agreed measurement source"]],
    sections: [["Common payment structures", "A campaign may use a written fixed fee for approved deliverables, a rate per 1,000 eligible verified views, a performance threshold, or a combination. No component should be implied if it is not in the assignment. A portfolio submission, network approval or campaign application is not a promise of work or income."], ["The calculation", "Campaign earnings equal the written fixed fee, if any, plus eligible verified views divided by 1,000 and multiplied by the written campaign rate, if any. Example: 80,000 eligible views at a stated rate of 2 currency units per 1,000 equals 160 units, before any clearly disclosed tax, platform or payment terms. The example explains arithmetic; it is not a Reklamatic rate quote."], ["What makes a view eligible", "The agreement should name the account, platform, post, campaign window, measurement source, geography when relevant, fraud and invalid-traffic rules, deletion rules and evidence deadline. Views outside that scope may be real platform activity but still outside the campaign settlement."], ["What the clipper must keep", "Keep the accepted campaign conditions, version approval, live post URL, publication time, account identity and the required analytics export or screenshot. Do not share passwords, session cookies, two-factor codes or private client files. Evidence should prove the delivery without exposing unrelated personal data."], ["When and how payment happens", "The assignment should state the verification date, dispute window, payment method, currency, invoice requirement and expected settlement timing. If any of those are missing, ask before publishing. A high headline rate without a clear eligibility definition can be less valuable than a lower rate with auditable rules."]], cta: "Apply with a public portfolio",
    sources: [["Whop — Content Rewards overview", "https://whop.com/blog/whop-content-rewards/"], ["FTC — disclosure guidance for social media", "https://www.ftc.gov/business-guidance/resources/disclosures-101-social-media-influencers"]]
  }, {
    title: "Clipper Nasıl Kazanır? | Oran, Uygun Görüntülenme ve Ödeme", description: "Yönetilen clipping kampanyasında sabit ücret, 1.000 uygun görüntülenme oranı, uygunluk kuralı ve ödeme kanıtını öğrenin.", kicker: "Clipper rehberi 07", headline: "Clipper evrensel ortalamaya göre değil, yazılı kampanya koşuluna göre kazanır.", lead: "Clipper ne kadar kazanır sorusunun dürüst tek bir rakamı yoktur. Kampanya kategorisi, sabit iş, hesap uygunluğu, doğrulanmış görüntülenme, oran, bölge, onay ve ödeme takvimi sonucu değiştirir. Yararlı yanıt, örnek ve hariçleri bulunan yazılı formüldür.",
    highlights: [["İşten önce", "Görevi, oranı, uygunluğu ve tarihi gör"], ["İş sırasında", "Onay ve yayın kanıtını sakla"], ["İşten sonra", "Mutabık ölçüm kaynağından hesaplaş"]],
    sections: [["Yaygın ödeme modelleri", "Kampanya; onaylı teslim için yazılı sabit ücret, 1.000 uygun doğrulanmış görüntülenme başına oran, performans eşiği veya bunların birleşimini kullanabilir. Görevde yazmayan hiçbir kalem varmış gibi anlatılmamalıdır. Portfolyo göndermek, ağa kabul edilmek veya kampanyaya başvurmak iş ya da gelir sözü değildir."], ["Hesaplama", "Kampanya kazancı; varsa yazılı sabit ücret ile uygun doğrulanmış görüntülenmenin 1.000'e bölünüp varsa yazılı kampanya oranıyla çarpılmasının toplamıdır. Örnek: 80.000 uygun görüntülenme ve 1.000 başına açıkça yazılmış 2 para birimi oranı, vergi ve ödeme koşullarından önce 160 birim eder. Bu yalnız matematiği açıklar; Reklamatic fiyat teklifi değildir."], ["Görüntülenmeyi uygun yapan nedir?", "Sözleşme hesabı, platformu, gönderiyi, kampanya dönemini, ölçüm kaynağını, gerekiyorsa coğrafyayı, geçersiz trafik kuralını, silinme koşulunu ve kanıt son tarihini yazmalıdır. Kapsam dışındaki görüntülenme gerçek platform etkinliği olsa bile kampanya ödemesine dahil olmayabilir."], ["Clipper hangi kanıtları saklar?", "Kabul edilen kampanya koşullarını, versiyon onayını, canlı gönderi bağlantısını, yayın zamanını, hesap kimliğini ve istenen analitik dışa aktarımını veya ekran görüntüsünü saklayın. Parola, oturum çerezi, iki aşamalı doğrulama kodu veya gizli müşteri dosyası paylaşmayın. Kanıt, ilgisiz kişisel veriyi açmadan teslimi doğrulamalıdır."], ["Ödeme ne zaman ve nasıl yapılır?", "Görev; doğrulama tarihini, itiraz süresini, ödeme yöntemini, para birimini, fatura gereksinimini ve beklenen ödeme zamanını belirtmelidir. Bunlardan biri eksikse yayınlamadan önce sorun. Uygunluk tanımı belirsiz yüksek oran, denetlenebilir düşük orandan daha değersiz olabilir."]], cta: "Herkese açık portfolyonla başvur",
    sources: [["Whop — Content Rewards genel bakış", "https://whop.com/blog/whop-content-rewards/"], ["FTC — sosyal medya reklam açıklaması rehberi", "https://www.ftc.gov/business-guidance/resources/disclosures-101-social-media-influencers"]]
  }, ["clippers", "view-guarantee", "faq"], { published: "2026-07-28", updated: "2026-07-28", readTime: { en: "6 min read", tr: "6 dk okuma" }, image: "/media/editorial/clipper-earnings.webp" }),
  make("view-guarantee", "Article", "blog/eligible-view-guarantee", "blog/uygun-goruntulenme-garantisi", {
    title: "Eligible-View Guarantee | Definition, Exclusions and Remedy", description: "Learn what a contract-defined eligible-view guarantee covers, how views are measured and what happens if the target is missed.", kicker: "Measurement guide 08", headline: "A view guarantee is a contract rule—not a promise that content will go viral.", lead: "A usable guarantee names exactly which views count, where the number comes from, when it is measured and what remedy applies if delivery is short. It does not turn views into a guarantee of unique people, sales, profit or brand lift.",
    highlights: [["Define", "Account, platform, post, metric and period"], ["Exclude", "Invalid traffic, deleted posts and out-of-scope delivery"], ["Remedy", "Write the shortfall response before launch"]],
    sections: [["Start with the target", "Write one numeric target and whether it applies across the whole campaign or per platform, account or post. Name the permitted accounts and content versions. A headline such as one million views is incomplete until the eligible population and measurement date are known."], ["Name the measurement source", "The contract should state whether the source is public post counts, native account analytics, an exported platform report or another agreed system. It should also specify the metric label. On YouTube, for example, public Shorts views and engaged views are different measures."], ["List exclusions before launch", "Typical exclusions can include invalid or manipulated traffic, paid media outside scope, views outside the campaign period or geography, unapproved posts, altered creatives, deleted posts and accounts that breach platform or campaign rules. Exclusions should be specific enough to audit, not a broad right to reject delivery later."], ["Write the reporting process", "Define the report window, evidence owner, data access, screenshot or export standard, discrepancy process and how unavailable platform data is handled. Cross-platform totals should preserve the underlying platform and metric instead of pretending every view has identical meaning."], ["Define the shortfall remedy", "The agreement should say what happens if eligible delivery is below target: an extension, approved replacement distribution, a proportional commercial remedy or another written action. The remedy must also state its limit and timing. The guarantee remains separate from sales, conversion, profit and viral outcomes."]], cta: "Define a measurable campaign",
    sources: [["YouTube Help — Shorts view definitions", "https://support.google.com/youtube/answer/10059070"], ["Google — video structured data", "https://developers.google.com/search/docs/appearance/structured-data/video"]]
  }, {
    title: "Uygun Görüntülenme Garantisi | Tanım, Hariçler ve Telafi", description: "Sözleşmede tanımlı uygun görüntülenme garantisinin neyi kapsadığını, nasıl ölçüldüğünü ve hedef eksik kalırsa ne olduğunu öğrenin.", kicker: "Ölçüm rehberi 08", headline: "Görüntülenme garantisi sözleşme kuralıdır; viral olma sözü değildir.", lead: "Kullanılabilir garanti; hangi görüntülenmenin sayıldığını, sayının nereden geldiğini, ne zaman ölçüldüğünü ve teslim eksik kalırsa hangi telafinin uygulanacağını yazar. Görüntülenmeyi tekil kişi, satış, kâr veya marka etkisi garantisine dönüştürmez.",
    highlights: [["Tanımla", "Hesap, platform, gönderi, metrik ve dönem"], ["Hariç tut", "Geçersiz trafik, silinen gönderi ve kapsam dışı teslim"], ["Telafi et", "Eksik kalma çözümünü yayından önce yaz"]],
    sections: [["Hedefle başlayın", "Tek bir sayısal hedef yazın ve bunun kampanya toplamına mı; platform, hesap veya gönderi bazına mı uygulandığını belirtin. İzinli hesapları ve içerik versiyonlarını adlandırın. Bir milyon görüntülenme gibi başlık, uygun kitle ve ölçüm tarihi bilinmeden eksiktir."], ["Ölçüm kaynağını adlandırın", "Sözleşme kaynağın herkese açık gönderi sayacı, yerel hesap analitiği, platform dışa aktarımı veya başka mutabık sistem olup olmadığını yazmalıdır. Metrik etiketi de belirtilmelidir. Örneğin YouTube'da herkese açık Shorts views ile engaged views farklı ölçülerdir."], ["Hariçleri yayından önce listeleyin", "Geçersiz veya manipüle trafik, kapsam dışı ücretli medya, dönem ya da coğrafya dışı görüntülenme, onaysız gönderi, değiştirilmiş kreatif, silinen gönderi ve platform veya kampanya kuralını ihlal eden hesaplar hariç tutulabilir. Hariçler sonradan teslimi keyfi reddedecek kadar geniş değil, denetlenebilir olmalıdır."], ["Raporlama sürecini yazın", "Rapor dönemini, kanıt sahibini, veri erişimini, ekran görüntüsü veya dışa aktarım standardını, uyuşmazlık sürecini ve platform verisi kullanılamazsa ne olacağını tanımlayın. Platformlar arası toplam, her görüntülenme aynı anlamdaymış gibi davranmak yerine temel platform ve metriği korumalıdır."], ["Eksik kalma telafisini tanımlayın", "Sözleşme uygun teslim hedefin altındaysa ne olacağını yazmalıdır: süre uzatımı, onaylı ek dağıtım, oransal ticari telafi veya başka yazılı işlem. Telafinin sınırı ve zamanı da belirtilmelidir. Garanti satış, dönüşüm, kâr ve viral sonuçtan ayrı kalır."]], cta: "Ölçülebilir kampanya tanımla",
    sources: [["YouTube Yardım — Shorts görüntüleme tanımları", "https://support.google.com/youtube/answer/10059070"], ["Google — video yapılandırılmış veri", "https://developers.google.com/search/docs/appearance/structured-data/video"]]
  }, ["campaigns", "pricing", "clipper-earnings", "faq"], { published: "2026-07-28", updated: "2026-07-28", readTime: { en: "6 min read", tr: "6 dk okuma" }, image: "/media/editorial/view-guarantee.webp" }),
  make("podcast", "Service", "services/podcast-clipping", "hizmetler/podcast-clipping", {
    title: "Podcast Clipping Service | Short-Form Episode System", description: "Turn approved podcast episodes into self-contained short clips with moment maps, captions, review and platform variants.", kicker: "Podcast clipping", headline: "Give every strong episode more than one chance to be discovered.", lead: "Podcast clipping finds opinions, stories, lessons and guest moments that can stand alone. Reklamatic rebuilds them for short-form while protecting context and approval.",
    highlights: [["Source", "Approved video or audio episode and transcript"], ["Creative", "Moment map, hooks, captions and reframing"], ["Delivery", "Scoped variants, review and organized files"]],
    sections: [["Moment selection", "We look for one clear idea, tension, practical value or story movement. A short excerpt is rejected when missing context could distort the guest or host."], ["Visual treatment", "Depending on source quality and scope, a clip may use speaker reframing, readable captions, supporting graphics, chapter context and platform-safe layouts."], ["Program design", "A recurring program defines episode intake, exclusions, approval owner, output rhythm, platforms and learning notes. Counts and turnaround are agreed after reviewing the real source."]], cta: "Plan podcast clipping"
  }, {
    title: "Podcast Clipping Hizmeti | Kısa Video Bölüm Sistemi", description: "Onaylı podcast bölümlerini an haritası, altyazı, onay ve platform varyantlarıyla tek başına anlaşılır kısa kliplere dönüştürün.", kicker: "Podcast clipping", headline: "Her güçlü bölüme keşfedilmek için birden fazla fırsat verin.", lead: "Podcast clipping tek başına anlaşılabilen görüş, hikâye, ders ve konuk anlarını bulur. Reklamatic bunları bağlamı ve onayı koruyarak kısa video için yeniden kurar.",
    highlights: [["Kaynak", "Onaylı video/ses bölümü ve transkript"], ["Kreatif", "An haritası, açılış, altyazı ve kadraj"], ["Teslim", "Kapsamlı varyant, değerlendirme ve düzenli dosya"]],
    sections: [["An seçimi", "Tek net fikir, gerilim, pratik değer veya hikâye hareketi ararız. Eksik bağlam konuk veya sunucuyu çarpıtabilecekse kısa bölüm reddedilir."], ["Görsel uygulama", "Kaynak kalitesi ve kapsama göre konuşmacı kadrajı, okunur altyazı, destekleyici grafik, bölüm bağlamı ve platforma güvenli düzen kullanılabilir."], ["Program tasarımı", "Düzenli program bölüm alımı, hariçler, onay sahibi, çıktı düzeni, platformlar ve öğrenme notlarını tanımlar. Adet ve süre gerçek kaynak incelendikten sonra kabul edilir."]], cta: "Podcast clipping planla"
  }, ["what-is-clipping", "repurposing", "campaigns"]),
  make("tiktok", "Service", "services/tiktok-clipping", "hizmetler/tiktok-clipping", {
    title: "TikTok Clipping Service | Platform-Native Short Video", description: "Adapt approved long-form moments for TikTok with clear hooks, captions, pacing, safe zones and review.", kicker: "TikTok clipping", headline: "Adapt the idea for TikTok without flattening its meaning.", lead: "TikTok clipping requires more than a 9:16 crop. The opening, context speed, captions, visual rhythm and safe zones need to support a viewer who encounters the clip cold.",
    highlights: [["Opening", "Immediate context and reason to continue"], ["Format", "Vertical framing, captions and safe zones"], ["Control", "Brand, claim and publishing approval"]],
    sections: [["Creative adaptation", "We identify the central idea, remove unnecessary setup, preserve necessary context and create a clear first frame. Trend use is considered only when it fits rights, brand and shelf life."], ["Platform preparation", "Scope may include 9:16 framing, captions, graphic hierarchy, cover direction and version notes. Final specifications follow the platform and account requirements available at delivery."], ["Measurement boundaries", "Accessible views, watch behavior, completion and engagement can guide iteration. Results vary; a TikTok view is not a guaranteed unique person, lead or sale."]], cta: "Scope TikTok clips"
  }, {
    title: "TikTok Clipping Hizmeti | Platforma Doğal Kısa Video", description: "Onaylı uzun içerik anlarını net açılış, altyazı, tempo, güvenli alan ve onayla TikTok'a uyarlayın.", kicker: "TikTok clipping", headline: "Fikri anlamını düzleştirmeden TikTok'a uyarlayın.", lead: "TikTok clipping, 9:16 kırpmadan fazlasını gerektirir. Açılış, bağlam hızı, altyazı, görsel ritim ve güvenli alanlar kliple ilk kez karşılaşan izleyiciyi desteklemelidir.",
    highlights: [["Açılış", "Anında bağlam ve devam nedeni"], ["Format", "Dikey kadraj, altyazı ve güvenli alan"], ["Kontrol", "Marka, iddia ve yayın onayı"]],
    sections: [["Kreatif uyarlama", "Ana fikri belirler, gereksiz kurulumu çıkarır, gerekli bağlamı korur ve net ilk kare oluştururuz. Trend yalnızca hak, marka ve raf ömrüne uyuyorsa değerlendirilir."], ["Platform hazırlığı", "Kapsam 9:16 kadraj, altyazı, grafik hiyerarşi, kapak yönü ve versiyon notu içerebilir. Son özellikler teslim anındaki platform ve hesap gereksinimini izler."], ["Ölçüm sınırları", "Erişilebilen görüntülenme, izleme davranışı, tamamlama ve etkileşim yinelemeyi yönlendirebilir. Sonuç değişir; TikTok görüntülenmesi garantili tekil kişi, potansiyel müşteri veya satış değildir."]], cta: "TikTok kliplerini kapsamlandır"
  }, ["strategy", "campaigns", "brands"]),
  make("reels", "Service", "services/instagram-reels-clipping", "hizmetler/instagram-reels-clipping", {
    title: "Instagram Reels Clipping Service | Reklamatic", description: "Create context-rich Instagram Reels from approved podcasts, interviews and brand footage with platform adaptation and review.", kicker: "Instagram Reels clipping", headline: "Turn source moments into Reels that make sense without the original post.", lead: "Reels clipping packages a selected idea for mobile viewing while considering captions, composition, cover context, brand language and how the clip may be encountered in feed or profile.",
    highlights: [["Meaning", "A self-contained thought or story"], ["Presentation", "Readable mobile composition and captions"], ["Workflow", "Approval, versions and organized delivery"]],
    sections: [["Source to Reel", "We select a moment, establish the context early, adapt pacing and create a visual hierarchy that supports rather than competes with the speaker or product."], ["Brand consistency", "Typography, colors, claims, logos, disclosures and prohibited topics follow the approved guidance. Third-party music or footage is used only under suitable rights."], ["Learning from Reels", "Available watch and engagement signals may guide later topics or openings. Historical account performance does not predict a client's future result."]], cta: "Plan Reels clipping"
  }, {
    title: "Instagram Reels Clipping Hizmeti | Reklamatic", description: "Onaylı podcast, röportaj ve marka çekimlerinden platform uyarlaması ve onayla bağlamlı Instagram Reels üretin.", kicker: "Instagram Reels clipping", headline: "Kaynak anları özgün gönderi olmadan da anlaşılır Reels videolarına dönüştürün.", lead: "Reels clipping seçili fikri mobil izlemeye hazırlar; altyazı, kompozisyon, kapak bağlamı, marka dili ve klibin akış ya da profilde nasıl görüleceğini dikkate alır.",
    highlights: [["Anlam", "Tek başına fikir veya hikâye"], ["Sunum", "Okunur mobil kompozisyon ve altyazı"], ["İş akışı", "Onay, versiyon ve düzenli teslim"]],
    sections: [["Kaynaktan Reel'e", "Anı seçer, bağlamı erken kurar, tempoyu uyarlar ve konuşmacı ya da ürünle yarışmak yerine onu destekleyen görsel hiyerarşi oluştururuz."], ["Marka tutarlılığı", "Tipografi, renk, iddia, logo, açıklama ve yasaklı konular onaylı rehberi izler. Üçüncü taraf müzik veya görüntü yalnızca uygun haklarla kullanılır."], ["Reels'ten öğrenme", "Erişilebilen izleme ve etkileşim sinyalleri sonraki konu veya açılışı yönlendirebilir. Geçmiş hesap performansı müşterinin gelecek sonucunu tahmin etmez."]], cta: "Reels clipping planla"
  }, ["strategy", "campaigns", "brands"]),
  make("shorts", "Service", "services/youtube-shorts-clipping", "hizmetler/youtube-shorts-clipping", {
    title: "YouTube Shorts Clipping Service | Reklamatic", description: "Repurpose approved long-form YouTube, podcast and education content into structured vertical Shorts.", kicker: "YouTube Shorts clipping", headline: "Build a short discovery layer around your long-form library.", lead: "Shorts clipping can connect useful moments from a long-form library to new viewers. Each clip still needs its own opening, context, pacing, captions and clear relationship to the source strategy.",
    highlights: [["Library", "Approved episodes, lessons and interviews"], ["Structure", "Self-contained vertical narratives"], ["Connection", "Optional source relationship when scoped"]],
    sections: [["Select for discovery", "Choose moments that answer a question, demonstrate expertise or move through a compact story. Do not cut only because a segment is short."], ["Prepare the Short", "Adapt framing, captions, pace, visual support and ending for vertical viewing. Titles, descriptions or source links are included only when agreed in delivery or publishing scope."], ["Review the signal", "Views, watch behavior and engagement may support later decisions where accessible. They do not guarantee subscribers, long-form transfer or conversion."]], cta: "Plan YouTube Shorts"
  }, {
    title: "YouTube Shorts Clipping Hizmeti | Reklamatic", description: "Onaylı uzun YouTube, podcast ve eğitim içeriğini yapılandırılmış dikey Shorts videolarına dönüştürün.", kicker: "YouTube Shorts clipping", headline: "Uzun içerik kütüphanenizin çevresinde kısa keşif katmanı kurun.", lead: "Shorts clipping uzun kütüphanedeki faydalı anları yeni izleyicilerle buluşturabilir. Her klip yine kendi açılışına, bağlamına, temposuna, altyazısına ve kaynak stratejisiyle net ilişkisine ihtiyaç duyar.",
    highlights: [["Kütüphane", "Onaylı bölüm, ders ve röportaj"], ["Yapı", "Tek başına dikey anlatılar"], ["Bağlantı", "Kapsama göre kaynak ilişkisi"]],
    sections: [["Keşif için seçin", "Bir soruyu yanıtlayan, uzmanlığı gösteren veya kısa hikâyede ilerleyen anları seçin. Sırf bölüm kısa diye klip çıkarmayın."], ["Short'u hazırlayın", "Kadraj, altyazı, tempo, görsel destek ve kapanışı dikey izlemeye uyarlayın. Başlık, açıklama veya kaynak linki yalnızca teslim ya da yayın kapsamı kabul edildiyse dahildir."], ["Sinyali değerlendirin", "Erişilebiliyorsa görüntülenme, izleme davranışı ve etkileşim sonraki kararı destekleyebilir. Abone, uzun videoya geçiş veya dönüşüm garantisi vermez."]], cta: "YouTube Shorts planla"
  }, ["repurposing", "strategy", "brands"]),
  make("brands", "Service", "for-brands", "markalar-icin", {
    title: "Clipping for Brands | Reach Audiences Through a Clipper Network", description: "Distribute app, music, publisher, creator and product campaigns through Reklamatic's active Türkiye-focused clipper network.", kicker: "For brands", headline: "Put one campaign into many relevant short-video feeds.", lead: "Instead of negotiating separately with every creator account, submit one Reklamatic campaign form. We prepare platform-native short videos, coordinate approval, distribute through suitable accounts in our active clipper network and report eligible views.",
    highlights: [["You define", "Product, audience, budget, source and brand rules"], ["We operate", "Creative, approval, account selection and publishing"], ["You receive", "Verified post list and eligible-view reporting"]],
    sections: [["Who can advertise", "The model fits brands, apps, artists, publishers, streamers, influencers and products that want to reach a Türkiye audience through TikTok, Instagram Reels and YouTube Shorts."], ["What Reklamatic does", "We turn the submitted form into content directions, prepare or adapt the short videos, coordinate brand approval, select suitable accounts from the active clipper network, schedule publishing and verify the resulting posts."], ["Fixed-price account distribution", "Subject to campaign fit and confirmed capacity, a brand can request publishing through 50–200 suitable accounts at an agreed daily video volume. The fixed quote is based on account count, daily posts, platforms and duration."], ["What the campaign guarantees", "If the proposal includes a view target, the agreement defines eligible accounts, platforms, audience geography, measurement source, counting window, exclusions and the shortfall remedy. Sales and virality are not guaranteed."]], cta: "Advertise with Reklamatic"
  }, {
    title: "Markalar için Clipping | Kampanya Planlama ve Üretim", description: "Markalar için net clipping yolu: kaynak inceleme, kampanya kapsamı, kurgu, onay, teslim ve ölçüm.", kicker: "Markalar için", headline: "Onaylı kaynak içeriği kontrollü kısa video programına dönüştürün.", lead: "Reklamatic uygulama, müzik ve yayıncı ekiplerine kreatif yön, kısa video üretimi, yönetilen clipper ataması, marka onayı, yayın koordinasyonu ve raporlama sağlar.",
    highlights: [["Getirin", "Kaynak, haklar, kitle, hedef ve marka kuralları"], ["Alın", "Yazılı kapsam, kreatif plan ve onaylı teslimatlar"], ["Karar verin", "Yalnız teslim veya açıkça kapsamlı yayın desteği"]],
    sections: [["Markadan gerekenler", "Yetkili kaynak, iş amacı, kitle, platform önceliği, izinli-yasaklı iddia, görsel kurallar, açıklama gereksinimi ve hesap verebilir tek onay sahibi sağlayın."], ["Reklamatic neyi kapsamlandırabilir?", "Kaynak denetimi, clipping stratejisi, sürekli üretim, kampanya sprinti, platform versiyonu, revizyon, düzenli teslim ve clipper dağıtımı seçenekleri vardır."], ["Sabit fiyatlı hesap dağıtımı", "Kampanya uyumu ve mevcut kapasite onaylandığında 50–200 uygun hesaptan, kararlaştırılan günlük video adediyle yayın planlanabilir. Sabit teklif; hesap sayısı, günlük yayın, platformlar ve süreye göre hazırlanır."], ["Başarı nasıl konuşulur?", "Hangi erişilebilir platform sinyalinin önemli olduğunu ve hangi kararı etkileyebileceğini kabul ederiz. Organik erişim ve dönüşüm garanti değildir; görüntülenme her zaman tekil kişi değildir, atıf sınırlıdır."]], cta: "Marka formunu başlat"
  }, ["campaigns", "pricing", "cases"]),
  make("clippers", "WebPage", "for-clippers", "clipper-ol", {
    title: "Become a Clipper | Earn from Eligible Campaign Views", description: "Apply with your public short-video account and learn how Reklamatic campaign rates, eligible views and publishing rules work.", kicker: "Become a clipper", headline: "Turn eligible campaign views into earnings.", lead: "A clipper prepares or adapts short videos from approved source material and written campaign conditions, then publishes them through an eligible account. When your account, category and audience fit a campaign, the per-1,000-view rate and eligibility rules are shown before you accept.",
    highlights: [["Apply", "Public account or portfolio and content category"], ["Choose", "A suitable campaign with written rules"], ["Earn", "Campaign rate for eligible verified views"]],
    sections: [["Why this is different", "Growing a page for future sponsorships takes time and a brand deal may never arrive. Ordinary Instagram or TikTok views are not automatic income for every account, while YouTube platform revenue requires channel eligibility. A Reklamatic campaign creates a separate earning path; channel monetization is not required for campaign-based payment."], ["Extension, automation and training", "Reklamatic's clipper system organizes content variants, campaign queues, authorized multi-account management and publishing workflows. Setup, training and consulting help a clipper handle more content and accounts in the same time; platform limits still apply."], ["Earnings and ongoing access", "A campaign can state a rate for each 1,000 eligible and verified views. The written conditions define platform, audience geography, counting window, exclusions and payment terms before publishing. Accepted clippers do not pay a recurring subscription to access future Reklamatic campaigns."], ["Optional company setup support", "A separate one-time paid service can support the sole proprietorship setup process. Campaign participation and the automation package are not required. A licensed accountant confirms the correct tax route and obligations."], ["Why local campaigns matter", "Some overseas campaigns require views from specific countries, often the United States. A Türkiye-based audience may not qualify. Reklamatic's local campaigns are designed around the Türkiye audience and accounts named in the campaign conditions. Application does not guarantee work or earnings."]], cta: "Apply as a clipper"
  }, {
    title: "Clipper ve Editörler için | İlginizi Paylaşın", description: "Gelecekteki olası Reklamatic iş birliği için herkese açık clipping portfolyonuzu, platform, dil ve uzmanlıklarınızı paylaşın.", kicker: "Clipper adayları için", headline: "Anında iş sözü olmadan yeteneğinizi paylaşın.", lead: "Reklamatic şu anda editör ve kısa video uzmanlarından ilgi toplar. Bu otomatik üyelik portalı, canlı iş pazaryeri, performans ödeme sistemi veya onboarding garantisi değildir.",
    highlights: [["Portfolyo", "Parolasız görülebilen herkese açık işler"], ["Uzmanlık", "Format, platform, dil ve hareketli grafik"], ["Durum", "Gelecekteki olası eşleşme için ilgi toplama"]],
    sections: [["Ne paylaşılmalı?", "Herkese açık portfolyo, en güçlü kısa video formatları, platform deneyimi, diller, altyazı ve hareketli grafik becerisi, uygunluk ve kalite kontrol yaklaşımınızı paylaşın."], ["Ne paylaşılmamalı?", "Gizli müşteri dosyası, özel link, parola, erişim token'ı, kişisel veri veya gösterme yetkiniz olmayan materyal göndermeyin."], ["Sonra ne olur?", "Reklamatic portfolyoyu inceleyebilir ve gizlilik politikasına göre ilgili gelecek iletişimi için e-postayı saklayabilir. Gönderim yanıt süresi, onboarding, görev, ücret veya kazanç garantisi vermez."]], cta: "Clipper ilgi formunu aç"
  }, ["what-is-clipping", "faq", "contact"]),
  make("contact", "ContactPage", "contact", "iletisim", {
    title: "Contact Reklamatic | Campaign Form or Clipper Interest", description: "Contact Reklamatic for a brand clipping scope or share clipper interest through clear separate pathways.", kicker: "Contact", headline: "Submit a campaign form or a public clipper portfolio.", lead: "Choose the relevant path before emailing. The website form prepares an email in your own mail application; it does not upload files, create accounts or promise a placement.",
    highlights: [["Email", "info@reklamatic.ai"], ["Phone", "+90 530 231 29 47"], ["Safety", "Never send passwords, tokens or unauthorized files"]],
    sections: [["Brand inquiries", "Include company or channel, market, target platforms, indicative budget, public source URL, service interest and the business question the clips should support."], ["Clipper interest", "Include a public portfolio URL, specialty, platform experience, languages, availability and a short note on your editing and quality-control approach."], ["Privacy and response", "Use only contact information you are authorized to share and read the privacy policy. Email does not create a service agreement, account, onboarding or guaranteed response time."]], cta: "Go to the secure contact choices"
  }, {
    title: "Reklamatic İletişim | Marka Formu veya Clipper Başvurusu", description: "Net biçimde ayrılmış yollarla marka clipping kapsamı için Reklamatic'e ulaşın veya clipper ilginizi paylaşın.", kicker: "İletişim", headline: "Marka formunu veya herkese açık clipper portfolyonu paylaş.", lead: "E-posta göndermeden ilgili yolu seçin. Site formu kendi e-posta uygulamanızda mesaj hazırlar; dosya yüklemez, hesap açmaz veya yerleşim sözü vermez.",
    highlights: [["E-posta", "info@reklamatic.ai"], ["Telefon", "+90 530 231 29 47"], ["Güvenlik", "Parola, token veya yetkisiz dosya göndermeyin"]],
    sections: [["Marka talepleri", "Şirket veya kanal, pazar, hedef platformlar, tahmini bütçe, herkese açık kaynak URL'si, hizmet ilgisi ve kliplerin destekleyeceği iş sorusunu ekleyin."], ["Clipper ilgisi", "Herkese açık portfolyo URL'si, uzmanlık, platform deneyimi, diller, uygunluk ve kurgu-kalite kontrol yaklaşımınız hakkında kısa not ekleyin."], ["Gizlilik ve yanıt", "Yalnızca paylaşma yetkiniz olan iletişim bilgisini kullanın ve gizlilik politikasını okuyun. E-posta hizmet sözleşmesi, hesap, onboarding veya garantili yanıt süresi oluşturmaz."]], cta: "Güvenli iletişim seçeneklerine git"
  }, ["brands", "clippers", "faq"]),
];

const clearTurkishCopy = {
  about: {
    title: "Reklamatic Hakkında | Clipping Ajansı ve Dağıtım Ağı",
    description: "Reklamatic'in kampanya formunu kısa videoya, aktif clipper dağıtımına ve uygun görüntülenme raporuna nasıl dönüştürdüğünü öğrenin.",
    kicker: "Reklamatic hakkında",
    headline: "Kampanya formundan aktif clipper ağıyla dağıtıma tek ajans operasyonu.",
    lead: "Reklamatic, marka, uygulama, sanatçı, yayıncı, streamer ve influencer içeriklerini platforma uygun kısa videolara dönüştürür; clipper eşleşmesini, onayı, yayını ve raporlamayı koordine eder. Yayın geçmişimiz milyonlarca platform görüntülenmesi içerir.",
    highlights: [["Aktif ağ", "Clipper'lar ve uygun yayın hesapları"], ["Kanıtlı dağıtım", "Milyonlarca geçmiş platform görüntülenmesi"], ["Marka kontrolü", "Form, içerik onayı ve yazılı ölçüm kuralları"]],
    sections: [["Neden varız?", "Markaların her hesapla ayrı ayrı iletişim, form, üretim, onay ve yayın takibi yapma yükünü tek kampanya operasyonunda toplarız."], ["Ne yapıyoruz?", "Kampanya hedefini netleştirir, kısa video formatlarını hazırlar, marka onayını alır, aktif clipper ağındaki uygun hesaplarda yayını koordine eder ve mutabık platform verilerini raporlarız."], ["Sözleşme neyi belirler?", "İçerik, hesap, platform, hedef coğrafya, onay, ölçüm ve ticari koşullar baştan yazılır. Uygun view garantisi varsa hedef, sayım kuralı, hariçler ve eksik kalma telafisi tanımlanır; satış veya viral sonuç garanti edilmez."]],
    cta: "Reklamatic ile çalış"
  },
  agency: {
    title: "Clipping Ajansı | İçerik Üretimi ve Clipper Dağıtımı",
    description: "Marka kampanyanızı kısa videolara dönüştürün ve uygun clipper hesaplarında yayımlayın. Üretim, dağıtım ve raporlama tek yerde.",
    kicker: "Clipping ajansı",
    headline: "Sadece video üretmeyiz; videoyu doğru hesaplarda gerçek paylaşıma dönüştürürüz.",
    lead: "Reklamatic, markanız için kısa video kampanyasını planlar, uygun clipper'ları seçer, içerikleri kontrol eder ve onaylanan videoların üreticilerin kendi hesaplarında yayımlanmasını yönetir.",
    highlights: [["Üretim", "Markaya ve platforma uygun kısa videolar"], ["Dağıtım", "Kendi kitlesi olan clipper hesaplarında paylaşım"], ["Takip", "İçerik, hesap ve sonuç bazında kampanya raporu"]],
    sections: [["Ajans ne yapar?", "Hedef kitleyi, platformu, bütçeyi ve marka kurallarını netleştirir; kampanyaya uygun içerik açıları oluşturur; clipper'larla eşleştirir; içerikleri yayın öncesi kontrol eder ve paylaşımları takip ederiz."], ["Kimler için uygundur?", "Ürününü, uygulamasını, müziğini, etkinliğini, podcast'ini veya hizmetini TikTok, Instagram Reels ve YouTube Shorts üzerinde farklı hesaplar üzerinden duyurmak isteyen markalar için uygundur."], ["Marka nasıl kontrolü korur?", "Kullanılabilecek mesajlar, yasaklı iddialar, görsel kurallar, reklam açıklaması ve hesap seçim ölçütleri kampanya formu ile sözleşmede belirlenir. Onaysız içerik kampanya yayınına çıkmaz."]],
    cta: "Markam için kampanya iste"
  },
  campaigns: {
    title: "Clipping Kampanyası Nasıl Çalışır? | Reklamatic",
    description: "Marka formundan aktif clipper ağında yayına ve uygun görüntülenme raporuna kadar Reklamatic clipping sürecini öğrenin.",
    kicker: "Sistem nasıl çalışır?",
    headline: "Formu doldurun. Clipper ağımız üretsin ve dağıtsın. Uygun görüntülenmeler raporlansın.",
    lead: "Reklamatic marka, uygulama, sanatçı, yayıncı ve influencer kampanyalarını tek süreçte yönetir: hedef ve koşulları belirler, kısa videoları hazırlar, onaylatır, uygun hesaplarda yayınlar ve mutabık sonucu raporlar.",
    highlights: [["1 · Form", "Hedef, kitle, bütçe, kaynak ve view kuralları"], ["2 · Dağıtım", "Üretim, onay ve uygun clipper hesapları"], ["3 · Rapor", "Doğrulanmış yayınlar ve sözleşmedeki uygun view"]],
    sections: [["1. Kampanyayı kur", "Marka; neyi tanıtacağını, Türkiye'de kime ulaşmak istediğini, bütçesini, onaylı materyalini, platformlarını ve yasaklı iddiaları paylaşır. Reklamatic bunları yazılı kampanya kapsamına dönüştürür."], ["2. Üret ve yayınla", "Kısa video yönleri ve platform versiyonları hazırlanır, kontrol edilir ve onaylanır. Yayın, Reklamatic'in aktif clipper ağındaki kampanyaya uygun hesaplarda koordine edilir."], ["3. Sonucu ölç", "Sözleşme uygun hesapları, platformları, coğrafyayı, sayım dönemini, hariçleri ve varsa eksik kalma telafisini yazar. Rapor doğrulanmış yayınları ve uygun görüntülenmeleri gösterir; satış veya viral sonuç sözü vermez."]],
    cta: "Kampanya başlat"
  },
  pricing: {
    title: "Clipping Kampanyası Fiyatları | Reklamatic",
    description: "Clipper sayısı, içerik adedi, platform, kampanya süresi ve ödeme modeline göre clipping kampanyası fiyatının nasıl belirlendiğini öğrenin.",
    kicker: "Kampanya bütçesi",
    headline: "Fiyat; kaç içerik üretileceğine, kaç hesapta paylaşılacağına ve hedefinize göre belirlenir.",
    lead: "Her marka ve kampanya farklıdır. Bu nedenle tek paket fiyat yerine içerik üretimi, clipper dağıtımı, kampanya süresi, platformlar ve raporlama ihtiyacına göre açık bir teklif hazırlarız.",
    highlights: [["İçerik", "Video adedi, çekim ihtiyacı ve kreatif çeşitlilik"], ["Dağıtım", "Clipper sayısı, hesap türleri ve platformlar"], ["Operasyon", "Onay, yayın takibi, veri doğrulama ve rapor"]],
    sections: [["Bütçeyi ne etkiler?", "Video sayısı, kreatif çeşitlilik, atanacak clipper ve hesap kapsamı, platformlar, kampanya süresi, revizyonlar ve raporlama ihtiyacı bütçeyi belirler."], ["Sabit fiyatlı dağıtım nasıl hesaplanır?", "Kapasite ve kampanya uyumu onaylandığında 50–200 uygun hesaptan günlük kararlaştırılan video adediyle yayın planlanabilir. Fiyat hesap sayısı, günlük yayın, platform ve süreye göre sabitlenir."], ["Teklifte ne yer alır?", "İçerik adedi, clipper ve hesap ölçütleri, yayın koşulları, takvim, onay süreci, raporlama ve ticari şartlar açıkça yazılır."], ["View hedefi nasıl fiyatlanır?", "Bazı kampanyalar sözleşmede tanımlı uygun view hedefi içerir. Ölçüm kaynağı, hesaplar, dönem, hariçler ve eksik kalma telafisi teklifte yazılır; satış ve viral sonuç bu garantinin dışındadır."]],
    cta: "Bütçeme göre teklif al"
  },
  brands: {
    title: "Markalar için Clipping Reklamı | Reklamatic",
    description: "Uygulama, müzik, yayıncı, influencer ve ürün kampanyalarınızı Reklamatic'in aktif clipper ağıyla farklı sosyal medya hesaplarında dağıtın.",
    kicker: "Markalar için",
    headline: "Tek kampanyayla farklı kısa video akışlarında yer alın.",
    lead: "Her hesapla ayrı pazarlık yapmak yerine Reklamatic formunu bir kez doldurun. Kısa videoları hazırlayalım, onayınızı alalım, aktif clipper ağımızdaki uygun hesaplarda yayınlayalım ve uygun görüntülenmeleri tek raporda gösterelim.",
    highlights: [["Siz belirleyin", "Ürün, hedef kitle, bütçe, kaynak ve marka kuralları"], ["Biz yönetelim", "Kreatif, onay, hesap seçimi ve yayın"], ["Siz görün", "Doğrulanmış yayın listesi ve uygun view raporu"]],
    sections: [["Kimler reklam verebilir?", "Türkiye kitlesine TikTok, Instagram Reels ve YouTube Shorts üzerinden ulaşmak isteyen markalar, uygulamalar, sanatçılar, yayıncılar, streamer'lar, influencerlar ve ürün sahipleri için uygundur."], ["Reklamatic ne yapar?", "Formdaki bilgileri içerik yönlerine dönüştürür, kısa videoları üretir veya uyarlar, marka onayını koordine eder, aktif clipper ağındaki uygun hesapları seçer, yayını planlar ve gönderileri doğrularız."], ["Sabit fiyatlı dağıtım seçeneği", "Kampanya uyumu ve kapasite onayına göre 50–200 uygun hesaptan, belirlenen günlük video adediyle yayın planı kurulabilir. Fiyat hesap sayısı, günlük yayın, platformlar ve süreye göre sabitlenir."], ["Kampanya neyi garanti eder?", "Teklif view hedefi içeriyorsa sözleşme uygun hesapları, platformları, coğrafyayı, ölçüm kaynağını, sayım dönemini, hariçleri ve eksik kalma telafisini yazar. Satış ve viral sonuç garanti edilmez."]],
    cta: "Reklam vermek istiyorum"
  },
  clippers: {
    title: "Clipper Ol | Uygun Görüntülenmeden Kazan",
    description: "Herkese açık kısa video hesabınla başvur; Reklamatic kampanyalarında 1.000 uygun görüntülenme başına oran ve yayın kurallarının nasıl işlediğini öğren.",
    kicker: "Clipper ol",
    headline: "Uygun kampanya görüntülenmesini kazanca çevir.",
    lead: "Clipper, onaylı kaynaktan ve yazılı kampanya koşullarından kısa video hazırlar; uygun hesabında yayınlar. Hesabın, kategorin ve kitlen kampanyaya uyarsa 1.000 görüntülenme başına oranı ve geçerlilik kurallarını işi kabul etmeden görürsün.",
    highlights: [["Başvur", "Herkese açık hesap veya portfolyo ve içerik kategorisi"], ["Üret", "Eklenti, AI veya CapCut destekli içerik akışı"], ["Kazan", "Uygun doğrulanmış görüntülenme için kampanya oranı"]],
    sections: [["Neden farklı?", "Gelecekte reklam almak için sayfa büyütmek zaman alır ve iş birliği hiç gelmeyebilir. Normal Instagram veya TikTok görüntülenmesi her hesap için otomatik gelir değildir; YouTube platform geliri de kanal uygunluğu ister. Reklamatic kampanyası ayrı bir kazanç yolu oluşturur; kanalın platform para kazanma statüsü kampanya ödemesi için şart değildir."], ["Eklenti ve eğitim ne sağlar?", "Reklamatic'in clipper otomasyonu; içerik varyasyonlarını, kampanya sırasını, çoklu yetkili hesap yönetimini ve yayın akışını düzenler. Kurulum, eğitim ve danışmanlık paketi aynı sürede daha fazla içerik ve hesabı yönetmeyi hedefler; platform limitleri geçerlidir."], ["Kazanç ve sürekli erişim", "Kampanya her 1.000 uygun ve doğrulanmış görüntülenme için bir oran belirleyebilir. Platform, hedef coğrafya, sayım dönemi, hariçler ve ödeme koşulları yayından önce yazılır. Kabul edilen clipper'lar gelecekteki Reklamatic kampanyalarına erişmek için tekrar eden abonelik ödemez."], ["Şahıs şirketi kuruluş desteği", "İsteğe bağlı, ayrı ve tek seferlik ücretli bir hizmettir. Kampanyalara katılmak veya otomasyon paketini almak gerekmez. Başvurudan kuruluma kadar süreç desteği verilir; doğru vergi modeli ve yükümlülükler mali müşavir tarafından teyit edilir."], ["Türkiye kampanyası neden önemli?", "Bazı yurt dışı kampanyaları belirli ülkelerden, çoğunlukla ABD'den görüntülenme ister. Türkiye kitlesi geçerli sayılmayabilir. Reklamatic'in yerel kampanyaları yazılı Türkiye kitlesi ve hesap koşullarına göre kurulur. Başvuru iş veya kazanç garantisi değildir."]],
    cta: "Clipper başvurusu yap"
  },
  faq: {
    title: "Clipping Hakkında Sık Sorulan Sorular | Reklamatic",
    description: "Markaların nasıl reklam verdiğini, clipper'ların nasıl çalışıp kazandığını ve kampanya paylaşımlarının nasıl yönetildiğini öğrenin.",
    kicker: "Sık sorulan sorular",
    headline: "Marka ve clipper tarafındaki tüm temel soruların net cevapları.",
    lead: "En basit haliyle marka kampanya açar; clipper kısa videoyu hazırlar ve uygun sosyal medya hesabında yayınlar; Reklamatic eşleşme, onay, aktif ağ dağıtımı, takip ve raporlamayı koordine eder.",
    faq: [["Clipping nedir?", "Onaylı kaynak ve yazılı kampanya koşullarının tek başına anlaşılır kısa videoya dönüştürülüp uygun sosyal medya hesabında dağıtılmasıdır."], ["Clipper kimdir?", "Kısa videoyu hazırlayan veya uyarlayan, kampanya kurallarına uyan ve uygun hesabında yayınlayan içerik üreticisi ya da hesap yöneticisidir."], ["Clipper nasıl kazanır?", "Kampanya her 1.000 uygun ve doğrulanmış görüntülenme için bir oran belirleyebilir. Oran ve sayım kuralları işten önce gösterilir; başvuru görev veya kazanç garantisi değildir."], ["Clipper eklentisi ne sağlar?", "İçerik varyasyonu, kampanya sırası, çoklu yetkili hesap yönetimi ve yayın akışını kolaylaştırır. Kurulum, eğitim ve danışmanlıkla birlikte sunulur; platform izinleri ve limitleri geçerlidir."], ["Para kazanan kanal gerekli mi?", "Reklamatic kampanya ödemesi için kanalın platform para kazanma programında olması gerekmez. Uygun görüntülenme ve ödeme, kabul edilen kampanyanın yazılı koşullarına göre değerlendirilir."], ["Şirket kuruluş desteği var mı?", "Evet. İsteğe bağlı şahıs şirketi kuruluş desteği ayrı ve tek seferlik ücretli bir hizmettir; kampanyaya veya otomasyon paketine katılım şartı yoktur. Vergi yolu mali müşavir tarafından teyit edilir."], ["Marka olarak ne satın alırım?", "Yazılı kapsam; içerik üretimi, uygun hesap seçimi, onay, yayın koordinasyonu, gönderi doğrulama, raporlama ve sözleşmede tanımlı uygun view hedefini içerebilir."], ["Görüntülenme garantisi var mı?", "Bazı kampanyalarda sözleşme uygun view hedefini, hesapları, platformları, coğrafyayı, ölçüm kaynağını, dönemi, hariçleri ve eksik kalma telafisini tanımlar. Satış veya viral sonuç garanti edilmez."], ["Reklamatic'in dağıtım ağı var mı?", "Evet. Reklamatic aktif clipper ağıyla içerik üretimi, uygun hesap seçimi, yayın ve raporlamayı koordine eder; yayın geçmişi milyonlarca platform görüntülenmesi içerir."]],
    sections: [["Marka için", "Kampanya hedefi, bütçe, içerik, platform ve onay kuralları belirlenir; uygun clipper'lar seçilir ve yayınlar raporlanır."], ["Clipper için", "Hesap ve içerik örnekleriyle başvuru yapılır; uygun kampanyalar teklif edilir; kabul edilen iş yazılı kampanya koşullarına göre üretilip paylaşılır."], ["Güvenlik ve şeffaflık", "İçerik hakları, reklam açıklaması, ödeme koşulları ve ölçüm yöntemi her kampanyada baştan belirlenir."]],
    cta: "Başvuru yollarını gör"
  },
  contact: {
    title: "Reklamatic İletişim | Reklam Ver veya Clipper Ol",
    description: "Markanız için clipping kampanyası başlatın veya içerik üreticisi olarak Reklamatic clipper ağına başvurun.",
    kicker: "İletişim",
    headline: "Marka olarak reklam verin veya clipper olarak ağımıza katılın.",
    lead: "İki ayrı yol var: Markaysanız hedefinizi, bütçenizi ve tanıtmak istediğiniz ürünü anlatın. Clipper olmak istiyorsanız sosyal medya hesabınızı, içerik alanınızı ve örnek çalışmalarınızı paylaşın.",
    highlights: [["Marka", "Kampanya talebi ve bütçe bilgisi"], ["Clipper", "Sosyal medya hesabı ve içerik örnekleri"], ["Doğrudan", "info@reklamatic.ai · +90 530 231 29 47"]],
    sections: [["Marka başvurusu", "Marka veya şirket adı, hedef kitle, platformlar, tahmini bütçe, ürün/içerik bağlantısı ve kampanyanın ne başarmasını istediğinizi paylaşın."], ["Clipper başvurusu", "TikTok, Instagram veya YouTube hesabınızı; içerik ürettiğiniz konuları, örnek videolarınızı, çalışma şeklinizi ve uygunluğunuzu paylaşın."], ["Sonraki adım", "Başvuruyu inceledikten sonra uygun kapsam veya eşleşme varsa sizinle iletişime geçeriz. E-posta göndermek sözleşme, otomatik kabul ya da iş garantisi oluşturmaz."]],
    cta: "Doğru başvuru yolunu seç"
  },
  "what-is-clipping": {
    title: "Clipping Nedir? Markalar ve İçerik Üreticileri için Rehber",
    description: "Clipping reklam modelinde markanın nasıl yönetilen dağıtım aldığı ve clipper kampanya koşullarının nasıl belirlendiğini öğrenin.",
    kicker: "Clipping nedir?",
    headline: "Clipping, kısa video üretimini dağıtımla birleştiren kampanya modelidir.",
    lead: "Clip; onaylı kaynaktan ve yazılı kampanya koşullarından hazırlanan kısa ve tek başına anlaşılır videodur. Clipper bu videoyu hazırlar, kampanya kurallarına uyar ve uygun sosyal medya hesabında yayınlar.",
    highlights: [["Marka", "Tek kampanyayla seçili hesaplara ulaşır"], ["Clipper", "Onaylı koşullara göre üretir ve yayımlar"], ["Reklamatic", "Eşleşme, onay, yayın ve raporlamayı yönetir"]],
    sections: [["Kurgudan farkı", "Kurgu dosya tesliminde biter. Clipping kampanyasında içerik mutabık sosyal medya hesaplarında da dağıtılır ve yayın sonucu yazılı kurallara göre ölçülür."], ["Clipper nasıl kazanır?", "Kampanya her 1.000 uygun ve doğrulanmış görüntülenme için oran belirleyebilir. Oran, uygun platform ve hesaplar, hedef coğrafya, sayım dönemi, hariçler ve ödeme koşulları işten önce gösterilir."], ["Türkiye odaklı kampanya neden önemli?", "Bazı yurt dışı kampanyaları belirli ülkelerden görüntülenme ister. Türkiye'den gelen view geçersiz sayılabilir. Reklamatic yerel kampanyaları Türkiye kitlesi, uygun hesaplar ve yazılı ölçüm koşulları etrafında kurar."]],
    cta: "Clipping modelini kullan"
  }
};

Object.entries(clearTurkishCopy).forEach(([key, copy]) => {
  const page = seoPages.find((item) => item.key === key);
  if (page) Object.assign(page.tr, copy);
});

export const findSeoPage = (locale, path) => seoPages.find((page) => page.paths[locale] === path);
export const routeParams = (locale) => seoPages.map((page) => ({ slug: page.paths[locale].split("/") }));
