const make = (key, type, enPath, trPath, en, tr, related = []) => ({ key, type, paths: { en: enPath, tr: trPath }, en, tr, related });

export const seoPages = [
  make("about", "AboutPage", "about", "hakkimizda", {
    title: "About Reklamatic | Human-Led Clipping Operations", description: "Learn how Reklamatic approaches short-form clipping with human editorial judgment, explicit approvals and honest measurement.", kicker: "About Reklamatic", headline: "A clipping operation built around judgment, clarity and control.", lead: "Reklamatic is a Türkiye-based clipping partner for brands, creators and media teams working in Turkish and English. We turn approved long-form sources into short-form systems without pretending that software, views or virality remove the need for human decisions.",
    highlights: [["Human-led", "Editorial choices and quality control stay accountable"], ["Bilingual", "Turkish and English production pathways"], ["Scope-first", "Rights, outputs, approvals and access are written first"]],
    sections: [["Why we exist", "Long-form content often contains useful moments that never become discoverable because teams lack the time or system to select, rebuild and distribute them. Reklamatic provides that operating layer while keeping the original meaning intact."], ["How we work", "We begin with audience, source rights, brand rules and the decision the content should support. Editors then create self-contained clips, clients approve the work, and available platform signals inform the next hypothesis."], ["What we will not promise", "We do not promise guaranteed views, viral outcomes, automatic creator distribution or work for every clipper applicant. Deliverables, publishing responsibility, reporting and commercial terms are defined in the written scope."]], cta: "Discuss a clipping brief"
  }, {
    title: "Reklamatic Hakkında | İnsan Odaklı Clipping Operasyonu", description: "Reklamatic'in kısa video clipping sürecini insan kararı, açık onaylar ve dürüst ölçümle nasıl yürüttüğünü öğrenin.", kicker: "Reklamatic hakkında", headline: "Karar, açıklık ve kontrol etrafında kurulan clipping operasyonu.", lead: "Reklamatic, Türkçe ve İngilizce çalışan marka, içerik üreticisi ve medya ekipleri için Türkiye merkezli clipping partneridir. Onaylı uzun kaynakları kısa video sistemlerine dönüştürürken yazılımın, görüntülenmenin veya viral olmanın insan kararının yerini tuttuğunu iddia etmeyiz.",
    highlights: [["İnsan odaklı", "Editoryal karar ve kalite kontrol hesap verebilir kalır"], ["İki dilli", "Türkçe ve İngilizce üretim akışları"], ["Önce kapsam", "Haklar, çıktılar, onay ve erişim baştan yazılır"]],
    sections: [["Neden varız?", "Uzun içerik çoğu zaman değerli anlar barındırır; ancak ekiplerin bunları seçmek, yeniden kurmak ve dağıtmak için zamanı veya sistemi yoktur. Reklamatic, özgün anlamı koruyarak bu operasyon katmanını sağlar."], ["Nasıl çalışırız?", "Hedef kitle, kaynak hakları, marka kuralları ve içeriğin destekleyeceği kararla başlarız. Editörler tek başına anlaşılır klipler hazırlar, müşteri onaylar ve erişilebilen platform sinyalleri sonraki hipotezi yönlendirir."], ["Ne vaat etmeyiz?", "Garantili görüntülenme, viral sonuç, otomatik üretici dağıtımı veya her clipper adayına iş sözü vermeyiz. Teslimatlar, yayın sorumluluğu, raporlama ve ticari koşullar yazılı kapsamda belirlenir."]], cta: "Clipping brief'ini görüş"
  }, ["agency", "brands", "contact"]),
  make("agency", "Service", "clipping-agency", "clipping-ajansi", {
    title: "Clipping Agency for Brands and Creators | Reklamatic", description: "A human-led clipping agency for turning podcasts, interviews and brand footage into platform-native short videos.", kicker: "Clipping agency", headline: "More than editing: the operating system around every short clip.", lead: "A clipping agency selects moments, rebuilds context, adapts creative for each platform and manages review. Reklamatic adds this external layer without claiming guaranteed distribution or replacing the client's approval responsibility.",
    highlights: [["Inputs", "Approved source, audience, goals and brand rules"], ["Outputs", "Scoped clips, versions and organized delivery"], ["Control", "Client approval before publishing where agreed"]],
    sections: [["What the agency does", "We review source material, create a moment map, propose hooks, edit for vertical viewing, add accessible captions and prepare platform variants. Publishing is included only when permissions and responsibilities are written into scope."], ["Who it fits", "The model fits podcast teams, founders, educators, product brands and agencies with recurring source material but limited internal short-form capacity. Low-volume, tightly directed work may be better suited to a freelance editor."], ["How quality is governed", "Rights, prohibited topics, claims, visual rules, music, disclosures and approval owners are documented. Human quality control checks context, language, specifications and brand fit before delivery."]], cta: "Request an agency scope"
  }, {
    title: "Markalar ve Üreticiler için Clipping Ajansı | Reklamatic", description: "Podcast, röportaj ve marka çekimlerini platforma doğal kısa videolara dönüştüren insan odaklı clipping ajansı.", kicker: "Clipping ajansı", headline: "Kurgudan fazlası: her kısa klibin çevresindeki operasyon sistemi.", lead: "Clipping ajansı anları seçer, bağlamı yeniden kurar, kreatifi platforma uyarlar ve değerlendirme sürecini yönetir. Reklamatic bu dış katmanı sunarken garantili dağıtım iddiasında bulunmaz ve müşteri onay sorumluluğunu ortadan kaldırmaz.",
    highlights: [["Girdiler", "Onaylı kaynak, kitle, hedef ve marka kuralları"], ["Çıktılar", "Kapsamlı klipler, versiyonlar ve düzenli teslim"], ["Kontrol", "Mutabık yayın öncesi müşteri onayı"]],
    sections: [["Ajans ne yapar?", "Kaynağı inceler, an haritası çıkarır, açılışlar önerir, dikey izleme için kurgu yapar, erişilebilir altyazı ve platform varyantları hazırlarız. Yayın, yalnızca yetki ve sorumluluklar kapsamda yazılıysa dahildir."], ["Kimler için uygundur?", "Düzenli kaynağı fakat sınırlı iç kısa video kapasitesi olan podcast ekipleri, kurucular, eğitim şirketleri, ürün markaları ve ajanslar için uygundur. Düşük hacimli net işler için freelance editör daha doğru olabilir."], ["Kalite nasıl yönetilir?", "Haklar, yasaklı konular, iddialar, görsel kurallar, müzik, açıklamalar ve onay sahipleri belgelenir. İnsan kalite kontrolü teslimden önce bağlamı, dili, teknik özellikleri ve marka uyumunu inceler."]], cta: "Ajans kapsamı iste"
  }, ["campaigns", "pricing", "choose-agency"]),
  make("campaigns", "Service", "clipping-campaigns", "clipping-kampanyalari", {
    title: "Clipping Campaigns | Planning, Production and Review", description: "Plan a short-form clipping campaign with clear sources, outputs, approvals, publishing responsibility and measurement boundaries.", kicker: "Clipping campaigns", headline: "A campaign is a controlled learning plan, not a promise of virality.", lead: "Reklamatic structures clipping campaigns around approved source material, a defined audience and a business question. Volume, timing, platforms, permissions and reporting are agreed before production.",
    highlights: [["Source", "Podcast, founder, product, education or event footage"], ["Plan", "Angles, formats, approvals and delivery rhythm"], ["Signals", "Available watch, engagement and action data"]],
    sections: [["Campaign inputs", "The brand provides source rights, audience, objective, platform priorities, claims, visual guidance, exclusions and an approval owner. Private links, tokens and unauthorized files should never be submitted through the website."], ["Possible campaign scope", "A written scope may include a source audit, moment map, hook directions, edited clips, platform versions, caption files, review rounds and organized delivery. There is no default volume or turnaround claim."], ["Publishing and measurement", "Publishing stays with the client unless account access and responsibility are explicitly assigned. Reporting uses accessible platform analytics; views are not always unique people and attribution is limited."]], cta: "Plan a campaign"
  }, {
    title: "Clipping Kampanyaları | Planlama, Üretim ve Onay", description: "Kaynak, çıktı, onay, yayın sorumluluğu ve ölçüm sınırları net bir kısa video clipping kampanyası planlayın.", kicker: "Clipping kampanyaları", headline: "Kampanya, viral olma sözü değil; kontrollü öğrenme planıdır.", lead: "Reklamatic clipping kampanyalarını onaylı kaynak içerik, tanımlı kitle ve iş sorusu etrafında kurar. Hacim, süre, platform, izin ve raporlama üretimden önce kabul edilir.",
    highlights: [["Kaynak", "Podcast, kurucu, ürün, eğitim veya etkinlik çekimi"], ["Plan", "Açılar, formatlar, onay ve teslim düzeni"], ["Sinyaller", "Erişilebilen izleme, etkileşim ve aksiyon verisi"]],
    sections: [["Kampanya girdileri", "Marka; kaynak hakları, kitle, amaç, platform öncelikleri, iddialar, görsel rehber, hariç tutulan konular ve onay sahibi sağlar. Özel link, token ve yetkisiz dosyalar site üzerinden paylaşılmamalıdır."], ["Olası kampanya kapsamı", "Yazılı kapsam; kaynak denetimi, an haritası, açılış yönleri, kurgulanmış klipler, platform versiyonları, altyazı dosyaları, revizyon ve düzenli teslim içerebilir. Varsayılan adet veya süre iddiası yoktur."], ["Yayın ve ölçüm", "Hesap erişimi ve sorumluluğu açıkça atanmadıkça yayın müşteridedir. Raporlama erişilebilen platform analitiğini kullanır; görüntülenme her zaman tekil kişi değildir ve atıf sınırlıdır."]], cta: "Kampanya planla"
  }, ["brands", "cases", "strategy"]),
  make("pricing", "WebPage", "pricing", "fiyatlandirma", {
    title: "Clipping Agency Pricing | How Reklamatic Scopes Work", description: "Understand the variables behind clipping agency pricing, deliverables and written commercial scope without invented package promises.", kicker: "Pricing", headline: "Price follows the real production load—not a vague clip count.", lead: "Reklamatic does not publish a universal price because source complexity, editorial depth, platform variants, approvals and publishing responsibility change the work. A written proposal shows the exact scope and commercial terms.",
    highlights: [["Source load", "Length, quality, languages and review complexity"], ["Creative depth", "Selection, hooks, graphics and platform versions"], ["Operations", "Revisions, access, publishing and reporting"]],
    sections: [["What affects price", "Key variables include source hours, usable moment density, number of platforms, caption and motion requirements, language versions, review rounds, turnaround expectations and whether publishing support is included."], ["What a proposal should state", "A useful proposal names deliverable counts, aspect ratios, included revisions, file organization, approval timing, publishing ownership, reporting period, usage terms and exclusions. Ask questions when any item is unclear."], ["Why no view-based promise", "Organic distribution is controlled by platforms and audiences. Pricing covers the agreed work and operating responsibility, not guaranteed views, conversions or virality."]], cta: "Request a written estimate"
  }, {
    title: "Clipping Ajansı Fiyatlandırması | Reklamatic Kapsamı", description: "Uydurma paket vaatleri olmadan clipping ajansı fiyatını, teslimatları ve yazılı ticari kapsamı belirleyen unsurları öğrenin.", kicker: "Fiyatlandırma", headline: "Fiyat, belirsiz klip adedini değil gerçek üretim yükünü izler.", lead: "Kaynak karmaşıklığı, editoryal derinlik, platform varyantları, onaylar ve yayın sorumluluğu işi değiştirdiği için Reklamatic tek fiyat yayınlamaz. Yazılı teklif net kapsam ve ticari koşulları gösterir.",
    highlights: [["Kaynak yükü", "Süre, kalite, diller ve inceleme karmaşıklığı"], ["Kreatif derinlik", "Seçim, açılış, grafik ve platform versiyonları"], ["Operasyon", "Revizyon, erişim, yayın ve raporlama"]],
    sections: [["Fiyatı ne etkiler?", "Kaynak saati, kullanılabilir an yoğunluğu, platform sayısı, altyazı ve hareketli grafik ihtiyacı, dil versiyonları, revizyon turu, teslim beklentisi ve yayın desteği temel değişkenlerdir."], ["Teklif ne söylemeli?", "İyi teklif teslim adedi, oranlar, revizyon, dosya düzeni, onay zamanı, yayın sahibi, rapor dönemi, kullanım koşulları ve hariçleri yazar. Belirsiz her maddeyi sorun."], ["Neden görüntülenme sözü yok?", "Organik dağıtımı platform ve izleyici belirler. Fiyat, garanti edilen görüntülenme, dönüşüm veya viral sonuç için değil; mutabık iş ve operasyon sorumluluğu içindir."]], cta: "Yazılı tahmin iste"
  }, ["agency", "campaigns", "contact"]),
  make("cases", "CollectionPage", "case-studies", "ornek-kampanyalar", {
    title: "Illustrative Clipping Campaign Examples | Reklamatic", description: "Explore fictional, clearly labelled clipping campaign scenarios for podcast, product and education teams without fabricated results.", kicker: "Illustrative examples", headline: "Planning scenarios—not client case studies or performance claims.", lead: "Reklamatic does not present these examples as completed client work. NOVA AUDIO, VELA APP and NORTHSTAR ACADEMY are fictional names used to show how inputs, outputs and measurement questions could be structured.",
    highlights: [["NOVA AUDIO", "Podcast moment mapping and vertical lessons"], ["VELA APP", "Product explanation and launch variants"], ["NORTHSTAR ACADEMY", "Founder-led education topic clusters"]],
    sections: [["Podcast scenario", "Source: an approved weekly expert episode. Goal: make useful ideas stand alone. Possible outputs: moment map, hook options, captioned vertical cuts and approval sheet. Signals: opening retention, completion, saves and qualitative comments."], ["Product launch scenario", "Source: founder explanation, product demo and approved claims. Goal: answer different audience questions. Possible outputs: demo, objection and founder-story variants. Signals: watch behavior, tracked clicks and stated attribution limits."], ["Education scenario", "Source: webinar, Q&A and direct-to-camera lessons. Goal: build a consistent expert point of view. Possible outputs: topic clusters, self-contained lessons and platform versions. Signals: completion, saves, shares and topic response."]], cta: "Create a real scope from my source"
  }, {
    title: "Temsilî Clipping Kampanya Örnekleri | Reklamatic", description: "Uydurma sonuçlar olmadan podcast, ürün ve eğitim ekipleri için açıkça etiketli kurgusal clipping kampanya senaryolarını inceleyin.", kicker: "Temsilî örnekler", headline: "Planlama senaryoları; müşteri vaka çalışması veya performans iddiası değil.", lead: "Reklamatic bu örnekleri tamamlanmış müşteri işi olarak sunmaz. NOVA AUDIO, VELA APP ve NORTHSTAR ACADEMY; girdi, çıktı ve ölçüm sorularının nasıl yapılandırılabileceğini göstermek için kullanılan kurgusal isimlerdir.",
    highlights: [["NOVA AUDIO", "Podcast an haritası ve dikey dersler"], ["VELA APP", "Ürün anlatımı ve lansman varyantları"], ["NORTHSTAR ACADEMY", "Kurucu odaklı eğitim konu kümeleri"]],
    sections: [["Podcast senaryosu", "Kaynak: onaylı haftalık uzman bölümü. Hedef: fikirleri tek başına anlaşılır kılmak. Olası çıktılar: an haritası, açılış seçenekleri, altyazılı dikey kurgular ve onay formu. Sinyaller: açılışta izleyici tutma, tamamlama, kaydetme ve nitel yorumlar."], ["Ürün lansman senaryosu", "Kaynak: kurucu anlatımı, ürün demosu ve onaylı iddialar. Hedef: farklı kitle sorularını yanıtlamak. Olası çıktılar: demo, itiraz ve kurucu hikâyesi varyantları. Sinyaller: izleme davranışı, izlenebilen tıklama ve belirtilen atıf sınırları."], ["Eğitim senaryosu", "Kaynak: webinar, soru-cevap ve kamera önü dersler. Hedef: tutarlı uzman bakış açısı kurmak. Olası çıktılar: konu kümeleri, tek başına dersler ve platform versiyonları. Sinyaller: tamamlama, kaydetme, paylaşma ve konu tepkisi."]], cta: "Kaynağımdan gerçek kapsam oluştur"
  }, ["campaigns", "brands", "contact"]),
  make("faq", "FAQPage", "faq", "sss", {
    title: "Clipping FAQ | Brands, Campaigns, Rights and Clippers", description: "Answers about clipping, campaign scope, brand safety, measurement, publishing, rights and clipper interest.", kicker: "Frequently asked questions", headline: "Clear answers before a source file changes hands.", lead: "These answers describe Reklamatic's current service boundaries. Your written proposal and agreement control the final deliverables, ownership, access and commercial terms.",
    faq: [["What is clipping?", "Clipping turns selected moments from longer approved material into self-contained short videos for specific platforms."], ["Is it automatic AI clipping?", "Tools may assist transcription or production, but selection, context, brand fit and quality approval remain human responsibilities."], ["Do you guarantee views?", "No. Platforms and audiences control organic reach. We guarantee only the work written in scope."], ["Can Reklamatic publish for us?", "Only when account access, approval, scheduling and reporting responsibilities are explicitly agreed."], ["Who confirms source rights?", "The client confirms rights unless a written agreement clearly assigns another responsibility."], ["Can I apply as a clipper?", "You can share a public portfolio and specialties. This is interest collection, not guaranteed onboarding or work."]],
    sections: [["Campaign scope", "Volume, timing, platforms, revisions and reporting depend on source and requirements. They are written before work begins."], ["Safety and privacy", "Do not send passwords, access tokens, private links or unauthorized material. Brand rules and prohibited topics are documented during scoping."], ["Measurement", "Available views, watch behavior, engagement, clicks and conversions may be reviewed. Views are not always unique people and attribution is limited."]], cta: "Ask a specific question"
  }, {
    title: "Clipping SSS | Marka, Kampanya, Haklar ve Clipper", description: "Clipping, kampanya kapsamı, marka güvenliği, ölçüm, yayın, haklar ve clipper ilgisi hakkında yanıtlar.", kicker: "Sık sorulan sorular", headline: "Kaynak dosya el değiştirmeden önce net yanıtlar.", lead: "Yanıtlar Reklamatic'in mevcut hizmet sınırlarını açıklar. Net teslimat, sahiplik, erişim ve ticari koşullarda yazılı teklif ve sözleşme geçerlidir.",
    faq: [["Clipping nedir?", "Clipping, onaylı uzun materyaldeki seçili anları belirli platformlar için tek başına anlaşılır kısa videolara dönüştürür."], ["Otomatik yapay zekâ clipping mi?", "Araçlar transkripsiyon veya üretime yardımcı olabilir; seçim, bağlam, marka uyumu ve kalite onayı insan sorumluluğunda kalır."], ["Görüntülenme garantisi var mı?", "Hayır. Organik erişimi platform ve izleyici belirler. Yalnızca kapsamda yazan işi garanti ederiz."], ["Reklamatic bizim için yayın yapabilir mi?", "Yalnızca hesap erişimi, onay, takvim ve raporlama sorumlulukları açıkça kabul edildiğinde."], ["Kaynak haklarını kim doğrular?", "Yazılı sözleşme başka sorumluluk atamadıkça müşteri doğrular."], ["Clipper olarak başvurabilir miyim?", "Herkese açık portfolyo ve uzmanlık paylaşabilirsiniz. Bu ilgi toplama sürecidir; onboarding veya iş garantisi değildir."]],
    sections: [["Kampanya kapsamı", "Hacim, süre, platform, revizyon ve raporlama kaynak ve gereksinime bağlıdır. İş başlamadan yazılır."], ["Güvenlik ve gizlilik", "Parola, erişim token'ı, özel link veya yetkisiz materyal göndermeyin. Marka kuralları ve yasaklı konular kapsam sırasında belgelenir."], ["Ölçüm", "Erişilebilen görüntülenme, izleme davranışı, etkileşim, tıklama ve dönüşüm incelenebilir. Görüntülenme her zaman tekil kişi değildir, atıf sınırlıdır."]], cta: "Belirli bir soru sor"
  }, ["agency", "pricing", "contact"]),
  make("blog", "CollectionPage", "blog", "blog", {
    title: "Clipping Resources and Guides | Reklamatic Blog", description: "Practical guides to clipping strategy, UGC, content repurposing, agency selection and short-form planning.", kicker: "Resource library", headline: "Build a better clipping brief before you buy production.", lead: "The Reklamatic guide library explains the decisions behind useful short-form systems. Every guide is educational, contains no guaranteed outcome and links to the next relevant planning step.",
    highlights: [["Basics", "What clipping is and what it is not"], ["Strategy", "How sources, formats and signals connect"], ["Selection", "How to evaluate an agency and scope"]],
    sections: [["Start with the fundamentals", "Read What is Clipping and Content Repurposing to understand source readiness, self-contained meaning and the difference between copying and adapting."], ["Choose the right creative model", "Clipping vs UGC explains how source-led editorial work differs from creator-style product content—and when a program may need both."], ["Turn knowledge into a brief", "Use the strategy and agency-selection guides to document audience, rights, outputs, approvals, publishing and measurement before requesting a proposal."]], cta: "Browse the five guides"
  }, {
    title: "Clipping Kaynakları ve Rehberleri | Reklamatic Blog", description: "Clipping stratejisi, UGC, içerik yeniden kullanımı, ajans seçimi ve kısa video planlaması için pratik rehberler.", kicker: "Kaynak kütüphanesi", headline: "Prodüksiyon satın almadan önce daha iyi clipping brief'i kurun.", lead: "Reklamatic rehber kütüphanesi faydalı kısa video sistemlerinin arkasındaki kararları açıklar. Her rehber eğiticidir, sonuç garantisi içermez ve ilgili sonraki planlama adımına bağlanır.",
    highlights: [["Temeller", "Clipping nedir ve ne değildir?"], ["Strateji", "Kaynak, format ve sinyaller nasıl bağlanır?"], ["Seçim", "Ajans ve kapsam nasıl değerlendirilir?"]],
    sections: [["Temellerle başlayın", "Kaynak hazırlığı, tek başına anlam ve kopyalamayla uyarlama farkı için Clipping Nedir ve İçerik Yeniden Kullanımı rehberlerini okuyun."], ["Doğru kreatif modeli seçin", "Clipping ve UGC rehberi kaynak odaklı editoryal çalışma ile üretici tarzı ürün içeriğinin farkını ve ne zaman ikisinin birlikte gerekebileceğini açıklar."], ["Bilgiyi brief'e dönüştürün", "Teklif istemeden önce kitle, haklar, çıktılar, onaylar, yayın ve ölçümü belgelemek için strateji ve ajans seçimi rehberlerini kullanın."]], cta: "Beş rehberi incele"
  }, ["what-is-clipping", "strategy", "choose-agency"]),
  make("what-is-clipping", "Article", "blog/what-is-clipping", "blog/clipping-nedir", {
    title: "What Is Clipping? A Practical Short-Form Guide", description: "Learn how clipping turns approved long-form sources into self-contained platform-native short videos.", kicker: "Clipping guide 01", headline: "What is clipping—and why is it more than adding captions?", lead: "Clipping is the editorial and production process of finding a meaningful moment inside longer content and rebuilding it as a complete short video for a specific audience and platform.",
    highlights: [["Select", "Choose a moment with standalone value"], ["Rebuild", "Add opening, context, pace and captions"], ["Adapt", "Respect platform behavior and specifications"]],
    sections: [["Clipping versus cropping", "Cropping changes the frame. Clipping changes the communication. A clip needs enough context for someone who never saw the source, while preserving the speaker's meaning and avoiding misleading edits."], ["Sources that can work", "Podcasts, interviews, webinars, founder recordings, lessons, livestreams, product demonstrations and campaign footage may work when rights, audio, image quality and brand rules are suitable."], ["What makes a useful clip", "Look for a clear opening, one main idea, evidence or story movement, readable captions, intentional pacing, platform-safe visuals and an ending that completes the thought or supports an agreed action."]], cta: "Turn my source into a plan"
  }, {
    title: "Clipping Nedir? Pratik Kısa Video Rehberi", description: "Clipping'in onaylı uzun kaynakları nasıl tek başına anlaşılır, platforma doğal kısa videolara dönüştürdüğünü öğrenin.", kicker: "Clipping rehberi 01", headline: "Clipping nedir ve neden altyazı eklemekten fazlasıdır?", lead: "Clipping, uzun içeriğin içindeki anlamlı anı bulup belirli bir kitle ve platform için tamamlanmış kısa video olarak yeniden kuran editoryal ve prodüksiyon sürecidir.",
    highlights: [["Seç", "Tek başına değeri olan anı belirle"], ["Yeniden kur", "Açılış, bağlam, tempo ve altyazı ekle"], ["Uyarla", "Platform davranışı ve teknik özelliklere uy"]],
    sections: [["Clipping ve kırpma farkı", "Kırpma kadrajı değiştirir. Clipping iletişimi değiştirir. Klip, kaynağı hiç görmemiş kişi için yeterli bağlama sahip olmalı; konuşmacının anlamını korumalı ve yanıltıcı kurgudan kaçınmalıdır."], ["Uygun olabilecek kaynaklar", "Haklar, ses, görüntü kalitesi ve marka kuralları uygunsa podcast, röportaj, webinar, kurucu kaydı, ders, canlı yayın, ürün demosu ve kampanya çekimi kullanılabilir."], ["Faydalı klip ne içerir?", "Net açılış, tek ana fikir, kanıt veya hikâye hareketi, okunur altyazı, bilinçli tempo, platforma güvenli görseller ve düşünceyi tamamlayan ya da kabul edilen aksiyonu destekleyen kapanış arayın."]], cta: "Kaynağımı plana dönüştür"
  }, ["repurposing", "strategy", "podcast"]),
  make("clipping-vs-ugc", "Article", "blog/clipping-vs-ugc", "blog/clipping-ve-ugc", {
    title: "Clipping vs UGC | Which Short-Form Model Fits?", description: "Compare source-led clipping and UGC-style content by inputs, control, use cases and measurement.", kicker: "Clipping guide 02", headline: "Clipping and UGC solve different creative problems.", lead: "Clipping rebuilds approved existing source material. UGC-style content is usually created as a new, native-feeling asset around a product, experience or message. Neither format guarantees performance.",
    highlights: [["Clipping", "Starts with long-form or campaign source"], ["UGC", "Starts with a creator-style concept or demonstration"], ["Hybrid", "Uses both when rights and scope support it"]],
    sections: [["Choose clipping when", "Use clipping when valuable expertise, stories, interviews, demos or talks already exist and you want to distribute the strongest moments without producing every asset from scratch."], ["Choose UGC-style production when", "Use UGC-style creative when the concept needs a fresh product demonstration, testimonial-style structure, problem-solution narrative or creator perspective. Claims and disclosures still require approval."], ["Build a hybrid carefully", "A campaign might clip a founder interview while separately producing native demonstrations. Keep source rights, usage terms, disclosures, creator permissions and measurement distinct in the written scope."]], cta: "Choose my creative model"
  }, {
    title: "Clipping ve UGC | Hangi Kısa Video Modeli Uygun?", description: "Kaynak odaklı clipping ile UGC tarzı içeriği girdi, kontrol, kullanım alanı ve ölçüm açısından karşılaştırın.", kicker: "Clipping rehberi 02", headline: "Clipping ve UGC farklı kreatif sorunları çözer.", lead: "Clipping onaylı mevcut kaynağı yeniden kurar. UGC tarzı içerik genellikle ürün, deneyim veya mesaj çevresinde yeni ve platforma doğal hisseden materyal olarak üretilir. Hiçbiri performans garantisi vermez.",
    highlights: [["Clipping", "Uzun veya kampanya kaynağıyla başlar"], ["UGC", "Üretici tarzı konsept veya demoyla başlar"], ["Hibrit", "Hak ve kapsam destekliyorsa ikisini kullanır"]],
    sections: [["Clipping ne zaman seçilir?", "Değerli uzmanlık, hikâye, röportaj, demo veya konuşma zaten varsa ve her materyali sıfırdan üretmeden güçlü anları dağıtmak istiyorsanız clipping kullanın."], ["UGC tarzı üretim ne zaman seçilir?", "Yeni ürün demosu, yorum benzeri yapı, sorun-çözüm anlatısı veya üretici bakışı gerekiyorsa UGC tarzı kreatif kullanın. İddia ve açıklamalar yine onay gerektirir."], ["Hibrit modeli dikkatle kurun", "Kampanya kurucu röportajını kliplerken ayrı doğal demolar üretebilir. Kaynak hakkı, kullanım koşulu, açıklama, üretici izni ve ölçümü yazılı kapsamda ayırın."]], cta: "Kreatif modelimi seç"
  }, ["what-is-clipping", "campaigns", "brands"]),
  make("strategy", "Article", "blog/clipping-strategy", "blog/clipping-stratejisi", {
    title: "Clipping Strategy | From Source to Learning Loop", description: "Build a clipping strategy around audience, source rights, moment selection, platform variants, approval and measurement.", kicker: "Clipping guide 03", headline: "A clipping strategy connects every cut to a decision.", lead: "Strategy prevents a short-form program from becoming a pile of disconnected edits. It defines who the clip is for, what source is safe, which idea is being tested and what happens after delivery.",
    highlights: [["Audience", "One defined viewer and need"], ["Creative", "Moment, hook, proof and format"], ["Learning", "A signal tied to a future decision"]],
    sections: [["Map source to audience", "Inventory source quality, rights, recurring themes and usable moments. Match each content pillar to a specific audience question rather than publishing every excerpt."], ["Design controlled variation", "Test one meaningful difference at a time—opening, duration, framing, proof, caption structure or CTA—while keeping approvals and platform specifications visible."], ["Close the loop", "Document which available signal would change the next decision. Watch behavior may change an opening; saves may support a useful topic; clicks require tracking. No single metric proves total business impact."]], cta: "Build a clipping strategy"
  }, {
    title: "Clipping Stratejisi | Kaynaktan Öğrenme Döngüsüne", description: "Kitle, kaynak hakkı, an seçimi, platform varyantı, onay ve ölçüm etrafında clipping stratejisi kurun.", kicker: "Clipping rehberi 03", headline: "Clipping stratejisi her kurguyu bir karara bağlar.", lead: "Strateji, kısa video programının bağlantısız kurgu yığınına dönüşmesini önler. Klibin kimin için olduğunu, hangi kaynağın güvenli olduğunu, hangi fikrin test edildiğini ve teslim sonrası ne olacağını tanımlar.",
    highlights: [["Kitle", "Tanımlı tek izleyici ve ihtiyaç"], ["Kreatif", "An, açılış, kanıt ve format"], ["Öğrenme", "Gelecek karara bağlı sinyal"]],
    sections: [["Kaynağı kitleyle eşleştirin", "Kaynak kalitesi, haklar, tekrar eden temalar ve kullanılabilir anları envanterleyin. Her parçayı yayınlamak yerine içerik sütunlarını belirli kitle sorularıyla eşleştirin."], ["Kontrollü varyasyon tasarlayın", "Onayları ve platform özelliklerini görünür tutarak açılış, süre, kadraj, kanıt, altyazı yapısı veya harekete geçirici mesajdan birini anlamlı biçimde test edin."], ["Döngüyü kapatın", "Hangi erişilebilir sinyalin sonraki kararı değiştireceğini yazın. İzleme davranışı açılışı, kaydetme faydalı konuyu değiştirebilir; tıklama izleme gerektirir. Tek metrik tüm iş etkisini kanıtlamaz."]], cta: "Clipping stratejisi kur"
  }, ["campaigns", "measurement", "choose-agency"]),
  make("choose-agency", "Article", "blog/how-to-choose-a-clipping-agency", "blog/clipping-ajansi-secimi", {
    title: "How to Choose a Clipping Agency | Evaluation Checklist", description: "Evaluate a clipping agency by editorial process, rights, approvals, platform adaptation, measurement and honest claims.", kicker: "Clipping guide 04", headline: "Choose the process you can audit—not the loudest view claim.", lead: "A strong clipping partner should explain how moments are selected, who approves claims, what is included, who publishes and how reporting limitations are communicated.",
    highlights: [["Ask", "How are moments selected and checked?"], ["Verify", "What rights, access and approvals are required?"], ["Write", "What exactly is delivered, when and by whom?"]],
    sections: [["Evaluate editorial quality", "Ask for the selection logic, context checks, caption process, language review, platform variants and quality-control owner. A polished transition cannot repair a misleading edit."], ["Evaluate operating clarity", "The proposal should identify source responsibility, exclusions, revision rounds, approval timing, publishing access, file delivery, usage terms, reporting period and escalation contacts."], ["Challenge performance claims", "Avoid guaranteed virality, unexplained network reach, borrowed case studies and metrics without date, platform or account scope. Historical screenshots do not equal future client results."]], cta: "Evaluate Reklamatic against this list"
  }, {
    title: "Clipping Ajansı Nasıl Seçilir? | Değerlendirme Listesi", description: "Clipping ajansını editoryal süreç, haklar, onay, platform uyarlaması, ölçüm ve dürüst iddialarla değerlendirin.", kicker: "Clipping rehberi 04", headline: "En yüksek görüntülenme iddiasını değil, denetleyebileceğiniz süreci seçin.", lead: "Güçlü clipping partneri anların nasıl seçildiğini, iddiaları kimin onayladığını, neyin dahil olduğunu, kimin yayın yaptığını ve raporlama sınırlarının nasıl açıklandığını anlatmalıdır.",
    highlights: [["Sor", "Anlar nasıl seçiliyor ve kontrol ediliyor?"], ["Doğrula", "Hangi hak, erişim ve onay gerekiyor?"], ["Yaz", "Tam olarak ne, ne zaman, kim tarafından teslim ediliyor?"]],
    sections: [["Editoryal kaliteyi değerlendirin", "Seçim mantığı, bağlam kontrolü, altyazı süreci, dil incelemesi, platform varyantları ve kalite kontrol sahibini sorun. Parlak geçiş yanıltıcı kurguyu düzeltemez."], ["Operasyon açıklığını değerlendirin", "Teklif kaynak sorumluluğu, hariçler, revizyon, onay zamanı, yayın erişimi, dosya teslimi, kullanım koşulları, rapor dönemi ve müdahale iletişimini belirtmelidir."], ["Performans iddialarını sorgulayın", "Garantili viral sonuç, açıklanmayan ağ erişimi, ödünç vaka çalışmaları ve tarih-platform-hesap kapsamı olmayan metriklerden kaçının. Geçmiş ekranlar gelecek müşteri sonucuna eşit değildir."]], cta: "Reklamatic'i bu listeyle değerlendir"
  }, ["agency", "pricing", "faq"]),
  make("repurposing", "Article", "blog/content-repurposing", "blog/icerik-yeniden-kullanim", {
    title: "Content Repurposing for Short-Form | A Responsible System", description: "Repurpose long-form content into short clips without losing context, rights control or brand consistency.", kicker: "Clipping guide 05", headline: "Repurposing should create new usefulness—not duplicate noise.", lead: "Responsible repurposing selects the parts of a source that deserve a new format, then adds the context, pacing and presentation needed for a different audience environment.",
    highlights: [["Inventory", "Know what source exists and who owns it"], ["Transform", "Adapt meaning, format and presentation"], ["Govern", "Track approvals, versions and usage terms"]],
    sections: [["Prepare the source library", "Record ownership, license limits, speakers, languages, sensitive sections, audio quality, visual quality and approval status. Remove private data before sharing."], ["Create a transformation map", "Connect each useful moment to an audience question, platform, format and intended action. Avoid forcing every source into every channel."], ["Maintain the system", "Use naming, version control, caption files, approval records and learning notes so teams know what was published, what changed and what may be reused again."]], cta: "Audit my source library"
  }, {
    title: "Kısa Video için İçerik Yeniden Kullanımı | Sorumlu Sistem", description: "Bağlamı, hak kontrolünü veya marka tutarlılığını kaybetmeden uzun içeriği kısa kliplere dönüştürün.", kicker: "Clipping rehberi 05", headline: "Yeniden kullanım kopya gürültü değil, yeni fayda üretmelidir.", lead: "Sorumlu yeniden kullanım, kaynağın yeni formatı hak eden bölümlerini seçer; sonra farklı izleyici ortamı için gereken bağlam, tempo ve sunumu ekler.",
    highlights: [["Envanter", "Hangi kaynak var, sahibi kim?"], ["Dönüştür", "Anlamı, formatı ve sunumu uyarla"], ["Yönet", "Onay, versiyon ve kullanım koşullarını izle"]],
    sections: [["Kaynak kütüphanesini hazırlayın", "Sahiplik, lisans sınırı, konuşmacı, dil, hassas bölüm, ses-görüntü kalitesi ve onay durumunu kaydedin. Paylaşmadan önce özel veriyi kaldırın."], ["Dönüşüm haritası oluşturun", "Her faydalı anı kitle sorusu, platform, format ve hedeflenen aksiyonla bağlayın. Her kaynağı her kanala zorlamayın."], ["Sistemi sürdürün", "İsimlendirme, versiyon kontrolü, altyazı dosyası, onay kaydı ve öğrenme notu kullanın; ekip neyin yayınlandığını, değiştiğini ve tekrar kullanılabileceğini bilsin."]], cta: "Kaynak kütüphanemi denetle"
  }, ["what-is-clipping", "podcast", "strategy"]),
  make("podcast", "Service", "services/podcast-clipping", "hizmetler/podcast-clipping", {
    title: "Podcast Clipping Service | Short-Form Episode System", description: "Turn approved podcast episodes into self-contained short clips with moment maps, captions, review and platform variants.", kicker: "Podcast clipping", headline: "Give every strong episode more than one chance to be discovered.", lead: "Podcast clipping finds opinions, stories, lessons and guest moments that can stand alone. Reklamatic rebuilds them for short-form while protecting context and approval.",
    highlights: [["Source", "Approved video or audio episode and transcript"], ["Creative", "Moment map, hooks, captions and reframing"], ["Delivery", "Scoped variants, review and organized files"]],
    sections: [["Moment selection", "We look for one clear idea, tension, practical value or story movement. A short excerpt is rejected when missing context could distort the guest or host."], ["Visual treatment", "Depending on source quality and scope, a clip may use speaker reframing, readable captions, supporting graphics, chapter context and platform-safe layouts."], ["Program design", "A recurring program defines episode intake, exclusions, approval owner, output rhythm, platforms and learning notes. Counts and turnaround are agreed after reviewing the real source."]], cta: "Plan podcast clipping"
  }, {
    title: "Podcast Clipping Hizmeti | Kısa Video Bölüm Sistemi", description: "Onaylı podcast bölümlerini an haritası, altyazı, onay ve platform varyantlarıyla tek başına anlaşılır kısa kliplere dönüştürün.", kicker: "Podcast clipping", headline: "Her güçlü bölüme keşfedilmek için birden fazla fırsat verin.", lead: "Podcast clipping tek başına anlaşılabilen görüş, hikâye, ders ve konuk anlarını bulur. Reklamatic bunları bağlamı ve onayı koruyarak kısa video için yeniden kurar.",
    highlights: [["Kaynak", "Onaylı video/ses bölümü ve transkript"], ["Kreatif", "An haritası, açılış, altyazı ve kadraj"], ["Teslim", "Kapsamlı varyant, değerlendirme ve düzenli dosya"]],
    sections: [["An seçimi", "Tek net fikir, gerilim, pratik değer veya hikâye hareketi ararız. Eksik bağlam konuk veya sunucuyu çarpıtabilecekse kısa bölüm reddedilir."], ["Görsel uygulama", "Kaynak kalitesi ve kapsama göre konuşmacı kadrajı, okunur altyazı, destekleyici grafik, bölüm bağlamı ve platforma güvenli düzen kullanılabilir."], ["Program tasarımı", "Düzenli program bölüm alımı, hariçler, onay sahibi, çıktı düzeni, platformlar ve öğrenme notlarını tanımlar. Adet ve süre gerçek kaynak incelendikten sonra kabul edilir."]], cta: "Podcast clipping planla"
  }, ["what-is-clipping", "repurposing", "campaigns"]),
  make("tiktok", "Service", "services/tiktok-clipping", "hizmetler/tiktok-clipping", {
    title: "TikTok Clipping Service | Platform-Native Short Video", description: "Adapt approved long-form moments for TikTok with clear hooks, captions, pacing, safe zones and review.", kicker: "TikTok clipping", headline: "Adapt the idea for TikTok without flattening its meaning.", lead: "TikTok clipping requires more than a 9:16 crop. The opening, context speed, captions, visual rhythm and safe zones need to support a viewer who encounters the clip cold.",
    highlights: [["Opening", "Immediate context and reason to continue"], ["Format", "Vertical framing, captions and safe zones"], ["Control", "Brand, claim and publishing approval"]],
    sections: [["Creative adaptation", "We identify the central idea, remove unnecessary setup, preserve necessary context and create a clear first frame. Trend use is considered only when it fits rights, brand and shelf life."], ["Platform preparation", "Scope may include 9:16 framing, captions, graphic hierarchy, cover direction and version notes. Final specifications follow the platform and account requirements available at delivery."], ["Measurement boundaries", "Accessible views, watch behavior, completion and engagement can guide iteration. Results vary; a TikTok view is not a guaranteed unique person, lead or sale."]], cta: "Scope TikTok clips"
  }, {
    title: "TikTok Clipping Hizmeti | Platforma Doğal Kısa Video", description: "Onaylı uzun içerik anlarını net açılış, altyazı, tempo, güvenli alan ve onayla TikTok'a uyarlayın.", kicker: "TikTok clipping", headline: "Fikri anlamını düzleştirmeden TikTok'a uyarlayın.", lead: "TikTok clipping, 9:16 kırpmadan fazlasını gerektirir. Açılış, bağlam hızı, altyazı, görsel ritim ve güvenli alanlar kliple ilk kez karşılaşan izleyiciyi desteklemelidir.",
    highlights: [["Açılış", "Anında bağlam ve devam nedeni"], ["Format", "Dikey kadraj, altyazı ve güvenli alan"], ["Kontrol", "Marka, iddia ve yayın onayı"]],
    sections: [["Kreatif uyarlama", "Ana fikri belirler, gereksiz kurulumu çıkarır, gerekli bağlamı korur ve net ilk kare oluştururuz. Trend yalnızca hak, marka ve raf ömrüne uyuyorsa değerlendirilir."], ["Platform hazırlığı", "Kapsam 9:16 kadraj, altyazı, grafik hiyerarşi, kapak yönü ve versiyon notu içerebilir. Son özellikler teslim anındaki platform ve hesap gereksinimini izler."], ["Ölçüm sınırları", "Erişilebilen görüntülenme, izleme davranışı, tamamlama ve etkileşim yinelemeyi yönlendirebilir. Sonuç değişir; TikTok görüntülenmesi garantili tekil kişi, potansiyel müşteri veya satış değildir."]], cta: "TikTok kliplerini kapsamlandır"
  }, ["strategy", "campaigns", "brands"]),
  make("reels", "Service", "services/instagram-reels-clipping", "hizmetler/instagram-reels-clipping", {
    title: "Instagram Reels Clipping Service | Reklamatic", description: "Create context-rich Instagram Reels from approved podcasts, interviews and brand footage with platform adaptation and review.", kicker: "Instagram Reels clipping", headline: "Turn source moments into Reels that make sense without the original post.", lead: "Reels clipping packages a selected idea for mobile viewing while considering captions, composition, cover context, brand language and how the clip may be encountered in feed or profile.",
    highlights: [["Meaning", "A self-contained thought or story"], ["Presentation", "Readable mobile composition and captions"], ["Workflow", "Approval, versions and organized delivery"]],
    sections: [["Source to Reel", "We select a moment, establish the context early, adapt pacing and create a visual hierarchy that supports rather than competes with the speaker or product."], ["Brand consistency", "Typography, colors, claims, logos, disclosures and prohibited topics follow the approved guidance. Third-party music or footage is used only under suitable rights."], ["Learning from Reels", "Available watch and engagement signals may guide later topics or openings. Historical account performance does not predict a client's future result."]], cta: "Plan Reels clipping"
  }, {
    title: "Instagram Reels Clipping Hizmeti | Reklamatic", description: "Onaylı podcast, röportaj ve marka çekimlerinden platform uyarlaması ve onayla bağlamlı Instagram Reels üretin.", kicker: "Instagram Reels clipping", headline: "Kaynak anları özgün gönderi olmadan da anlaşılır Reels videolarına dönüştürün.", lead: "Reels clipping seçili fikri mobil izlemeye hazırlar; altyazı, kompozisyon, kapak bağlamı, marka dili ve klibin akış ya da profilde nasıl görüleceğini dikkate alır.",
    highlights: [["Anlam", "Tek başına fikir veya hikâye"], ["Sunum", "Okunur mobil kompozisyon ve altyazı"], ["İş akışı", "Onay, versiyon ve düzenli teslim"]],
    sections: [["Kaynaktan Reel'e", "Anı seçer, bağlamı erken kurar, tempoyu uyarlar ve konuşmacı ya da ürünle yarışmak yerine onu destekleyen görsel hiyerarşi oluştururuz."], ["Marka tutarlılığı", "Tipografi, renk, iddia, logo, açıklama ve yasaklı konular onaylı rehberi izler. Üçüncü taraf müzik veya görüntü yalnızca uygun haklarla kullanılır."], ["Reels'ten öğrenme", "Erişilebilen izleme ve etkileşim sinyalleri sonraki konu veya açılışı yönlendirebilir. Geçmiş hesap performansı müşterinin gelecek sonucunu tahmin etmez."]], cta: "Reels clipping planla"
  }, ["strategy", "campaigns", "brands"]),
  make("shorts", "Service", "services/youtube-shorts-clipping", "hizmetler/youtube-shorts-clipping", {
    title: "YouTube Shorts Clipping Service | Reklamatic", description: "Repurpose approved long-form YouTube, podcast and education content into structured vertical Shorts.", kicker: "YouTube Shorts clipping", headline: "Build a short discovery layer around your long-form library.", lead: "Shorts clipping can connect useful moments from a long-form library to new viewers. Each clip still needs its own opening, context, pacing, captions and clear relationship to the source strategy.",
    highlights: [["Library", "Approved episodes, lessons and interviews"], ["Structure", "Self-contained vertical narratives"], ["Connection", "Optional source relationship when scoped"]],
    sections: [["Select for discovery", "Choose moments that answer a question, demonstrate expertise or move through a compact story. Do not cut only because a segment is short."], ["Prepare the Short", "Adapt framing, captions, pace, visual support and ending for vertical viewing. Titles, descriptions or source links are included only when agreed in delivery or publishing scope."], ["Review the signal", "Views, watch behavior and engagement may support later decisions where accessible. They do not guarantee subscribers, long-form transfer or conversion."]], cta: "Plan YouTube Shorts"
  }, {
    title: "YouTube Shorts Clipping Hizmeti | Reklamatic", description: "Onaylı uzun YouTube, podcast ve eğitim içeriğini yapılandırılmış dikey Shorts videolarına dönüştürün.", kicker: "YouTube Shorts clipping", headline: "Uzun içerik kütüphanenizin çevresinde kısa keşif katmanı kurun.", lead: "Shorts clipping uzun kütüphanedeki faydalı anları yeni izleyicilerle buluşturabilir. Her klip yine kendi açılışına, bağlamına, temposuna, altyazısına ve kaynak stratejisiyle net ilişkisine ihtiyaç duyar.",
    highlights: [["Kütüphane", "Onaylı bölüm, ders ve röportaj"], ["Yapı", "Tek başına dikey anlatılar"], ["Bağlantı", "Kapsama göre kaynak ilişkisi"]],
    sections: [["Keşif için seçin", "Bir soruyu yanıtlayan, uzmanlığı gösteren veya kısa hikâyede ilerleyen anları seçin. Sırf bölüm kısa diye klip çıkarmayın."], ["Short'u hazırlayın", "Kadraj, altyazı, tempo, görsel destek ve kapanışı dikey izlemeye uyarlayın. Başlık, açıklama veya kaynak linki yalnızca teslim ya da yayın kapsamı kabul edildiyse dahildir."], ["Sinyali değerlendirin", "Erişilebiliyorsa görüntülenme, izleme davranışı ve etkileşim sonraki kararı destekleyebilir. Abone, uzun videoya geçiş veya dönüşüm garantisi vermez."]], cta: "YouTube Shorts planla"
  }, ["repurposing", "strategy", "brands"]),
  make("brands", "Service", "for-brands", "markalar-icin", {
    title: "Clipping for Brands | Campaign Planning and Production", description: "A clear clipping pathway for brands: source review, campaign scope, editing, approval, delivery and measurement.", kicker: "For brands", headline: "Turn approved source material into a controlled short-form program.", lead: "Reklamatic helps brand, product, founder, podcast and education teams add a specialized clipping layer without inventing a creator network or guaranteed distribution model.",
    highlights: [["Bring", "Source, rights, audience, goals and brand rules"], ["Receive", "Written scope, creative plan and approved deliverables"], ["Decide", "Delivery-only or explicitly scoped publishing support"]],
    sections: [["What we need from the brand", "Provide authorized source material, business objective, audience, platform priorities, allowed and prohibited claims, visual rules, disclosure requirements and one accountable approval owner."], ["What Reklamatic can scope", "Options include source audit, moment mapping, clipping strategy, ongoing production, campaign sprints, platform versions, caption files, review rounds, organized delivery and limited publishing support."], ["How success is discussed", "We agree which accessible platform signals matter and what decision each can influence. Organic reach and conversion are not guaranteed; views are not always unique people and attribution has limits."]], cta: "Start a brand brief"
  }, {
    title: "Markalar için Clipping | Kampanya Planlama ve Üretim", description: "Markalar için net clipping yolu: kaynak inceleme, kampanya kapsamı, kurgu, onay, teslim ve ölçüm.", kicker: "Markalar için", headline: "Onaylı kaynak içeriği kontrollü kısa video programına dönüştürün.", lead: "Reklamatic marka, ürün, kurucu, podcast ve eğitim ekiplerine uydurma üretici ağı veya garantili dağıtım modeli olmadan uzman clipping katmanı ekler.",
    highlights: [["Getirin", "Kaynak, haklar, kitle, hedef ve marka kuralları"], ["Alın", "Yazılı kapsam, kreatif plan ve onaylı teslimatlar"], ["Karar verin", "Yalnız teslim veya açıkça kapsamlı yayın desteği"]],
    sections: [["Markadan gerekenler", "Yetkili kaynak, iş amacı, kitle, platform önceliği, izinli-yasaklı iddia, görsel kurallar, açıklama gereksinimi ve hesap verebilir tek onay sahibi sağlayın."], ["Reklamatic neyi kapsamlandırabilir?", "Kaynak denetimi, an haritası, clipping stratejisi, sürekli üretim, kampanya sprinti, platform versiyonu, altyazı dosyası, revizyon, düzenli teslim ve sınırlı yayın desteği seçenekleri vardır."], ["Başarı nasıl konuşulur?", "Hangi erişilebilir platform sinyalinin önemli olduğunu ve hangi kararı etkileyebileceğini kabul ederiz. Organik erişim ve dönüşüm garanti değildir; görüntülenme her zaman tekil kişi değildir, atıf sınırlıdır."]], cta: "Marka brief'i başlat"
  }, ["campaigns", "pricing", "cases"]),
  make("clippers", "WebPage", "for-clippers", "clipper-ol", {
    title: "For Clippers and Editors | Share Your Interest", description: "Share a public clipping portfolio, platforms, languages and specialties for possible future Reklamatic collaboration.", kicker: "For clippers", headline: "Share your craft—without a false promise of instant work.", lead: "Reklamatic currently collects interest from editors and short-form specialists. This is not an automated membership portal, live job marketplace, performance-pay system or guarantee of onboarding.",
    highlights: [["Portfolio", "Public work viewable without passwords"], ["Specialties", "Formats, platforms, languages and motion skills"], ["Status", "Interest collection for possible future matching"]],
    sections: [["What to share", "Provide a public portfolio, strongest short-form formats, platform experience, languages, caption and motion capability, working availability and quality-control approach."], ["What not to share", "Do not submit confidential client files, private links, passwords, access tokens, personal data or material you are not authorized to show."], ["What happens next", "Reklamatic may review and retain the contact email under the privacy policy for relevant future communication. Submission does not guarantee response time, onboarding, assignments, rates or earnings."]], cta: "Open the clipper-interest form"
  }, {
    title: "Clipper ve Editörler için | İlginizi Paylaşın", description: "Gelecekteki olası Reklamatic iş birliği için herkese açık clipping portfolyonuzu, platform, dil ve uzmanlıklarınızı paylaşın.", kicker: "Clipper adayları için", headline: "Anında iş sözü olmadan yeteneğinizi paylaşın.", lead: "Reklamatic şu anda editör ve kısa video uzmanlarından ilgi toplar. Bu otomatik üyelik portalı, canlı iş pazaryeri, performans ödeme sistemi veya onboarding garantisi değildir.",
    highlights: [["Portfolyo", "Parolasız görülebilen herkese açık işler"], ["Uzmanlık", "Format, platform, dil ve hareketli grafik"], ["Durum", "Gelecekteki olası eşleşme için ilgi toplama"]],
    sections: [["Ne paylaşılmalı?", "Herkese açık portfolyo, en güçlü kısa video formatları, platform deneyimi, diller, altyazı ve hareketli grafik becerisi, uygunluk ve kalite kontrol yaklaşımınızı paylaşın."], ["Ne paylaşılmamalı?", "Gizli müşteri dosyası, özel link, parola, erişim token'ı, kişisel veri veya gösterme yetkiniz olmayan materyal göndermeyin."], ["Sonra ne olur?", "Reklamatic portfolyoyu inceleyebilir ve gizlilik politikasına göre ilgili gelecek iletişimi için e-postayı saklayabilir. Gönderim yanıt süresi, onboarding, görev, ücret veya kazanç garantisi vermez."]], cta: "Clipper ilgi formunu aç"
  }, ["what-is-clipping", "faq", "contact"]),
  make("contact", "ContactPage", "contact", "iletisim", {
    title: "Contact Reklamatic | Brand Brief or Clipper Interest", description: "Contact Reklamatic for a brand clipping scope or share clipper interest through clear separate pathways.", kicker: "Contact", headline: "Bring a brand brief or a public clipper portfolio.", lead: "Choose the relevant path before emailing. The website form prepares an email in your own mail application; it does not upload files, create accounts or promise a placement.",
    highlights: [["Email", "info@reklamatic.ai"], ["Phone", "+90 530 231 29 47"], ["Safety", "Never send passwords, tokens or unauthorized files"]],
    sections: [["Brand inquiries", "Include company or channel, market, target platforms, indicative budget, public source URL, service interest and the business question the clips should support."], ["Clipper interest", "Include a public portfolio URL, specialty, platform experience, languages, availability and a short note on your editing and quality-control approach."], ["Privacy and response", "Use only contact information you are authorized to share and read the privacy policy. Email does not create a service agreement, account, onboarding or guaranteed response time."]], cta: "Go to the secure contact choices"
  }, {
    title: "Reklamatic İletişim | Marka Brief'i veya Clipper İlgisi", description: "Net biçimde ayrılmış yollarla marka clipping kapsamı için Reklamatic'e ulaşın veya clipper ilginizi paylaşın.", kicker: "İletişim", headline: "Marka brief'i veya herkese açık clipper portfolyosu getirin.", lead: "E-posta göndermeden ilgili yolu seçin. Site formu kendi e-posta uygulamanızda mesaj hazırlar; dosya yüklemez, hesap açmaz veya yerleşim sözü vermez.",
    highlights: [["E-posta", "info@reklamatic.ai"], ["Telefon", "+90 530 231 29 47"], ["Güvenlik", "Parola, token veya yetkisiz dosya göndermeyin"]],
    sections: [["Marka talepleri", "Şirket veya kanal, pazar, hedef platformlar, tahmini bütçe, herkese açık kaynak URL'si, hizmet ilgisi ve kliplerin destekleyeceği iş sorusunu ekleyin."], ["Clipper ilgisi", "Herkese açık portfolyo URL'si, uzmanlık, platform deneyimi, diller, uygunluk ve kurgu-kalite kontrol yaklaşımınız hakkında kısa not ekleyin."], ["Gizlilik ve yanıt", "Yalnızca paylaşma yetkiniz olan iletişim bilgisini kullanın ve gizlilik politikasını okuyun. E-posta hizmet sözleşmesi, hesap, onboarding veya garantili yanıt süresi oluşturmaz."]], cta: "Güvenli iletişim seçeneklerine git"
  }, ["brands", "clippers", "faq"]),
];

export const findSeoPage = (locale, path) => seoPages.find((page) => page.paths[locale] === path);
export const routeParams = (locale) => seoPages.map((page) => ({ slug: page.paths[locale].split("/") }));
